// Copyright 2024 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/scheduling/v1alpha/scheduling.proto

package v1alpha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scheduling_ReceiveRequests_FullMethodName = "/aalyria.spacetime.scheduling.v1alpha.Scheduling/ReceiveRequests"
	Scheduling_Reset_FullMethodName           = "/aalyria.spacetime.scheduling.v1alpha.Scheduling/Reset"
)

// SchedulingClient is the client API for Scheduling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingClient interface {
	// Establishes a bidirectional stream through which the SDN controller may
	// send scheduling requests to the SDN agent, and the agent may respond.
	//
	// The use of the stream allows the SDN controller to send requests to the
	// agent even though the SDN controller may not be able to initiate a
	// connection to the agent (if the agent is behind a firewall, for example,
	// or a NAT gateway).
	//
	// The SDN controller will leave the stream open indefinitely. In the event
	// that the stream closes, the agent should re-establish the stream to
	// continue receiving requests.
	ReceiveRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController], error)
	// Notifies the SDN controller that an agent's schedule has been reset. The
	// agent must call this upon startup and after any event that has reset the
	// schedule.
	Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type schedulingClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingClient(cc grpc.ClientConnInterface) SchedulingClient {
	return &schedulingClient{cc}
}

func (c *schedulingClient) ReceiveRequests(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Scheduling_ServiceDesc.Streams[0], Scheduling_ReceiveRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduling_ReceiveRequestsClient = grpc.BidiStreamingClient[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController]

func (c *schedulingClient) Reset(ctx context.Context, in *ResetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Scheduling_Reset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServer is the server API for Scheduling service.
// All implementations must embed UnimplementedSchedulingServer
// for forward compatibility.
type SchedulingServer interface {
	// Establishes a bidirectional stream through which the SDN controller may
	// send scheduling requests to the SDN agent, and the agent may respond.
	//
	// The use of the stream allows the SDN controller to send requests to the
	// agent even though the SDN controller may not be able to initiate a
	// connection to the agent (if the agent is behind a firewall, for example,
	// or a NAT gateway).
	//
	// The SDN controller will leave the stream open indefinitely. In the event
	// that the stream closes, the agent should re-establish the stream to
	// continue receiving requests.
	ReceiveRequests(grpc.BidiStreamingServer[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController]) error
	// Notifies the SDN controller that an agent's schedule has been reset. The
	// agent must call this upon startup and after any event that has reset the
	// schedule.
	Reset(context.Context, *ResetRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSchedulingServer()
}

// UnimplementedSchedulingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingServer struct{}

func (UnimplementedSchedulingServer) ReceiveRequests(grpc.BidiStreamingServer[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController]) error {
	return status.Error(codes.Unimplemented, "method ReceiveRequests not implemented")
}
func (UnimplementedSchedulingServer) Reset(context.Context, *ResetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedSchedulingServer) mustEmbedUnimplementedSchedulingServer() {}
func (UnimplementedSchedulingServer) testEmbeddedByValue()                    {}

// UnsafeSchedulingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServer will
// result in compilation errors.
type UnsafeSchedulingServer interface {
	mustEmbedUnimplementedSchedulingServer()
}

func RegisterSchedulingServer(s grpc.ServiceRegistrar, srv SchedulingServer) {
	// If the following call panics, it indicates UnimplementedSchedulingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scheduling_ServiceDesc, srv)
}

func _Scheduling_ReceiveRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SchedulingServer).ReceiveRequests(&grpc.GenericServerStream[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Scheduling_ReceiveRequestsServer = grpc.BidiStreamingServer[ReceiveRequestsMessageToController, ReceiveRequestsMessageFromController]

func _Scheduling_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduling_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServer).Reset(ctx, req.(*ResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduling_ServiceDesc is the grpc.ServiceDesc for Scheduling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aalyria.spacetime.scheduling.v1alpha.Scheduling",
	HandlerType: (*SchedulingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reset",
			Handler:    _Scheduling_Reset_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveRequests",
			Handler:       _Scheduling_ReceiveRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/scheduling/v1alpha/scheduling.proto",
}
