// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file contains messages used to model antenna radiation patterns.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/nbi/v1alpha/resources/antenna_pattern.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Models an antenna pattern. Multiple platform definitions can
// reference the same antenna pattern.
type AntennaPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PatternType:
	//
	//	*AntennaPattern_CustomPhiThetaPattern
	//	*AntennaPattern_GaussianPattern
	//	*AntennaPattern_HelicalPattern
	//	*AntennaPattern_IsotropicPattern
	//	*AntennaPattern_ParabolicPattern
	//	*AntennaPattern_SquareHornPattern
	//	*AntennaPattern_GaussianOpticalPattern
	//	*AntennaPattern_PhasedArrayPattern
	//	*AntennaPattern_NearAndFarFieldPattern
	//	*AntennaPattern_TransmitterAndReceiverPattern
	//	*AntennaPattern_CustomAntennaPatternPerAngle_
	//	*AntennaPattern_CustomAzElPattern
	PatternType   isAntennaPattern_PatternType `protobuf_oneof:"pattern_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern) Reset() {
	*x = AntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern) ProtoMessage() {}

func (x *AntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0}
}

func (x *AntennaPattern) GetPatternType() isAntennaPattern_PatternType {
	if x != nil {
		return x.PatternType
	}
	return nil
}

func (x *AntennaPattern) GetCustomPhiThetaPattern() *AntennaPattern_CustomPhiThetaAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_CustomPhiThetaPattern); ok {
			return x.CustomPhiThetaPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetGaussianPattern() *AntennaPattern_GaussianAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_GaussianPattern); ok {
			return x.GaussianPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetHelicalPattern() *AntennaPattern_HelicalAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_HelicalPattern); ok {
			return x.HelicalPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetIsotropicPattern() *AntennaPattern_IsotropicAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_IsotropicPattern); ok {
			return x.IsotropicPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetParabolicPattern() *AntennaPattern_ParabolicAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_ParabolicPattern); ok {
			return x.ParabolicPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetSquareHornPattern() *AntennaPattern_SquareHornAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_SquareHornPattern); ok {
			return x.SquareHornPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetGaussianOpticalPattern() *AntennaPattern_GaussianOpticalAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_GaussianOpticalPattern); ok {
			return x.GaussianOpticalPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetPhasedArrayPattern() *AntennaPattern_PhasedArrayAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_PhasedArrayPattern); ok {
			return x.PhasedArrayPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetNearAndFarFieldPattern() *AntennaPattern_NearAndFarFieldAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_NearAndFarFieldPattern); ok {
			return x.NearAndFarFieldPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetTransmitterAndReceiverPattern() *AntennaPattern_TransmitterAndReceiverAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_TransmitterAndReceiverPattern); ok {
			return x.TransmitterAndReceiverPattern
		}
	}
	return nil
}

func (x *AntennaPattern) GetCustomAntennaPatternPerAngle() *AntennaPattern_CustomAntennaPatternPerAngle {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_CustomAntennaPatternPerAngle_); ok {
			return x.CustomAntennaPatternPerAngle
		}
	}
	return nil
}

func (x *AntennaPattern) GetCustomAzElPattern() *AntennaPattern_CustomAzElAntennaPattern {
	if x != nil {
		if x, ok := x.PatternType.(*AntennaPattern_CustomAzElPattern); ok {
			return x.CustomAzElPattern
		}
	}
	return nil
}

type isAntennaPattern_PatternType interface {
	isAntennaPattern_PatternType()
}

type AntennaPattern_CustomPhiThetaPattern struct {
	CustomPhiThetaPattern *AntennaPattern_CustomPhiThetaAntennaPattern `protobuf:"bytes,1,opt,name=custom_phi_theta_pattern,json=customPhiThetaPattern,oneof"`
}

type AntennaPattern_GaussianPattern struct {
	GaussianPattern *AntennaPattern_GaussianAntennaPattern `protobuf:"bytes,2,opt,name=gaussian_pattern,json=gaussianPattern,oneof"`
}

type AntennaPattern_HelicalPattern struct {
	HelicalPattern *AntennaPattern_HelicalAntennaPattern `protobuf:"bytes,3,opt,name=helical_pattern,json=helicalPattern,oneof"`
}

type AntennaPattern_IsotropicPattern struct {
	IsotropicPattern *AntennaPattern_IsotropicAntennaPattern `protobuf:"bytes,4,opt,name=isotropic_pattern,json=isotropicPattern,oneof"`
}

type AntennaPattern_ParabolicPattern struct {
	ParabolicPattern *AntennaPattern_ParabolicAntennaPattern `protobuf:"bytes,5,opt,name=parabolic_pattern,json=parabolicPattern,oneof"`
}

type AntennaPattern_SquareHornPattern struct {
	SquareHornPattern *AntennaPattern_SquareHornAntennaPattern `protobuf:"bytes,6,opt,name=square_horn_pattern,json=squareHornPattern,oneof"`
}

type AntennaPattern_GaussianOpticalPattern struct {
	GaussianOpticalPattern *AntennaPattern_GaussianOpticalAntennaPattern `protobuf:"bytes,7,opt,name=gaussian_optical_pattern,json=gaussianOpticalPattern,oneof"`
}

type AntennaPattern_PhasedArrayPattern struct {
	PhasedArrayPattern *AntennaPattern_PhasedArrayAntennaPattern `protobuf:"bytes,10,opt,name=phased_array_pattern,json=phasedArrayPattern,oneof"`
}

type AntennaPattern_NearAndFarFieldPattern struct {
	NearAndFarFieldPattern *AntennaPattern_NearAndFarFieldAntennaPattern `protobuf:"bytes,9,opt,name=near_and_far_field_pattern,json=nearAndFarFieldPattern,oneof"`
}

type AntennaPattern_TransmitterAndReceiverPattern struct {
	TransmitterAndReceiverPattern *AntennaPattern_TransmitterAndReceiverAntennaPattern `protobuf:"bytes,11,opt,name=transmitter_and_receiver_pattern,json=transmitterAndReceiverPattern,oneof"`
}

type AntennaPattern_CustomAntennaPatternPerAngle_ struct {
	CustomAntennaPatternPerAngle *AntennaPattern_CustomAntennaPatternPerAngle `protobuf:"bytes,12,opt,name=custom_antenna_pattern_per_angle,json=customAntennaPatternPerAngle,oneof"`
}

type AntennaPattern_CustomAzElPattern struct {
	CustomAzElPattern *AntennaPattern_CustomAzElAntennaPattern `protobuf:"bytes,13,opt,name=custom_az_el_pattern,json=customAzElPattern,oneof"`
}

func (*AntennaPattern_CustomPhiThetaPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_GaussianPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_HelicalPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_IsotropicPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_ParabolicPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_SquareHornPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_GaussianOpticalPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_PhasedArrayPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_NearAndFarFieldPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_TransmitterAndReceiverPattern) isAntennaPattern_PatternType() {}

func (*AntennaPattern_CustomAntennaPatternPerAngle_) isAntennaPattern_PatternType() {}

func (*AntennaPattern_CustomAzElPattern) isAntennaPattern_PatternType() {}

// A custom antenna pattern defined through spherical coordinates
// (IEEE 149-1979).
// This message can be used to define any 3D antenna pattern.
//
// For further reference on the spherical coordinate system used,
// see the "physics convention" at
// https://en.wikipedia.org/wiki/Spherical_coordinate_system.
type AntennaPattern_CustomPhiThetaAntennaPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From this message, a 2D array is created, where rows are phi cuts
	// through the antenna pattern, columns are theta cuts through the antenna
	// pattern, and the values represent the gain in decibels.
	//
	// Requirements:
	// 1) No missing values can exist in this array. For example, suppose an
	// antenna pattern is defined for phi = {0, π/6, π/4} and
	// theta = {0, π/9, 2π/9, 2π/5, 3π/8}. A gain value corresponding to each
	// entry in this 2D array must be provided, such as in this notional
	// example:
	//
	//	         Theta (θ)
	//	Phi (φ) |    0      |    π/9    |    2π/9   |    2π/5   |    3π/8   |
	//	---------------------------------------------------------------------
	//	 0      |    20     |    18     |    16     |    15     |    14     |
	//	 π/6    |    18     |    16     |    14     |    12     |    11     |
	//	 π/4    |    16     |    14     |    12     |    10     |    10     |
	//
	// In this example, the gain_value field must contain 15 elements that
	// correspond to each element of this array.
	//
	// 2) There must be strictly more than 1 phi point and strictly more than 1
	// theta point. The smallest array allowed is 2x2.
	//
	// Notes:
	// 1) The gain in directions that fall between the defined data will
	// be interpolated using bilinear interpolation in decibels
	// (https://en.wikipedia.org/wiki/Bilinear_interpolation). The gain in
	// directions that fall outside the defined data will yield 0 (-infinity dB)
	// gain.
	//
	// 2) The elements are not required to be sorted in any particular order.
	//
	// 3) The interval between the phi angles does not need to be consistent.
	// The interval between the theta angles does not need to be consistent.
	//
	// Required.
	GainValue     []*AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue `protobuf:"bytes,1,rep,name=gain_value,json=gainValue" json:"gain_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern) Reset() {
	*x = AntennaPattern_CustomPhiThetaAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_CustomPhiThetaAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_CustomPhiThetaAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_CustomPhiThetaAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern) GetGainValue() []*AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue {
	if x != nil {
		return x.GainValue
	}
	return nil
}

// An antenna pattern defined through azimuth and elevation in a rectangular
// coordinate system.
//
// Because of the coordinate system used, this message is a natural choice to
// model the gain patterns of fixed LEO or GEO beams. When a platform's motion
// is defined as a TLE, the axes of the platform orients the positive z-axis
// along the negative position vector, the positive x-axis along the
// velocity vector, and the positive y-axis along the negative angular
// momentum vector. Consider a GEO satellite in an equatorial orbit, orbiting
// from west to east. This axes orients the z-axis towards the Earth, the
// positive x-axis towards the east, and the positive y-axis towards the
// south. Based on the definitions below, azimuth is measured from nadir
// towards the east, and elevation is measured from the Equator towards the
// north.
type AntennaPattern_CustomAzElAntennaPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From this message, a 2D array is created, where rows are azimuth cuts
	// through the antenna pattern, columns are elevation cuts through the
	// antenna patterns, and the values represent the gain in decibels.
	//
	// To compute the gain for a given link vector, the vector is decomposed
	// into its x, y, and z components. The arctan(x/z) yields the azimuth angle
	// for the link, and the arctan(-y/z) yields the elevation angle. The gain
	// corresponding to this azimuth and elevation is then looked up in the 2D
	// array.
	//
	// Requirements:
	// 1) No missing values can exist in this array. For example, suppose an
	// antenna pattern is defined for phi = {0°, 30°, 60°} and
	// theta = {0°, 2°, 4°, 6°}. A gain value corresponding to each entry in
	// this 2D array must be provided, such as in this notional example:
	//
	//	         Theta (θ)
	//	Phi (φ) |    0°     |    2°     |    4°     |    6°     |
	//	---------------------------------------------------------
	//	 0°     |    20     |    18     |    16     |    15     |
	//	 30°    |    18     |    16     |    14     |    12     |
	//	 60°    |    16     |    14     |    12     |    10     |
	//
	// In this example, the gain_value field must contain 12 elements that
	// correspond to each element of this array.
	//
	// 2) The azimuth angles must have an equal interval between them. The
	// elevation angles must have an equal interval between them. The interval
	// between the azimuth angles does not have to be equal to the interval
	// between the elevation angles.
	//
	// Notes:
	// 1) To compute the gain in directions that fall between the defined data,
	// the azimuth and elevation is rounded to the nearest angle for which gain
	// values exist, and the corresponding gain is returned. The gain in
	// directions that fall outside the defined range is clamped to the minimum
	// or maximum angle for which a gain value is defined.
	// TODO: Implement an interpolation approach.
	//
	// 2) The elements are not required to be sorted in any particular order.
	// Required.
	GainValues    []*AntennaPattern_CustomAzElAntennaPattern_AzElGainValue `protobuf:"bytes,1,rep,name=gain_values,json=gainValues" json:"gain_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_CustomAzElAntennaPattern) Reset() {
	*x = AntennaPattern_CustomAzElAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_CustomAzElAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_CustomAzElAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_CustomAzElAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_CustomAzElAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_CustomAzElAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AntennaPattern_CustomAzElAntennaPattern) GetGainValues() []*AntennaPattern_CustomAzElAntennaPattern_AzElGainValue {
	if x != nil {
		return x.GainValues
	}
	return nil
}

// An antenna pattern that represents a unique 3D gain pattern at various
// scan angles.
//
// This message is a natural choice to model the antenna patterns of phased
// array or electronically steered antennas. The same coordinate system as
// CustomPhiThetaAntennaPattern is used here.
type AntennaPattern_CustomAntennaPatternPerAngle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// From this message, a 4D array is created, where for each scan angle, a
	// 2D array is stored to represent the 3D antenna pattern at this scan
	// angle.
	//
	// Requirements:
	// 1) No missing values can exist in this array. For example, suppose an
	// antenna pattern is defined for scan angles of phi = {0, π/3} and
	// theta = {0, π/4}. For each scan angle, suppose we have the gain defined
	// at 4 look angles, at phi = {0, π/8} and theta = {0, π/8}.
	// Conceptually, the array would resemble:
	//
	//	                     Scan Angle Theta (θ)
	//	 Scan Angle Phi (φ) |            0          |          π/4          |
	//	 --------------------------------------------------------------------
	//	                    |    20     |    18     |    16     |    15     |
	//	          0         |_ _ _ _ _ _|_ _ _ _ _ _| _ _ _ _ _ |_ _ _ _ _ _|
	//	                    |    19     |    17     |    17     |    13     |
	//	____________________|___________|___________|___________|___________|
	//	                    |    17     |    17     |    14     |    15     |
	//	          π/3       |_ _ _ _ _ _|_ _ _ _ _ _| _ _ _ _ _ |_ _ _ _ _ _|
	//	                    |    16     |    15     |    12     |    11     |
	//	____________________|___________|___________|___________|___________|
	//
	// where each "inner" 2D array corresponds to the gain values at the look
	// angles.
	//
	// In this example, the scan_angle_and_custom_patterns field must contain 4
	// elements, and each CustomPhiThetaAntennaPattern must contain 4 elements
	// in the gain_value field.
	//
	// 2) The phi angles must have an equal interval between them. The theta
	// angles must have an equal interval between them. The interval for the phi
	// angles does not have to be the same as the interval for the theta angles.
	// The intervals for the scan angles do not have to be the same as the
	// intervals for the look angles. Within each CustomPhiThetaAntennaPattern,
	// unlike a standalone CustomPhiThetaAntennaPattern, the phi and theta
	// angles must each have an equal interval between them, and must have the
	// same phi and theta range across elements.
	//
	// Notes:
	// 1) To compute the gain in directions that fall between the defined data,
	// the phi and theta is rounded to the nearest angle for which gain values
	// exist, and the corresponding gain is returned. The gain in directions
	// that fall outside the defined range is clamped to the minimum or maximum
	// angle for which a gain value is defined.
	// TODO: Implement an interpolation approach.
	//
	// 2) The elements are not required to be sorted in any particular order.
	//
	// Required.
	ScanAngleAndCustomPatterns []*AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern `protobuf:"bytes,1,rep,name=scan_angle_and_custom_patterns,json=scanAngleAndCustomPatterns" json:"scan_angle_and_custom_patterns,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle) Reset() {
	*x = AntennaPattern_CustomAntennaPatternPerAngle{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_CustomAntennaPatternPerAngle) ProtoMessage() {}

func (x *AntennaPattern_CustomAntennaPatternPerAngle) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_CustomAntennaPatternPerAngle.ProtoReflect.Descriptor instead.
func (*AntennaPattern_CustomAntennaPatternPerAngle) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 2}
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle) GetScanAngleAndCustomPatterns() []*AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern {
	if x != nil {
		return x.ScanAngleAndCustomPatterns
	}
	return nil
}

type AntennaPattern_GaussianAntennaPattern struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiameterM         *float64               `protobuf:"fixed64,1,opt,name=diameter_m,json=diameterM" json:"diameter_m,omitempty"`
	EfficiencyPercent *float64               `protobuf:"fixed64,2,opt,name=efficiency_percent,json=efficiencyPercent" json:"efficiency_percent,omitempty"`
	BacklobeGainDb    *float64               `protobuf:"fixed64,3,opt,name=backlobe_gain_db,json=backlobeGainDb" json:"backlobe_gain_db,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AntennaPattern_GaussianAntennaPattern) Reset() {
	*x = AntennaPattern_GaussianAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_GaussianAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_GaussianAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_GaussianAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_GaussianAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_GaussianAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 3}
}

func (x *AntennaPattern_GaussianAntennaPattern) GetDiameterM() float64 {
	if x != nil && x.DiameterM != nil {
		return *x.DiameterM
	}
	return 0
}

func (x *AntennaPattern_GaussianAntennaPattern) GetEfficiencyPercent() float64 {
	if x != nil && x.EfficiencyPercent != nil {
		return *x.EfficiencyPercent
	}
	return 0
}

func (x *AntennaPattern_GaussianAntennaPattern) GetBacklobeGainDb() float64 {
	if x != nil && x.BacklobeGainDb != nil {
		return *x.BacklobeGainDb
	}
	return 0
}

type AntennaPattern_HelicalAntennaPattern struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiameterM         *float64               `protobuf:"fixed64,1,opt,name=diameter_m,json=diameterM" json:"diameter_m,omitempty"`
	EfficiencyPercent *float64               `protobuf:"fixed64,2,opt,name=efficiency_percent,json=efficiencyPercent" json:"efficiency_percent,omitempty"`
	BacklobeGainDb    *float64               `protobuf:"fixed64,3,opt,name=backlobe_gain_db,json=backlobeGainDb" json:"backlobe_gain_db,omitempty"`
	NumberOfTurns     *float64               `protobuf:"fixed64,4,opt,name=number_of_turns,json=numberOfTurns" json:"number_of_turns,omitempty"`
	TurnSpacingM      *float64               `protobuf:"fixed64,5,opt,name=turn_spacing_m,json=turnSpacingM" json:"turn_spacing_m,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AntennaPattern_HelicalAntennaPattern) Reset() {
	*x = AntennaPattern_HelicalAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_HelicalAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_HelicalAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_HelicalAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_HelicalAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_HelicalAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 4}
}

func (x *AntennaPattern_HelicalAntennaPattern) GetDiameterM() float64 {
	if x != nil && x.DiameterM != nil {
		return *x.DiameterM
	}
	return 0
}

func (x *AntennaPattern_HelicalAntennaPattern) GetEfficiencyPercent() float64 {
	if x != nil && x.EfficiencyPercent != nil {
		return *x.EfficiencyPercent
	}
	return 0
}

func (x *AntennaPattern_HelicalAntennaPattern) GetBacklobeGainDb() float64 {
	if x != nil && x.BacklobeGainDb != nil {
		return *x.BacklobeGainDb
	}
	return 0
}

func (x *AntennaPattern_HelicalAntennaPattern) GetNumberOfTurns() float64 {
	if x != nil && x.NumberOfTurns != nil {
		return *x.NumberOfTurns
	}
	return 0
}

func (x *AntennaPattern_HelicalAntennaPattern) GetTurnSpacingM() float64 {
	if x != nil && x.TurnSpacingM != nil {
		return *x.TurnSpacingM
	}
	return 0
}

type AntennaPattern_IsotropicAntennaPattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_IsotropicAntennaPattern) Reset() {
	*x = AntennaPattern_IsotropicAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_IsotropicAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_IsotropicAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_IsotropicAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_IsotropicAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_IsotropicAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 5}
}

type AntennaPattern_ParabolicAntennaPattern struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiameterM         *float64               `protobuf:"fixed64,1,opt,name=diameter_m,json=diameterM" json:"diameter_m,omitempty"`
	EfficiencyPercent *float64               `protobuf:"fixed64,2,opt,name=efficiency_percent,json=efficiencyPercent" json:"efficiency_percent,omitempty"`
	BacklobeGainDb    *float64               `protobuf:"fixed64,3,opt,name=backlobe_gain_db,json=backlobeGainDb" json:"backlobe_gain_db,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AntennaPattern_ParabolicAntennaPattern) Reset() {
	*x = AntennaPattern_ParabolicAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_ParabolicAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_ParabolicAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_ParabolicAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_ParabolicAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_ParabolicAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 6}
}

func (x *AntennaPattern_ParabolicAntennaPattern) GetDiameterM() float64 {
	if x != nil && x.DiameterM != nil {
		return *x.DiameterM
	}
	return 0
}

func (x *AntennaPattern_ParabolicAntennaPattern) GetEfficiencyPercent() float64 {
	if x != nil && x.EfficiencyPercent != nil {
		return *x.EfficiencyPercent
	}
	return 0
}

func (x *AntennaPattern_ParabolicAntennaPattern) GetBacklobeGainDb() float64 {
	if x != nil && x.BacklobeGainDb != nil {
		return *x.BacklobeGainDb
	}
	return 0
}

type AntennaPattern_SquareHornAntennaPattern struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DiameterM         *float64               `protobuf:"fixed64,1,opt,name=diameter_m,json=diameterM" json:"diameter_m,omitempty"`
	EfficiencyPercent *float64               `protobuf:"fixed64,2,opt,name=efficiency_percent,json=efficiencyPercent" json:"efficiency_percent,omitempty"`
	BacklobeGainDb    *float64               `protobuf:"fixed64,3,opt,name=backlobe_gain_db,json=backlobeGainDb" json:"backlobe_gain_db,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AntennaPattern_SquareHornAntennaPattern) Reset() {
	*x = AntennaPattern_SquareHornAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_SquareHornAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_SquareHornAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_SquareHornAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_SquareHornAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_SquareHornAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 7}
}

func (x *AntennaPattern_SquareHornAntennaPattern) GetDiameterM() float64 {
	if x != nil && x.DiameterM != nil {
		return *x.DiameterM
	}
	return 0
}

func (x *AntennaPattern_SquareHornAntennaPattern) GetEfficiencyPercent() float64 {
	if x != nil && x.EfficiencyPercent != nil {
		return *x.EfficiencyPercent
	}
	return 0
}

func (x *AntennaPattern_SquareHornAntennaPattern) GetBacklobeGainDb() float64 {
	if x != nil && x.BacklobeGainDb != nil {
		return *x.BacklobeGainDb
	}
	return 0
}

type AntennaPattern_GaussianOpticalAntennaPattern struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DiameterM          *float64               `protobuf:"fixed64,1,opt,name=diameter_m,json=diameterM" json:"diameter_m,omitempty"`
	EfficiencyPercent  *float64               `protobuf:"fixed64,2,opt,name=efficiency_percent,json=efficiencyPercent" json:"efficiency_percent,omitempty"`
	DivergenceAngleRad *float64               `protobuf:"fixed64,3,opt,name=divergence_angle_rad,json=divergenceAngleRad" json:"divergence_angle_rad,omitempty"`
	PointingErrorRad   *float64               `protobuf:"fixed64,4,opt,name=pointing_error_rad,json=pointingErrorRad" json:"pointing_error_rad,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) Reset() {
	*x = AntennaPattern_GaussianOpticalAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_GaussianOpticalAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_GaussianOpticalAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_GaussianOpticalAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 8}
}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) GetDiameterM() float64 {
	if x != nil && x.DiameterM != nil {
		return *x.DiameterM
	}
	return 0
}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) GetEfficiencyPercent() float64 {
	if x != nil && x.EfficiencyPercent != nil {
		return *x.EfficiencyPercent
	}
	return 0
}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) GetDivergenceAngleRad() float64 {
	if x != nil && x.DivergenceAngleRad != nil {
		return *x.DivergenceAngleRad
	}
	return 0
}

func (x *AntennaPattern_GaussianOpticalAntennaPattern) GetPointingErrorRad() float64 {
	if x != nil && x.PointingErrorRad != nil {
		return *x.PointingErrorRad
	}
	return 0
}

type AntennaPattern_PhasedArrayAntennaPattern struct {
	state                 protoimpl.MessageState                              `protogen:"open.v1"`
	DesignFrequencyHz     *float64                                            `protobuf:"fixed64,1,opt,name=design_frequency_hz,json=designFrequencyHz" json:"design_frequency_hz,omitempty"`
	BacklobeSuppressionDb *float64                                            `protobuf:"fixed64,2,opt,name=backlobe_suppression_db,json=backlobeSuppressionDb" json:"backlobe_suppression_db,omitempty"`
	Elements              []*AntennaPattern_PhasedArrayAntennaPattern_Element `protobuf:"bytes,3,rep,name=elements" json:"elements,omitempty"`
	// Types that are valid to be assigned to Beamformer:
	//
	//	*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer_
	Beamformer                  isAntennaPattern_PhasedArrayAntennaPattern_Beamformer                 `protobuf_oneof:"beamformer"`
	CosineExponentElementFactor *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor `protobuf:"bytes,5,opt,name=cosine_exponent_element_factor,json=cosineExponentElementFactor" json:"cosine_exponent_element_factor,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) Reset() {
	*x = AntennaPattern_PhasedArrayAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_PhasedArrayAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_PhasedArrayAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_PhasedArrayAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_PhasedArrayAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 9}
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) GetDesignFrequencyHz() float64 {
	if x != nil && x.DesignFrequencyHz != nil {
		return *x.DesignFrequencyHz
	}
	return 0
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) GetBacklobeSuppressionDb() float64 {
	if x != nil && x.BacklobeSuppressionDb != nil {
		return *x.BacklobeSuppressionDb
	}
	return 0
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) GetElements() []*AntennaPattern_PhasedArrayAntennaPattern_Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) GetBeamformer() isAntennaPattern_PhasedArrayAntennaPattern_Beamformer {
	if x != nil {
		return x.Beamformer
	}
	return nil
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) GetMinimumVarianceDistortionlessResponseBeamformer() *AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer {
	if x != nil {
		if x, ok := x.Beamformer.(*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer_); ok {
			return x.MinimumVarianceDistortionlessResponseBeamformer
		}
	}
	return nil
}

func (x *AntennaPattern_PhasedArrayAntennaPattern) GetCosineExponentElementFactor() *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor {
	if x != nil {
		return x.CosineExponentElementFactor
	}
	return nil
}

type isAntennaPattern_PhasedArrayAntennaPattern_Beamformer interface {
	isAntennaPattern_PhasedArrayAntennaPattern_Beamformer()
}

type AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer_ struct {
	MinimumVarianceDistortionlessResponseBeamformer *AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer `protobuf:"bytes,4,opt,name=minimum_variance_distortionless_response_beamformer,json=minimumVarianceDistortionlessResponseBeamformer,oneof"`
}

func (*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer_) isAntennaPattern_PhasedArrayAntennaPattern_Beamformer() {
}

// Applies a separate near-field antenna radiation pattern when the other
// link end is within the near field range (in meters).
type AntennaPattern_NearAndFarFieldAntennaPattern struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NearFieldPattern *AntennaPattern        `protobuf:"bytes,1,opt,name=near_field_pattern,json=nearFieldPattern" json:"near_field_pattern,omitempty"`
	FarFieldPattern  *AntennaPattern        `protobuf:"bytes,2,opt,name=far_field_pattern,json=farFieldPattern" json:"far_field_pattern,omitempty"`
	NearFieldRangeM  *float64               `protobuf:"fixed64,3,opt,name=near_field_range_m,json=nearFieldRangeM" json:"near_field_range_m,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AntennaPattern_NearAndFarFieldAntennaPattern) Reset() {
	*x = AntennaPattern_NearAndFarFieldAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_NearAndFarFieldAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_NearAndFarFieldAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_NearAndFarFieldAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_NearAndFarFieldAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_NearAndFarFieldAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 10}
}

func (x *AntennaPattern_NearAndFarFieldAntennaPattern) GetNearFieldPattern() *AntennaPattern {
	if x != nil {
		return x.NearFieldPattern
	}
	return nil
}

func (x *AntennaPattern_NearAndFarFieldAntennaPattern) GetFarFieldPattern() *AntennaPattern {
	if x != nil {
		return x.FarFieldPattern
	}
	return nil
}

func (x *AntennaPattern_NearAndFarFieldAntennaPattern) GetNearFieldRangeM() float64 {
	if x != nil && x.NearFieldRangeM != nil {
		return *x.NearFieldRangeM
	}
	return 0
}

// Applies a different antenna radiation pattern for the transmitter
// and receiver.
type AntennaPattern_TransmitterAndReceiverAntennaPattern struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TransmitterPattern *AntennaPattern        `protobuf:"bytes,1,opt,name=transmitter_pattern,json=transmitterPattern" json:"transmitter_pattern,omitempty"`
	ReceiverPattern    *AntennaPattern        `protobuf:"bytes,2,opt,name=receiver_pattern,json=receiverPattern" json:"receiver_pattern,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AntennaPattern_TransmitterAndReceiverAntennaPattern) Reset() {
	*x = AntennaPattern_TransmitterAndReceiverAntennaPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_TransmitterAndReceiverAntennaPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_TransmitterAndReceiverAntennaPattern) ProtoMessage() {}

func (x *AntennaPattern_TransmitterAndReceiverAntennaPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_TransmitterAndReceiverAntennaPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_TransmitterAndReceiverAntennaPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 11}
}

func (x *AntennaPattern_TransmitterAndReceiverAntennaPattern) GetTransmitterPattern() *AntennaPattern {
	if x != nil {
		return x.TransmitterPattern
	}
	return nil
}

func (x *AntennaPattern_TransmitterAndReceiverAntennaPattern) GetReceiverPattern() *AntennaPattern {
	if x != nil {
		return x.ReceiverPattern
	}
	return nil
}

type AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	GainDb *float64 `protobuf:"fixed64,1,opt,name=gain_db,json=gainDb" json:"gain_db,omitempty"`
	// Phi is defined as the angle, in radians, from the positive x-axis
	// to the orthogonal projection of the vector in the x-y plane. Positive
	// phi is measured from the positive x-axis towards the positive y-axis.
	// Range: [0, 2π).
	// Required.
	PhiRad *float64 `protobuf:"fixed64,2,opt,name=phi_rad,json=phiRad" json:"phi_rad,omitempty"`
	// Theta is the zenith angle, in radians, from the positive
	// z-axis to the vector. Positive theta is measured from the
	// positive z-axis towards the negative z-axis.
	// Range: [0, π].
	// Required.
	ThetaRad      *float64 `protobuf:"fixed64,3,opt,name=theta_rad,json=thetaRad" json:"theta_rad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) Reset() {
	*x = AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) ProtoMessage() {}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue.ProtoReflect.Descriptor instead.
func (*AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) GetGainDb() float64 {
	if x != nil && x.GainDb != nil {
		return *x.GainDb
	}
	return 0
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) GetPhiRad() float64 {
	if x != nil && x.PhiRad != nil {
		return *x.PhiRad
	}
	return 0
}

func (x *AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue) GetThetaRad() float64 {
	if x != nil && x.ThetaRad != nil {
		return *x.ThetaRad
	}
	return 0
}

type AntennaPattern_CustomAzElAntennaPattern_AzElGainValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A gain value (in decibels) for the angle.
	// Required.
	GainDb *float64 `protobuf:"fixed64,1,opt,name=gain_db,json=gainDb" json:"gain_db,omitempty"`
	// Azimuth is defined as the angle from the z-axis to the projection
	// of the direction vector onto the x-z plane. Positive azimuth is
	// measured from the positive z-axis towards the positive x-axis.
	// Range: [-180, 180).
	// Required.
	AzDeg *float64 `protobuf:"fixed64,2,opt,name=az_deg,json=azDeg" json:"az_deg,omitempty"`
	// *** WARNING: This definition of elevation is non-standard. ***
	// In other coordinate systems, elevation is often measured as
	// the angle above a platform's local horizon, or more generally,
	// the angle above the 0-elevation plane.
	// HOWEVER, in this message, elevation is defined as the angle from the
	// z-axis to the *projection of the direction vector onto the y-z plane*.
	// In other words, this measures the angle of the *projection of the
	// direction vector onto the y-z plane* above the 0-elevation plane.
	// Positive elevation is measured towards the *negative* y-axis.
	// Range [-180, 180).
	// Required.
	ElDeg         *float64 `protobuf:"fixed64,3,opt,name=el_deg,json=elDeg" json:"el_deg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) Reset() {
	*x = AntennaPattern_CustomAzElAntennaPattern_AzElGainValue{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) ProtoMessage() {}

func (x *AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_CustomAzElAntennaPattern_AzElGainValue.ProtoReflect.Descriptor instead.
func (*AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) GetGainDb() float64 {
	if x != nil && x.GainDb != nil {
		return *x.GainDb
	}
	return 0
}

func (x *AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) GetAzDeg() float64 {
	if x != nil && x.AzDeg != nil {
		return *x.AzDeg
	}
	return 0
}

func (x *AntennaPattern_CustomAzElAntennaPattern_AzElGainValue) GetElDeg() float64 {
	if x != nil && x.ElDeg != nil {
		return *x.ElDeg
	}
	return 0
}

type AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The phi component of the scan angle.
	// Phi is defined as the angle, in radians, from the positive x-axis
	// to the orthogonal projection of the vector in the x-y plane. Positive
	// phi is measured from the positive x-axis towards the positive y-axis.
	// Range: [-π, π).
	// Required.
	PhiRad *float32 `protobuf:"fixed32,1,opt,name=phi_rad,json=phiRad" json:"phi_rad,omitempty"`
	// The theta component of the scan angle.
	// Theta is the zenith angle, in radians, from the positive
	// z-axis to the vector. Positive theta is measured from the
	// positive z-axis towards the negative z-axis.
	// Range: [0, π].
	// Required.
	ThetaRad *float32 `protobuf:"fixed32,2,opt,name=theta_rad,json=thetaRad" json:"theta_rad,omitempty"`
	// The 3D antenna pattern for this scan angle. This pattern assigns
	// a gain value to each look angle.
	// The phi and theta in this pattern must also conform to the ranges
	// above.
	// Required.
	CustomPattern *AntennaPattern_CustomPhiThetaAntennaPattern `protobuf:"bytes,3,opt,name=custom_pattern,json=customPattern" json:"custom_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) Reset() {
	*x = AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) ProtoMessage() {}

func (x *AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern.ProtoReflect.Descriptor instead.
func (*AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) GetPhiRad() float32 {
	if x != nil && x.PhiRad != nil {
		return *x.PhiRad
	}
	return 0
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) GetThetaRad() float32 {
	if x != nil && x.ThetaRad != nil {
		return *x.ThetaRad
	}
	return 0
}

func (x *AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern) GetCustomPattern() *AntennaPattern_CustomPhiThetaAntennaPattern {
	if x != nil {
		return x.CustomPattern
	}
	return nil
}

type AntennaPattern_PhasedArrayAntennaPattern_Element struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// These fields determine the position of each element in the phased
	// array. The center of the array is considered to be at (0, 0). Since
	// this models a planar array, the z-coordinate is 0.0.
	X             *float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y             *float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_Element) Reset() {
	*x = AntennaPattern_PhasedArrayAntennaPattern_Element{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_PhasedArrayAntennaPattern_Element) ProtoMessage() {}

func (x *AntennaPattern_PhasedArrayAntennaPattern_Element) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_PhasedArrayAntennaPattern_Element.ProtoReflect.Descriptor instead.
func (*AntennaPattern_PhasedArrayAntennaPattern_Element) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 9, 0}
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_Element) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_Element) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BeamVariance  *float64               `protobuf:"fixed64,1,opt,name=beam_variance,json=beamVariance" json:"beam_variance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer) Reset() {
	*x = AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer) ProtoMessage() {
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer.ProtoReflect.Descriptor instead.
func (*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 9, 1}
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer) GetBeamVariance() float64 {
	if x != nil && x.BeamVariance != nil {
		return *x.BeamVariance
	}
	return 0
}

type AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CosineExponent *float64               `protobuf:"fixed64,1,opt,name=cosine_exponent,json=cosineExponent" json:"cosine_exponent,omitempty"`
	// The element area in meters squared.
	ElementAreaM2 *float64 `protobuf:"fixed64,2,opt,name=element_area_m2,json=elementAreaM2" json:"element_area_m2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) Reset() {
	*x = AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor{}
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) ProtoMessage() {}

func (x *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor.ProtoReflect.Descriptor instead.
func (*AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP(), []int{0, 9, 2}
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) GetCosineExponent() float64 {
	if x != nil && x.CosineExponent != nil {
		return *x.CosineExponent
	}
	return 0
}

func (x *AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor) GetElementAreaM2() float64 {
	if x != nil && x.ElementAreaM2 != nil {
		return *x.ElementAreaM2
	}
	return 0
}

var File_api_nbi_v1alpha_resources_antenna_pattern_proto protoreflect.FileDescriptor

const file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDesc = "" +
	"\n" +
	"/api/nbi/v1alpha/resources/antenna_pattern.proto\x12+aalyria.spacetime.api.nbi.v1alpha.resources\"\x89(\n" +
	"\x0eAntennaPattern\x12\x93\x01\n" +
	"\x18custom_phi_theta_pattern\x18\x01 \x01(\v2X.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPatternH\x00R\x15customPhiThetaPattern\x12\x7f\n" +
	"\x10gaussian_pattern\x18\x02 \x01(\v2R.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.GaussianAntennaPatternH\x00R\x0fgaussianPattern\x12|\n" +
	"\x0fhelical_pattern\x18\x03 \x01(\v2Q.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.HelicalAntennaPatternH\x00R\x0ehelicalPattern\x12\x82\x01\n" +
	"\x11isotropic_pattern\x18\x04 \x01(\v2S.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.IsotropicAntennaPatternH\x00R\x10isotropicPattern\x12\x82\x01\n" +
	"\x11parabolic_pattern\x18\x05 \x01(\v2S.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.ParabolicAntennaPatternH\x00R\x10parabolicPattern\x12\x86\x01\n" +
	"\x13square_horn_pattern\x18\x06 \x01(\v2T.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.SquareHornAntennaPatternH\x00R\x11squareHornPattern\x12\x95\x01\n" +
	"\x18gaussian_optical_pattern\x18\a \x01(\v2Y.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.GaussianOpticalAntennaPatternH\x00R\x16gaussianOpticalPattern\x12\x89\x01\n" +
	"\x14phased_array_pattern\x18\n" +
	" \x01(\v2U.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPatternH\x00R\x12phasedArrayPattern\x12\x97\x01\n" +
	"\x1anear_and_far_field_pattern\x18\t \x01(\v2Y.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.NearAndFarFieldAntennaPatternH\x00R\x16nearAndFarFieldPattern\x12\xab\x01\n" +
	" transmitter_and_receiver_pattern\x18\v \x01(\v2`.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.TransmitterAndReceiverAntennaPatternH\x00R\x1dtransmitterAndReceiverPattern\x12\xa2\x01\n" +
	" custom_antenna_pattern_per_angle\x18\f \x01(\v2X.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngleH\x00R\x1ccustomAntennaPatternPerAngle\x12\x87\x01\n" +
	"\x14custom_az_el_pattern\x18\r \x01(\v2T.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPatternH\x00R\x11customAzElPattern\x1a\x90\x02\n" +
	"\x1cCustomPhiThetaAntennaPattern\x12\x8a\x01\n" +
	"\n" +
	"gain_value\x18\x01 \x03(\v2k.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern.SphericalGainValueR\tgainValue\x1ac\n" +
	"\x12SphericalGainValue\x12\x17\n" +
	"\again_db\x18\x01 \x01(\x01R\x06gainDb\x12\x17\n" +
	"\aphi_rad\x18\x02 \x01(\x01R\x06phiRad\x12\x1b\n" +
	"\ttheta_rad\x18\x03 \x01(\x01R\bthetaRad\x1a\xf8\x01\n" +
	"\x18CustomAzElAntennaPattern\x12\x83\x01\n" +
	"\vgain_values\x18\x01 \x03(\v2b.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPattern.AzElGainValueR\n" +
	"gainValues\x1aV\n" +
	"\rAzElGainValue\x12\x17\n" +
	"\again_db\x18\x01 \x01(\x01R\x06gainDb\x12\x15\n" +
	"\x06az_deg\x18\x02 \x01(\x01R\x05azDeg\x12\x15\n" +
	"\x06el_deg\x18\x03 \x01(\x01R\x05elDeg\x1a\xac\x03\n" +
	"\x1cCustomAntennaPatternPerAngle\x12\xb6\x01\n" +
	"\x1escan_angle_and_custom_patterns\x18\x01 \x03(\v2r.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle.ScanAngleAndCustomPatternR\x1ascanAngleAndCustomPatterns\x1a\xd2\x01\n" +
	"\x19ScanAngleAndCustomPattern\x12\x17\n" +
	"\aphi_rad\x18\x01 \x01(\x02R\x06phiRad\x12\x1b\n" +
	"\ttheta_rad\x18\x02 \x01(\x02R\bthetaRad\x12\x7f\n" +
	"\x0ecustom_pattern\x18\x03 \x01(\v2X.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPatternR\rcustomPattern\x1a\x90\x01\n" +
	"\x16GaussianAntennaPattern\x12\x1d\n" +
	"\n" +
	"diameter_m\x18\x01 \x01(\x01R\tdiameterM\x12-\n" +
	"\x12efficiency_percent\x18\x02 \x01(\x01R\x11efficiencyPercent\x12(\n" +
	"\x10backlobe_gain_db\x18\x03 \x01(\x01R\x0ebacklobeGainDb\x1a\xdd\x01\n" +
	"\x15HelicalAntennaPattern\x12\x1d\n" +
	"\n" +
	"diameter_m\x18\x01 \x01(\x01R\tdiameterM\x12-\n" +
	"\x12efficiency_percent\x18\x02 \x01(\x01R\x11efficiencyPercent\x12(\n" +
	"\x10backlobe_gain_db\x18\x03 \x01(\x01R\x0ebacklobeGainDb\x12&\n" +
	"\x0fnumber_of_turns\x18\x04 \x01(\x01R\rnumberOfTurns\x12$\n" +
	"\x0eturn_spacing_m\x18\x05 \x01(\x01R\fturnSpacingM\x1a\x19\n" +
	"\x17IsotropicAntennaPattern\x1a\x91\x01\n" +
	"\x17ParabolicAntennaPattern\x12\x1d\n" +
	"\n" +
	"diameter_m\x18\x01 \x01(\x01R\tdiameterM\x12-\n" +
	"\x12efficiency_percent\x18\x02 \x01(\x01R\x11efficiencyPercent\x12(\n" +
	"\x10backlobe_gain_db\x18\x03 \x01(\x01R\x0ebacklobeGainDb\x1a\x92\x01\n" +
	"\x18SquareHornAntennaPattern\x12\x1d\n" +
	"\n" +
	"diameter_m\x18\x01 \x01(\x01R\tdiameterM\x12-\n" +
	"\x12efficiency_percent\x18\x02 \x01(\x01R\x11efficiencyPercent\x12(\n" +
	"\x10backlobe_gain_db\x18\x03 \x01(\x01R\x0ebacklobeGainDb\x1a\xcd\x01\n" +
	"\x1dGaussianOpticalAntennaPattern\x12\x1d\n" +
	"\n" +
	"diameter_m\x18\x01 \x01(\x01R\tdiameterM\x12-\n" +
	"\x12efficiency_percent\x18\x02 \x01(\x01R\x11efficiencyPercent\x120\n" +
	"\x14divergence_angle_rad\x18\x03 \x01(\x01R\x12divergenceAngleRad\x12,\n" +
	"\x12pointing_error_rad\x18\x04 \x01(\x01R\x10pointingErrorRad\x1a\xad\a\n" +
	"\x19PhasedArrayAntennaPattern\x12.\n" +
	"\x13design_frequency_hz\x18\x01 \x01(\x01R\x11designFrequencyHz\x126\n" +
	"\x17backlobe_suppression_db\x18\x02 \x01(\x01R\x15backlobeSuppressionDb\x12y\n" +
	"\belements\x18\x03 \x03(\v2].aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.ElementR\belements\x12\xf6\x01\n" +
	"3minimum_variance_distortionless_response_beamformer\x18\x04 \x01(\v2\x85\x01.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.MinimumVarianceDistortionlessResponseBeamformerH\x00R/minimumVarianceDistortionlessResponseBeamformer\x12\xb6\x01\n" +
	"\x1ecosine_exponent_element_factor\x18\x05 \x01(\v2q.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.CosineExponentElementFactorR\x1bcosineExponentElementFactor\x1a%\n" +
	"\aElement\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x1aV\n" +
	"/MinimumVarianceDistortionlessResponseBeamformer\x12#\n" +
	"\rbeam_variance\x18\x01 \x01(\x01R\fbeamVariance\x1an\n" +
	"\x1bCosineExponentElementFactor\x12'\n" +
	"\x0fcosine_exponent\x18\x01 \x01(\x01R\x0ecosineExponent\x12&\n" +
	"\x0felement_area_m2\x18\x02 \x01(\x01R\relementAreaM2B\f\n" +
	"\n" +
	"beamformer\x1a\xa0\x02\n" +
	"\x1dNearAndFarFieldAntennaPattern\x12i\n" +
	"\x12near_field_pattern\x18\x01 \x01(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPatternR\x10nearFieldPattern\x12g\n" +
	"\x11far_field_pattern\x18\x02 \x01(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPatternR\x0ffarFieldPattern\x12+\n" +
	"\x12near_field_range_m\x18\x03 \x01(\x01R\x0fnearFieldRangeM\x1a\xfc\x01\n" +
	"$TransmitterAndReceiverAntennaPattern\x12l\n" +
	"\x13transmitter_pattern\x18\x01 \x01(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPatternR\x12transmitterPattern\x12f\n" +
	"\x10receiver_pattern\x18\x02 \x01(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPatternR\x0freceiverPatternB\x0e\n" +
	"\fpattern_typeJ\x04\b\b\x10\tJ\b\b\x0e\x10\x80\x80\x80\x80\x02Bb\n" +
	"/com.aalyria.spacetime.api.nbi.v1alpha.resourcesZ/aalyria.com/spacetime/api/nbi/v1alpha/resources"

var (
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescOnce sync.Once
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescData []byte
)

func file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescGZIP() []byte {
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescOnce.Do(func() {
		file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDesc), len(file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDesc)))
	})
	return file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDescData
}

var file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_nbi_v1alpha_resources_antenna_pattern_proto_goTypes = []any{
	(*AntennaPattern)(nil),                                                                           // 0: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern
	(*AntennaPattern_CustomPhiThetaAntennaPattern)(nil),                                              // 1: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern
	(*AntennaPattern_CustomAzElAntennaPattern)(nil),                                                  // 2: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPattern
	(*AntennaPattern_CustomAntennaPatternPerAngle)(nil),                                              // 3: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle
	(*AntennaPattern_GaussianAntennaPattern)(nil),                                                    // 4: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.GaussianAntennaPattern
	(*AntennaPattern_HelicalAntennaPattern)(nil),                                                     // 5: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.HelicalAntennaPattern
	(*AntennaPattern_IsotropicAntennaPattern)(nil),                                                   // 6: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.IsotropicAntennaPattern
	(*AntennaPattern_ParabolicAntennaPattern)(nil),                                                   // 7: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.ParabolicAntennaPattern
	(*AntennaPattern_SquareHornAntennaPattern)(nil),                                                  // 8: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.SquareHornAntennaPattern
	(*AntennaPattern_GaussianOpticalAntennaPattern)(nil),                                             // 9: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.GaussianOpticalAntennaPattern
	(*AntennaPattern_PhasedArrayAntennaPattern)(nil),                                                 // 10: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern
	(*AntennaPattern_NearAndFarFieldAntennaPattern)(nil),                                             // 11: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.NearAndFarFieldAntennaPattern
	(*AntennaPattern_TransmitterAndReceiverAntennaPattern)(nil),                                      // 12: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.TransmitterAndReceiverAntennaPattern
	(*AntennaPattern_CustomPhiThetaAntennaPattern_SphericalGainValue)(nil),                           // 13: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern.SphericalGainValue
	(*AntennaPattern_CustomAzElAntennaPattern_AzElGainValue)(nil),                                    // 14: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPattern.AzElGainValue
	(*AntennaPattern_CustomAntennaPatternPerAngle_ScanAngleAndCustomPattern)(nil),                    // 15: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle.ScanAngleAndCustomPattern
	(*AntennaPattern_PhasedArrayAntennaPattern_Element)(nil),                                         // 16: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.Element
	(*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer)(nil), // 17: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.MinimumVarianceDistortionlessResponseBeamformer
	(*AntennaPattern_PhasedArrayAntennaPattern_CosineExponentElementFactor)(nil),                     // 18: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.CosineExponentElementFactor
}
var file_api_nbi_v1alpha_resources_antenna_pattern_proto_depIdxs = []int32{
	1,  // 0: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.custom_phi_theta_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern
	4,  // 1: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.gaussian_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.GaussianAntennaPattern
	5,  // 2: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.helical_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.HelicalAntennaPattern
	6,  // 3: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.isotropic_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.IsotropicAntennaPattern
	7,  // 4: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.parabolic_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.ParabolicAntennaPattern
	8,  // 5: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.square_horn_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.SquareHornAntennaPattern
	9,  // 6: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.gaussian_optical_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.GaussianOpticalAntennaPattern
	10, // 7: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.phased_array_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern
	11, // 8: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.near_and_far_field_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.NearAndFarFieldAntennaPattern
	12, // 9: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.transmitter_and_receiver_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.TransmitterAndReceiverAntennaPattern
	3,  // 10: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.custom_antenna_pattern_per_angle:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle
	2,  // 11: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.custom_az_el_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPattern
	13, // 12: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern.gain_value:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern.SphericalGainValue
	14, // 13: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPattern.gain_values:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAzElAntennaPattern.AzElGainValue
	15, // 14: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle.scan_angle_and_custom_patterns:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle.ScanAngleAndCustomPattern
	16, // 15: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.elements:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.Element
	17, // 16: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.minimum_variance_distortionless_response_beamformer:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.MinimumVarianceDistortionlessResponseBeamformer
	18, // 17: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.cosine_exponent_element_factor:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.PhasedArrayAntennaPattern.CosineExponentElementFactor
	0,  // 18: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.NearAndFarFieldAntennaPattern.near_field_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern
	0,  // 19: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.NearAndFarFieldAntennaPattern.far_field_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern
	0,  // 20: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.TransmitterAndReceiverAntennaPattern.transmitter_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern
	0,  // 21: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.TransmitterAndReceiverAntennaPattern.receiver_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern
	1,  // 22: aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomAntennaPatternPerAngle.ScanAngleAndCustomPattern.custom_pattern:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AntennaPattern.CustomPhiThetaAntennaPattern
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_api_nbi_v1alpha_resources_antenna_pattern_proto_init() }
func file_api_nbi_v1alpha_resources_antenna_pattern_proto_init() {
	if File_api_nbi_v1alpha_resources_antenna_pattern_proto != nil {
		return
	}
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[0].OneofWrappers = []any{
		(*AntennaPattern_CustomPhiThetaPattern)(nil),
		(*AntennaPattern_GaussianPattern)(nil),
		(*AntennaPattern_HelicalPattern)(nil),
		(*AntennaPattern_IsotropicPattern)(nil),
		(*AntennaPattern_ParabolicPattern)(nil),
		(*AntennaPattern_SquareHornPattern)(nil),
		(*AntennaPattern_GaussianOpticalPattern)(nil),
		(*AntennaPattern_PhasedArrayPattern)(nil),
		(*AntennaPattern_NearAndFarFieldPattern)(nil),
		(*AntennaPattern_TransmitterAndReceiverPattern)(nil),
		(*AntennaPattern_CustomAntennaPatternPerAngle_)(nil),
		(*AntennaPattern_CustomAzElPattern)(nil),
	}
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes[10].OneofWrappers = []any{
		(*AntennaPattern_PhasedArrayAntennaPattern_MinimumVarianceDistortionlessResponseBeamformer_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDesc), len(file_api_nbi_v1alpha_resources_antenna_pattern_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_nbi_v1alpha_resources_antenna_pattern_proto_goTypes,
		DependencyIndexes: file_api_nbi_v1alpha_resources_antenna_pattern_proto_depIdxs,
		MessageInfos:      file_api_nbi_v1alpha_resources_antenna_pattern_proto_msgTypes,
	}.Build()
	File_api_nbi_v1alpha_resources_antenna_pattern_proto = out.File
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_goTypes = nil
	file_api_nbi_v1alpha_resources_antenna_pattern_proto_depIdxs = nil
}
