// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/nbi/v1alpha/resources/coverage.proto

package resources

import (
	common "aalyria.com/spacetime/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines a grouping of transceiver models.
type TransceiverSet struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	TransceiverIds []*common.TransceiverModelId `protobuf:"bytes,1,rep,name=transceiver_ids,json=transceiverIds" json:"transceiver_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransceiverSet) Reset() {
	*x = TransceiverSet{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransceiverSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransceiverSet) ProtoMessage() {}

func (x *TransceiverSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransceiverSet.ProtoReflect.Descriptor instead.
func (*TransceiverSet) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{0}
}

func (x *TransceiverSet) GetTransceiverIds() []*common.TransceiverModelId {
	if x != nil {
		return x.TransceiverIds
	}
	return nil
}

// Defines a grouping of platforms.
type PlatformSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformIds   []string               `protobuf:"bytes,1,rep,name=platform_ids,json=platformIds" json:"platform_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformSet) Reset() {
	*x = PlatformSet{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSet) ProtoMessage() {}

func (x *PlatformSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformSet.ProtoReflect.Descriptor instead.
func (*PlatformSet) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformSet) GetPlatformIds() []string {
	if x != nil {
		return x.PlatformIds
	}
	return nil
}

// The term "station" is used in the sense of the ITU definition:
// "One or more transmitters or receivers or a combination of transmitters
// and receivers, including the accessory equipment, necessary at one
// location for carrying on a radiocommunication service, or the radio
// astronomy service."
type StationSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StationSetType:
	//
	//	*StationSet_Transceivers
	//	*StationSet_Platforms
	StationSetType isStationSet_StationSetType `protobuf_oneof:"station_set_type"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StationSet) Reset() {
	*x = StationSet{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationSet) ProtoMessage() {}

func (x *StationSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationSet.ProtoReflect.Descriptor instead.
func (*StationSet) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{2}
}

func (x *StationSet) GetStationSetType() isStationSet_StationSetType {
	if x != nil {
		return x.StationSetType
	}
	return nil
}

func (x *StationSet) GetTransceivers() *TransceiverSet {
	if x != nil {
		if x, ok := x.StationSetType.(*StationSet_Transceivers); ok {
			return x.Transceivers
		}
	}
	return nil
}

func (x *StationSet) GetPlatforms() *PlatformSet {
	if x != nil {
		if x, ok := x.StationSetType.(*StationSet_Platforms); ok {
			return x.Platforms
		}
	}
	return nil
}

type isStationSet_StationSetType interface {
	isStationSet_StationSetType()
}

type StationSet_Transceivers struct {
	// Use transceivers when the radio equipment model information is
	// relevant to the description of the stations.
	Transceivers *TransceiverSet `protobuf:"bytes,1,opt,name=transceivers,oneof"`
}

type StationSet_Platforms struct {
	// Use platforms, when only the coordinates and motion are relevant to the
	// description of the station.
	Platforms *PlatformSet `protobuf:"bytes,2,opt,name=platforms,oneof"`
}

func (*StationSet_Transceivers) isStationSet_StationSetType() {}

func (*StationSet_Platforms) isStationSet_StationSetType() {}

type StationSubset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// References a StationSet entity ID.
	StationSetId *string `protobuf:"bytes,1,opt,name=station_set_id,json=stationSetId" json:"station_set_id,omitempty"`
	// May be optionally used to filter the station set to only those that exist
	// above a surface region, which is specified by referencing a region entity
	// ID. All stations in the set are selected if this field is omitted.
	RegionId      *string `protobuf:"bytes,2,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationSubset) Reset() {
	*x = StationSubset{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationSubset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationSubset) ProtoMessage() {}

func (x *StationSubset) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationSubset.ProtoReflect.Descriptor instead.
func (*StationSubset) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{3}
}

func (x *StationSubset) GetStationSetId() string {
	if x != nil && x.StationSetId != nil {
		return *x.StationSetId
	}
	return ""
}

func (x *StationSubset) GetRegionId() string {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return ""
}

// References a set of coordinates derived from an array of transceivers,
// platforms, or spatial surface region.
type CoordinateArray struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Derivation:
	//
	//	*CoordinateArray_Surface
	//	*CoordinateArray_GeoArc
	//	*CoordinateArray_Stations
	Derivation    isCoordinateArray_Derivation `protobuf_oneof:"derivation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateArray) Reset() {
	*x = CoordinateArray{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateArray) ProtoMessage() {}

func (x *CoordinateArray) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateArray.ProtoReflect.Descriptor instead.
func (*CoordinateArray) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinateArray) GetDerivation() isCoordinateArray_Derivation {
	if x != nil {
		return x.Derivation
	}
	return nil
}

func (x *CoordinateArray) GetSurface() *S2CoverageGrid {
	if x != nil {
		if x, ok := x.Derivation.(*CoordinateArray_Surface); ok {
			return x.Surface
		}
	}
	return nil
}

func (x *CoordinateArray) GetGeoArc() *GeostationaryArc {
	if x != nil {
		if x, ok := x.Derivation.(*CoordinateArray_GeoArc); ok {
			return x.GeoArc
		}
	}
	return nil
}

func (x *CoordinateArray) GetStations() *StationSubset {
	if x != nil {
		if x, ok := x.Derivation.(*CoordinateArray_Stations); ok {
			return x.Stations
		}
	}
	return nil
}

type isCoordinateArray_Derivation interface {
	isCoordinateArray_Derivation()
}

type CoordinateArray_Surface struct {
	Surface *S2CoverageGrid `protobuf:"bytes,1,opt,name=surface,oneof"`
}

type CoordinateArray_GeoArc struct {
	GeoArc *GeostationaryArc `protobuf:"bytes,2,opt,name=geo_arc,json=geoArc,oneof"`
}

type CoordinateArray_Stations struct {
	Stations *StationSubset `protobuf:"bytes,3,opt,name=stations,oneof"`
}

func (*CoordinateArray_Surface) isCoordinateArray_Derivation() {}

func (*CoordinateArray_GeoArc) isCoordinateArray_Derivation() {}

func (*CoordinateArray_Stations) isCoordinateArray_Derivation() {}

// The signal power over a coordinate grid.
type SignalPowerCoverage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*SignalPowerCoverage_Surface
	//	*SignalPowerCoverage_GeoArc
	//	*SignalPowerCoverage_Constellation
	Type          isSignalPowerCoverage_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalPowerCoverage) Reset() {
	*x = SignalPowerCoverage{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalPowerCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalPowerCoverage) ProtoMessage() {}

func (x *SignalPowerCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalPowerCoverage.ProtoReflect.Descriptor instead.
func (*SignalPowerCoverage) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{5}
}

func (x *SignalPowerCoverage) GetType() isSignalPowerCoverage_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *SignalPowerCoverage) GetSurface() *SurfacePfdRegions {
	if x != nil {
		if x, ok := x.Type.(*SignalPowerCoverage_Surface); ok {
			return x.Surface
		}
	}
	return nil
}

func (x *SignalPowerCoverage) GetGeoArc() *GeostationaryArcPfd {
	if x != nil {
		if x, ok := x.Type.(*SignalPowerCoverage_GeoArc); ok {
			return x.GeoArc
		}
	}
	return nil
}

func (x *SignalPowerCoverage) GetConstellation() *PfdOverConstellation {
	if x != nil {
		if x, ok := x.Type.(*SignalPowerCoverage_Constellation); ok {
			return x.Constellation
		}
	}
	return nil
}

type isSignalPowerCoverage_Type interface {
	isSignalPowerCoverage_Type()
}

type SignalPowerCoverage_Surface struct {
	Surface *SurfacePfdRegions `protobuf:"bytes,1,opt,name=surface,oneof"`
}

type SignalPowerCoverage_GeoArc struct {
	GeoArc *GeostationaryArcPfd `protobuf:"bytes,2,opt,name=geo_arc,json=geoArc,oneof"`
}

type SignalPowerCoverage_Constellation struct {
	Constellation *PfdOverConstellation `protobuf:"bytes,3,opt,name=constellation,oneof"`
}

func (*SignalPowerCoverage_Surface) isSignalPowerCoverage_Type() {}

func (*SignalPowerCoverage_GeoArc) isSignalPowerCoverage_Type() {}

func (*SignalPowerCoverage_Constellation) isSignalPowerCoverage_Type() {}

// Defines a GeoJSON formatted geographic region.
type GeoJsonRegion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This provides a human-readable name for the region.
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Geobuf encoded geoJSON region (see https://github.com/mapbox/geobuf).
	EncodedGeoBuffer [][]byte `protobuf:"bytes,2,rep,name=encoded_geo_buffer,json=encodedGeoBuffer" json:"encoded_geo_buffer,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GeoJsonRegion) Reset() {
	*x = GeoJsonRegion{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoJsonRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoJsonRegion) ProtoMessage() {}

func (x *GeoJsonRegion) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoJsonRegion.ProtoReflect.Descriptor instead.
func (*GeoJsonRegion) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{6}
}

func (x *GeoJsonRegion) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GeoJsonRegion) GetEncodedGeoBuffer() [][]byte {
	if x != nil {
		return x.EncodedGeoBuffer
	}
	return nil
}

// Defines a set of S2 cells (that can be at different levels) that togeher
// cover some region.  This can be used to represent the boundaries of a nation,
// as one example.
type SurfaceRegion struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	S2CellIds []int64                `protobuf:"varint,1,rep,name=s2_cell_ids,json=s2CellIds" json:"s2_cell_ids,omitempty"`
	// This provides a human-readable name for the region.
	Name          *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurfaceRegion) Reset() {
	*x = SurfaceRegion{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurfaceRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurfaceRegion) ProtoMessage() {}

func (x *SurfaceRegion) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurfaceRegion.ProtoReflect.Descriptor instead.
func (*SurfaceRegion) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{7}
}

func (x *SurfaceRegion) GetS2CellIds() []int64 {
	if x != nil {
		return x.S2CellIds
	}
	return nil
}

func (x *SurfaceRegion) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// Defines a set of s2 cells and an analysis level over a region.  Calculations
// use WGS84 ellipsoid, altitude is assumed to be zero and terrain is not
// factored into the coverage calculation. See http://s2geometry.io/ for
// background information.
type S2CoverageGrid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A region on Earth's surface. Defined by an outer covering of S2 cells at
	// various levels. See http://s2geometry.io/devguide/examples/coverings.
	//
	// Types that are valid to be assigned to RegionDescription:
	//
	//	*S2CoverageGrid_Region
	//	*S2CoverageGrid_RegionId
	RegionDescription isS2CoverageGrid_RegionDescription `protobuf_oneof:"region_description"`
	// The desired s2 cell resolution for coverage analysis over this region.
	// See levels at http://s2geometry.io/resources/s2cell_statistics.  If an
	// s2_level is provided that does not match the level of a provided cell id,
	// the parents or children of the provided cell will be found that match the
	// desired s2 _level.
	S2Level       *uint32 `protobuf:"varint,2,opt,name=s2_level,json=s2Level,def=6" json:"s2_level,omitempty"` // range: [0..30]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for S2CoverageGrid fields.
const (
	Default_S2CoverageGrid_S2Level = uint32(6)
)

func (x *S2CoverageGrid) Reset() {
	*x = S2CoverageGrid{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CoverageGrid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CoverageGrid) ProtoMessage() {}

func (x *S2CoverageGrid) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CoverageGrid.ProtoReflect.Descriptor instead.
func (*S2CoverageGrid) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{8}
}

func (x *S2CoverageGrid) GetRegionDescription() isS2CoverageGrid_RegionDescription {
	if x != nil {
		return x.RegionDescription
	}
	return nil
}

func (x *S2CoverageGrid) GetRegion() *common.S2Cells {
	if x != nil {
		if x, ok := x.RegionDescription.(*S2CoverageGrid_Region); ok {
			return x.Region
		}
	}
	return nil
}

func (x *S2CoverageGrid) GetRegionId() string {
	if x != nil {
		if x, ok := x.RegionDescription.(*S2CoverageGrid_RegionId); ok {
			return x.RegionId
		}
	}
	return ""
}

func (x *S2CoverageGrid) GetS2Level() uint32 {
	if x != nil && x.S2Level != nil {
		return *x.S2Level
	}
	return Default_S2CoverageGrid_S2Level
}

type isS2CoverageGrid_RegionDescription interface {
	isS2CoverageGrid_RegionDescription()
}

type S2CoverageGrid_Region struct {
	// An explicit list of cell IDs.
	Region *common.S2Cells `protobuf:"bytes,1,opt,name=region,oneof"`
}

type S2CoverageGrid_RegionId struct {
	// The entity key for a SurfaceRegion object in the store.
	RegionId string `protobuf:"bytes,3,opt,name=region_id,json=regionId,oneof"`
}

func (*S2CoverageGrid_Region) isS2CoverageGrid_RegionDescription() {}

func (*S2CoverageGrid_RegionId) isS2CoverageGrid_RegionDescription() {}

// Power flux density over a region.  Terrain is not utilized for these results.
// WGS84 ellipsoid is used and altitude is assumed to be zero.
type PfdOverS2Region struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A region on Earth's surface. Defined by an outer covering of S2 cells at
	// various levels. See http://s2geometry.io/devguide/examples/coverings.
	Region *common.S2Cells `protobuf:"bytes,1,opt,name=region" json:"region,omitempty"`
	// The received power flux density over the region, in dB(W/m2).
	ReceivedPowerFluxDensityDbWPerM2 *float64 `protobuf:"fixed64,2,opt,name=received_power_flux_density_db_w_per_m2,json=receivedPowerFluxDensityDbWPerM2" json:"received_power_flux_density_db_w_per_m2,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PfdOverS2Region) Reset() {
	*x = PfdOverS2Region{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfdOverS2Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfdOverS2Region) ProtoMessage() {}

func (x *PfdOverS2Region) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfdOverS2Region.ProtoReflect.Descriptor instead.
func (*PfdOverS2Region) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{9}
}

func (x *PfdOverS2Region) GetRegion() *common.S2Cells {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *PfdOverS2Region) GetReceivedPowerFluxDensityDbWPerM2() float64 {
	if x != nil && x.ReceivedPowerFluxDensityDbWPerM2 != nil {
		return *x.ReceivedPowerFluxDensityDbWPerM2
	}
	return 0
}

// The power flux density over one or more regions.
type SurfacePfdRegions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PfdRegion     []*PfdOverS2Region     `protobuf:"bytes,1,rep,name=pfd_region,json=pfdRegion" json:"pfd_region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurfacePfdRegions) Reset() {
	*x = SurfacePfdRegions{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurfacePfdRegions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurfacePfdRegions) ProtoMessage() {}

func (x *SurfacePfdRegions) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurfacePfdRegions.ProtoReflect.Descriptor instead.
func (*SurfacePfdRegions) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{10}
}

func (x *SurfacePfdRegions) GetPfdRegion() []*PfdOverS2Region {
	if x != nil {
		return x.PfdRegion
	}
	return nil
}

// A grid on the circular arc of geostationary orbit, approximately 35,786 km
// above Earth's surface.
type GeostationaryArc struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The absolute value of the minimum and maximum latitude, in degrees, above
	// and below the geostationary arc. If this field is omitted, grid points are
	// assigned directly to the geostationary arc at the specified resolution.
	LatitudeBoundDeg *float64 `protobuf:"fixed64,1,opt,name=latitude_bound_deg,json=latitudeBoundDeg" json:"latitude_bound_deg,omitempty"`
	// The maximum angular spacing between grid points, in degrees.
	ResolutionDeg *float64 `protobuf:"fixed64,2,opt,name=resolution_deg,json=resolutionDeg" json:"resolution_deg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeostationaryArc) Reset() {
	*x = GeostationaryArc{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeostationaryArc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeostationaryArc) ProtoMessage() {}

func (x *GeostationaryArc) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeostationaryArc.ProtoReflect.Descriptor instead.
func (*GeostationaryArc) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{11}
}

func (x *GeostationaryArc) GetLatitudeBoundDeg() float64 {
	if x != nil && x.LatitudeBoundDeg != nil {
		return *x.LatitudeBoundDeg
	}
	return 0
}

func (x *GeostationaryArc) GetResolutionDeg() float64 {
	if x != nil && x.ResolutionDeg != nil {
		return *x.ResolutionDeg
	}
	return 0
}

// The power flux density over some grid cell in geostationary orbit.  Altitude
// is assumed to be 35,786 km.
type PfdOverGeoArcCell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The longitude on the geostationary arc, in degrees.
	LongitudeDeg *float64 `protobuf:"fixed64,1,opt,name=longitude_deg,json=longitudeDeg" json:"longitude_deg,omitempty"`
	// The latitude on the geostationary arc, in degrees.
	LatitudeDeg *float64 `protobuf:"fixed64,2,opt,name=latitude_deg,json=latitudeDeg" json:"latitude_deg,omitempty"`
	// The received power flux density over this cell, in dB(W/m2).
	ReceivedPowerFluxDensityDbWPerM2 *float64 `protobuf:"fixed64,3,opt,name=received_power_flux_density_db_w_per_m2,json=receivedPowerFluxDensityDbWPerM2" json:"received_power_flux_density_db_w_per_m2,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PfdOverGeoArcCell) Reset() {
	*x = PfdOverGeoArcCell{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfdOverGeoArcCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfdOverGeoArcCell) ProtoMessage() {}

func (x *PfdOverGeoArcCell) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfdOverGeoArcCell.ProtoReflect.Descriptor instead.
func (*PfdOverGeoArcCell) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{12}
}

func (x *PfdOverGeoArcCell) GetLongitudeDeg() float64 {
	if x != nil && x.LongitudeDeg != nil {
		return *x.LongitudeDeg
	}
	return 0
}

func (x *PfdOverGeoArcCell) GetLatitudeDeg() float64 {
	if x != nil && x.LatitudeDeg != nil {
		return *x.LatitudeDeg
	}
	return 0
}

func (x *PfdOverGeoArcCell) GetReceivedPowerFluxDensityDbWPerM2() float64 {
	if x != nil && x.ReceivedPowerFluxDensityDbWPerM2 != nil {
		return *x.ReceivedPowerFluxDensityDbWPerM2
	}
	return 0
}

// The power flux density over a set of cells in the geostationary arc.
type GeostationaryArcPfd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          []*PfdOverGeoArcCell   `protobuf:"bytes,1,rep,name=cell" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeostationaryArcPfd) Reset() {
	*x = GeostationaryArcPfd{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeostationaryArcPfd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeostationaryArcPfd) ProtoMessage() {}

func (x *GeostationaryArcPfd) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeostationaryArcPfd.ProtoReflect.Descriptor instead.
func (*GeostationaryArcPfd) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{13}
}

func (x *GeostationaryArcPfd) GetCell() []*PfdOverGeoArcCell {
	if x != nil {
		return x.Cell
	}
	return nil
}

// The power flux density at an antenna.
type PfdAtAntenna struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	TransceiverModelId *common.TransceiverModelId `protobuf:"bytes,3,opt,name=transceiver_model_id,json=transceiverModelId" json:"transceiver_model_id,omitempty"`
	// The received power flux density at the antenna's location, in dB(W/m2).
	ReceivedPowerFluxDensityDbWPerM2 *float64 `protobuf:"fixed64,2,opt,name=received_power_flux_density_db_w_per_m2,json=receivedPowerFluxDensityDbWPerM2" json:"received_power_flux_density_db_w_per_m2,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PfdAtAntenna) Reset() {
	*x = PfdAtAntenna{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfdAtAntenna) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfdAtAntenna) ProtoMessage() {}

func (x *PfdAtAntenna) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfdAtAntenna.ProtoReflect.Descriptor instead.
func (*PfdAtAntenna) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{14}
}

func (x *PfdAtAntenna) GetTransceiverModelId() *common.TransceiverModelId {
	if x != nil {
		return x.TransceiverModelId
	}
	return nil
}

func (x *PfdAtAntenna) GetReceivedPowerFluxDensityDbWPerM2() float64 {
	if x != nil && x.ReceivedPowerFluxDensityDbWPerM2 != nil {
		return *x.ReceivedPowerFluxDensityDbWPerM2
	}
	return 0
}

// The power flux density observed by a constellation of antennas.
type PfdOverConstellation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Victim        []*PfdAtAntenna        `protobuf:"bytes,1,rep,name=victim" json:"victim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PfdOverConstellation) Reset() {
	*x = PfdOverConstellation{}
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PfdOverConstellation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PfdOverConstellation) ProtoMessage() {}

func (x *PfdOverConstellation) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PfdOverConstellation.ProtoReflect.Descriptor instead.
func (*PfdOverConstellation) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP(), []int{15}
}

func (x *PfdOverConstellation) GetVictim() []*PfdAtAntenna {
	if x != nil {
		return x.Victim
	}
	return nil
}

var File_api_nbi_v1alpha_resources_coverage_proto protoreflect.FileDescriptor

const file_api_nbi_v1alpha_resources_coverage_proto_rawDesc = "" +
	"\n" +
	"(api/nbi/v1alpha/resources/coverage.proto\x12+aalyria.spacetime.api.nbi.v1alpha.resources\x1a\x1capi/common/coordinates.proto\x1a%api/common/wireless_transceiver.proto\"k\n" +
	"\x0eTransceiverSet\x12Y\n" +
	"\x0ftransceiver_ids\x18\x01 \x03(\v20.aalyria.spacetime.api.common.TransceiverModelIdR\x0etransceiverIds\"0\n" +
	"\vPlatformSet\x12!\n" +
	"\fplatform_ids\x18\x01 \x03(\tR\vplatformIds\"\xdd\x01\n" +
	"\n" +
	"StationSet\x12a\n" +
	"\ftransceivers\x18\x01 \x01(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverSetH\x00R\ftransceivers\x12X\n" +
	"\tplatforms\x18\x02 \x01(\v28.aalyria.spacetime.api.nbi.v1alpha.resources.PlatformSetH\x00R\tplatformsB\x12\n" +
	"\x10station_set_type\"R\n" +
	"\rStationSubset\x12$\n" +
	"\x0estation_set_id\x18\x01 \x01(\tR\fstationSetId\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\tR\bregionId\"\xac\x02\n" +
	"\x0fCoordinateArray\x12W\n" +
	"\asurface\x18\x01 \x01(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.S2CoverageGridH\x00R\asurface\x12X\n" +
	"\ageo_arc\x18\x02 \x01(\v2=.aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArcH\x00R\x06geoArc\x12X\n" +
	"\bstations\x18\x03 \x01(\v2:.aalyria.spacetime.api.nbi.v1alpha.resources.StationSubsetH\x00R\bstationsB\f\n" +
	"\n" +
	"derivation\"\xc1\x02\n" +
	"\x13SignalPowerCoverage\x12Z\n" +
	"\asurface\x18\x01 \x01(\v2>.aalyria.spacetime.api.nbi.v1alpha.resources.SurfacePfdRegionsH\x00R\asurface\x12[\n" +
	"\ageo_arc\x18\x02 \x01(\v2@.aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArcPfdH\x00R\x06geoArc\x12i\n" +
	"\rconstellation\x18\x03 \x01(\v2A.aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverConstellationH\x00R\rconstellationB\x06\n" +
	"\x04type\"Q\n" +
	"\rGeoJsonRegion\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12encoded_geo_buffer\x18\x02 \x03(\fR\x10encodedGeoBuffer\"C\n" +
	"\rSurfaceRegion\x12\x1e\n" +
	"\vs2_cell_ids\x18\x01 \x03(\x03R\ts2CellIds\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xa4\x01\n" +
	"\x0eS2CoverageGrid\x12?\n" +
	"\x06region\x18\x01 \x01(\v2%.aalyria.spacetime.api.common.S2CellsH\x00R\x06region\x12\x1d\n" +
	"\tregion_id\x18\x03 \x01(\tH\x00R\bregionId\x12\x1c\n" +
	"\bs2_level\x18\x02 \x01(\r:\x016R\as2LevelB\x14\n" +
	"\x12region_description\"\xa3\x01\n" +
	"\x0fPfdOverS2Region\x12=\n" +
	"\x06region\x18\x01 \x01(\v2%.aalyria.spacetime.api.common.S2CellsR\x06region\x12Q\n" +
	"'received_power_flux_density_db_w_per_m2\x18\x02 \x01(\x01R receivedPowerFluxDensityDbWPerM2\"p\n" +
	"\x11SurfacePfdRegions\x12[\n" +
	"\n" +
	"pfd_region\x18\x01 \x03(\v2<.aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverS2RegionR\tpfdRegion\"g\n" +
	"\x10GeostationaryArc\x12,\n" +
	"\x12latitude_bound_deg\x18\x01 \x01(\x01R\x10latitudeBoundDeg\x12%\n" +
	"\x0eresolution_deg\x18\x02 \x01(\x01R\rresolutionDeg\"\xae\x01\n" +
	"\x11PfdOverGeoArcCell\x12#\n" +
	"\rlongitude_deg\x18\x01 \x01(\x01R\flongitudeDeg\x12!\n" +
	"\flatitude_deg\x18\x02 \x01(\x01R\vlatitudeDeg\x12Q\n" +
	"'received_power_flux_density_db_w_per_m2\x18\x03 \x01(\x01R receivedPowerFluxDensityDbWPerM2\"i\n" +
	"\x13GeostationaryArcPfd\x12R\n" +
	"\x04cell\x18\x01 \x03(\v2>.aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverGeoArcCellR\x04cell\"\xcb\x01\n" +
	"\fPfdAtAntenna\x12b\n" +
	"\x14transceiver_model_id\x18\x03 \x01(\v20.aalyria.spacetime.api.common.TransceiverModelIdR\x12transceiverModelId\x12Q\n" +
	"'received_power_flux_density_db_w_per_m2\x18\x02 \x01(\x01R receivedPowerFluxDensityDbWPerM2J\x04\b\x01\x10\x02\"i\n" +
	"\x14PfdOverConstellation\x12Q\n" +
	"\x06victim\x18\x01 \x03(\v29.aalyria.spacetime.api.nbi.v1alpha.resources.PfdAtAntennaR\x06victimBb\n" +
	"/com.aalyria.spacetime.api.nbi.v1alpha.resourcesZ/aalyria.com/spacetime/api/nbi/v1alpha/resources"

var (
	file_api_nbi_v1alpha_resources_coverage_proto_rawDescOnce sync.Once
	file_api_nbi_v1alpha_resources_coverage_proto_rawDescData []byte
)

func file_api_nbi_v1alpha_resources_coverage_proto_rawDescGZIP() []byte {
	file_api_nbi_v1alpha_resources_coverage_proto_rawDescOnce.Do(func() {
		file_api_nbi_v1alpha_resources_coverage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_resources_coverage_proto_rawDesc), len(file_api_nbi_v1alpha_resources_coverage_proto_rawDesc)))
	})
	return file_api_nbi_v1alpha_resources_coverage_proto_rawDescData
}

var file_api_nbi_v1alpha_resources_coverage_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_nbi_v1alpha_resources_coverage_proto_goTypes = []any{
	(*TransceiverSet)(nil),            // 0: aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverSet
	(*PlatformSet)(nil),               // 1: aalyria.spacetime.api.nbi.v1alpha.resources.PlatformSet
	(*StationSet)(nil),                // 2: aalyria.spacetime.api.nbi.v1alpha.resources.StationSet
	(*StationSubset)(nil),             // 3: aalyria.spacetime.api.nbi.v1alpha.resources.StationSubset
	(*CoordinateArray)(nil),           // 4: aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArray
	(*SignalPowerCoverage)(nil),       // 5: aalyria.spacetime.api.nbi.v1alpha.resources.SignalPowerCoverage
	(*GeoJsonRegion)(nil),             // 6: aalyria.spacetime.api.nbi.v1alpha.resources.GeoJsonRegion
	(*SurfaceRegion)(nil),             // 7: aalyria.spacetime.api.nbi.v1alpha.resources.SurfaceRegion
	(*S2CoverageGrid)(nil),            // 8: aalyria.spacetime.api.nbi.v1alpha.resources.S2CoverageGrid
	(*PfdOverS2Region)(nil),           // 9: aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverS2Region
	(*SurfacePfdRegions)(nil),         // 10: aalyria.spacetime.api.nbi.v1alpha.resources.SurfacePfdRegions
	(*GeostationaryArc)(nil),          // 11: aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArc
	(*PfdOverGeoArcCell)(nil),         // 12: aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverGeoArcCell
	(*GeostationaryArcPfd)(nil),       // 13: aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArcPfd
	(*PfdAtAntenna)(nil),              // 14: aalyria.spacetime.api.nbi.v1alpha.resources.PfdAtAntenna
	(*PfdOverConstellation)(nil),      // 15: aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverConstellation
	(*common.TransceiverModelId)(nil), // 16: aalyria.spacetime.api.common.TransceiverModelId
	(*common.S2Cells)(nil),            // 17: aalyria.spacetime.api.common.S2Cells
}
var file_api_nbi_v1alpha_resources_coverage_proto_depIdxs = []int32{
	16, // 0: aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverSet.transceiver_ids:type_name -> aalyria.spacetime.api.common.TransceiverModelId
	0,  // 1: aalyria.spacetime.api.nbi.v1alpha.resources.StationSet.transceivers:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverSet
	1,  // 2: aalyria.spacetime.api.nbi.v1alpha.resources.StationSet.platforms:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.PlatformSet
	8,  // 3: aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArray.surface:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.S2CoverageGrid
	11, // 4: aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArray.geo_arc:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArc
	3,  // 5: aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArray.stations:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.StationSubset
	10, // 6: aalyria.spacetime.api.nbi.v1alpha.resources.SignalPowerCoverage.surface:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.SurfacePfdRegions
	13, // 7: aalyria.spacetime.api.nbi.v1alpha.resources.SignalPowerCoverage.geo_arc:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArcPfd
	15, // 8: aalyria.spacetime.api.nbi.v1alpha.resources.SignalPowerCoverage.constellation:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverConstellation
	17, // 9: aalyria.spacetime.api.nbi.v1alpha.resources.S2CoverageGrid.region:type_name -> aalyria.spacetime.api.common.S2Cells
	17, // 10: aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverS2Region.region:type_name -> aalyria.spacetime.api.common.S2Cells
	9,  // 11: aalyria.spacetime.api.nbi.v1alpha.resources.SurfacePfdRegions.pfd_region:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverS2Region
	12, // 12: aalyria.spacetime.api.nbi.v1alpha.resources.GeostationaryArcPfd.cell:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverGeoArcCell
	16, // 13: aalyria.spacetime.api.nbi.v1alpha.resources.PfdAtAntenna.transceiver_model_id:type_name -> aalyria.spacetime.api.common.TransceiverModelId
	14, // 14: aalyria.spacetime.api.nbi.v1alpha.resources.PfdOverConstellation.victim:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.PfdAtAntenna
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_nbi_v1alpha_resources_coverage_proto_init() }
func file_api_nbi_v1alpha_resources_coverage_proto_init() {
	if File_api_nbi_v1alpha_resources_coverage_proto != nil {
		return
	}
	file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[2].OneofWrappers = []any{
		(*StationSet_Transceivers)(nil),
		(*StationSet_Platforms)(nil),
	}
	file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[4].OneofWrappers = []any{
		(*CoordinateArray_Surface)(nil),
		(*CoordinateArray_GeoArc)(nil),
		(*CoordinateArray_Stations)(nil),
	}
	file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[5].OneofWrappers = []any{
		(*SignalPowerCoverage_Surface)(nil),
		(*SignalPowerCoverage_GeoArc)(nil),
		(*SignalPowerCoverage_Constellation)(nil),
	}
	file_api_nbi_v1alpha_resources_coverage_proto_msgTypes[8].OneofWrappers = []any{
		(*S2CoverageGrid_Region)(nil),
		(*S2CoverageGrid_RegionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_resources_coverage_proto_rawDesc), len(file_api_nbi_v1alpha_resources_coverage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_nbi_v1alpha_resources_coverage_proto_goTypes,
		DependencyIndexes: file_api_nbi_v1alpha_resources_coverage_proto_depIdxs,
		MessageInfos:      file_api_nbi_v1alpha_resources_coverage_proto_msgTypes,
	}.Build()
	File_api_nbi_v1alpha_resources_coverage_proto = out.File
	file_api_nbi_v1alpha_resources_coverage_proto_goTypes = nil
	file_api_nbi_v1alpha_resources_coverage_proto_depIdxs = nil
}
