// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// An Intent describes an application's request to the Spacetime core to alter
// the network's behavior.  It specifies policy rather than mechanism.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/nbi/v1alpha/resources/intent.proto

package resources

import (
	common "aalyria.com/spacetime/api/common"
	code "google.golang.org/genproto/googleapis/rpc/code"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Intent states are based on the ONOS intent framework,
// see https://goo.gl/aO4ivn, but with more granularity.
type IntentState int32

const (
	IntentState_UNKNOWN      IntentState = 0
	IntentState_INSTALL_REQ  IntentState = 1
	IntentState_SCHEDULED    IntentState = 10
	IntentState_SCHEDULING   IntentState = 12
	IntentState_INSTALLING   IntentState = 3 // In process of being deprecated.
	IntentState_INSTALLED    IntentState = 4
	IntentState_WITHDRAW_REQ IntentState = 5
	// TODO: Subdivide WITHDRAWING state as was done for the
	// INSTALLING state.
	IntentState_WITHDRAWING IntentState = 6
	IntentState_FAILED      IntentState = 8
)

// Enum value maps for IntentState.
var (
	IntentState_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "INSTALL_REQ",
		10: "SCHEDULED",
		12: "SCHEDULING",
		3:  "INSTALLING",
		4:  "INSTALLED",
		5:  "WITHDRAW_REQ",
		6:  "WITHDRAWING",
		8:  "FAILED",
	}
	IntentState_value = map[string]int32{
		"UNKNOWN":      0,
		"INSTALL_REQ":  1,
		"SCHEDULED":    10,
		"SCHEDULING":   12,
		"INSTALLING":   3,
		"INSTALLED":    4,
		"WITHDRAW_REQ": 5,
		"WITHDRAWING":  6,
		"FAILED":       8,
	}
)

func (x IntentState) Enum() *IntentState {
	p := new(IntentState)
	*p = x
	return p
}

func (x IntentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_nbi_v1alpha_resources_intent_proto_enumTypes[0].Descriptor()
}

func (IntentState) Type() protoreflect.EnumType {
	return &file_api_nbi_v1alpha_resources_intent_proto_enumTypes[0]
}

func (x IntentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IntentState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IntentState(num)
	return nil
}

// Deprecated: Use IntentState.Descriptor instead.
func (IntentState) EnumDescriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{0}
}

type Polarization int32

const (
	Polarization_POLARIZATION_UNSPECIFIED Polarization = 0
	Polarization_POLARIZATION_LHCP        Polarization = 1 // Left-handed circular polarization
	Polarization_POLARIZATION_RHCP        Polarization = 2 // Right-handed circular polarization
)

// Enum value maps for Polarization.
var (
	Polarization_name = map[int32]string{
		0: "POLARIZATION_UNSPECIFIED",
		1: "POLARIZATION_LHCP",
		2: "POLARIZATION_RHCP",
	}
	Polarization_value = map[string]int32{
		"POLARIZATION_UNSPECIFIED": 0,
		"POLARIZATION_LHCP":        1,
		"POLARIZATION_RHCP":        2,
	}
)

func (x Polarization) Enum() *Polarization {
	p := new(Polarization)
	*p = x
	return p
}

func (x Polarization) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Polarization) Descriptor() protoreflect.EnumDescriptor {
	return file_api_nbi_v1alpha_resources_intent_proto_enumTypes[1].Descriptor()
}

func (Polarization) Type() protoreflect.EnumType {
	return &file_api_nbi_v1alpha_resources_intent_proto_enumTypes[1]
}

func (x Polarization) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Polarization) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Polarization(num)
	return nil
}

// Deprecated: Use Polarization.Descriptor instead.
func (Polarization) EnumDescriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{1}
}

type IntentFailure_IntentFailureType int32

const (
	IntentFailure_UNKNOWN                    IntentFailure_IntentFailureType = 0
	IntentFailure_COMPILATION_FAILURE        IntentFailure_IntentFailureType = 1
	IntentFailure_AGENT_INSTALLATION_FAILURE IntentFailure_IntentFailureType = 2
	IntentFailure_UNREACHABLE_AGENT          IntentFailure_IntentFailureType = 3
	// An intent in the INSTALLING or INSTALLED state failed because of a CDPI
	// report with unexpected state (e.g. due to loss of antenna tracking, bug
	// in the agent, etc). An intent in the INSTALLING state can also report
	// this failure if another intent concurrently modified control plane state
	// after compiled updates have been acked by agents, but before the compiler
	// had a chance to observe the desired control plane state.
	IntentFailure_UNEXPECTED_CDPI_STATE_CHANGE IntentFailure_IntentFailureType = 4
	IntentFailure_PRECONDITION_FAILED          IntentFailure_IntentFailureType = 5
	IntentFailure_DEADLINE_EXCEEDED            IntentFailure_IntentFailureType = 6
	// The precondition is in WITHDRAW_REQ, WITHDRAWING or WITHDRAWN state.
	IntentFailure_PRECONDITION_EXPIRED IntentFailure_IntentFailureType = 7
	IntentFailure_SDN_INTERNAL_ERROR   IntentFailure_IntentFailureType = 9
)

// Enum value maps for IntentFailure_IntentFailureType.
var (
	IntentFailure_IntentFailureType_name = map[int32]string{
		0: "UNKNOWN",
		1: "COMPILATION_FAILURE",
		2: "AGENT_INSTALLATION_FAILURE",
		3: "UNREACHABLE_AGENT",
		4: "UNEXPECTED_CDPI_STATE_CHANGE",
		5: "PRECONDITION_FAILED",
		6: "DEADLINE_EXCEEDED",
		7: "PRECONDITION_EXPIRED",
		9: "SDN_INTERNAL_ERROR",
	}
	IntentFailure_IntentFailureType_value = map[string]int32{
		"UNKNOWN":                      0,
		"COMPILATION_FAILURE":          1,
		"AGENT_INSTALLATION_FAILURE":   2,
		"UNREACHABLE_AGENT":            3,
		"UNEXPECTED_CDPI_STATE_CHANGE": 4,
		"PRECONDITION_FAILED":          5,
		"DEADLINE_EXCEEDED":            6,
		"PRECONDITION_EXPIRED":         7,
		"SDN_INTERNAL_ERROR":           9,
	}
)

func (x IntentFailure_IntentFailureType) Enum() *IntentFailure_IntentFailureType {
	p := new(IntentFailure_IntentFailureType)
	*p = x
	return p
}

func (x IntentFailure_IntentFailureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentFailure_IntentFailureType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_nbi_v1alpha_resources_intent_proto_enumTypes[2].Descriptor()
}

func (IntentFailure_IntentFailureType) Type() protoreflect.EnumType {
	return &file_api_nbi_v1alpha_resources_intent_proto_enumTypes[2]
}

func (x IntentFailure_IntentFailureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IntentFailure_IntentFailureType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IntentFailure_IntentFailureType(num)
	return nil
}

// Deprecated: Use IntentFailure_IntentFailureType.Descriptor instead.
func (IntentFailure_IntentFailureType) EnumDescriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{9, 0}
}

type IntentWithdrawal_WithdrawType int32

const (
	IntentWithdrawal_UNKNOWN      IntentWithdrawal_WithdrawType = 0
	IntentWithdrawal_INACCESSIBLE IntentWithdrawal_WithdrawType = 1
	IntentWithdrawal_NOT_REQUIRED IntentWithdrawal_WithdrawType = 2
)

// Enum value maps for IntentWithdrawal_WithdrawType.
var (
	IntentWithdrawal_WithdrawType_name = map[int32]string{
		0: "UNKNOWN",
		1: "INACCESSIBLE",
		2: "NOT_REQUIRED",
	}
	IntentWithdrawal_WithdrawType_value = map[string]int32{
		"UNKNOWN":      0,
		"INACCESSIBLE": 1,
		"NOT_REQUIRED": 2,
	}
)

func (x IntentWithdrawal_WithdrawType) Enum() *IntentWithdrawal_WithdrawType {
	p := new(IntentWithdrawal_WithdrawType)
	*p = x
	return p
}

func (x IntentWithdrawal_WithdrawType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntentWithdrawal_WithdrawType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_nbi_v1alpha_resources_intent_proto_enumTypes[3].Descriptor()
}

func (IntentWithdrawal_WithdrawType) Type() protoreflect.EnumType {
	return &file_api_nbi_v1alpha_resources_intent_proto_enumTypes[3]
}

func (x IntentWithdrawal_WithdrawType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IntentWithdrawal_WithdrawType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IntentWithdrawal_WithdrawType(num)
	return nil
}

// Deprecated: Use IntentWithdrawal_WithdrawType.Descriptor instead.
func (IntentWithdrawal_WithdrawType) EnumDescriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{10, 0}
}

// Specifies a policy that reserves the use of a network resource.
// Once the controller has started compiling an intent, Network Applications
// must treat all fields except 'state' as immutable.  To modify the resource
// reserved by an intent, submit a new intent and withdraw the existing intent
// if necessary.
type Intent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TODO: Replace the use of this field with app_id in EntityGroup
	// and remove it.
	//
	// Deprecated: Marked as deprecated in api/nbi/v1alpha/resources/intent.proto.
	AppId *string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	// Determines what time the install request should be enacted.
	// If left blank, the intent compiler will request that the changes be made at
	// the earliest time that it believes it can deliver the messages to the
	// affected agents (that is, the maximum control plane latency to all affected
	// agents.
	TimeToEnact *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_to_enact,json=timeToEnact" json:"time_to_enact,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Intent_Link
	//	*Intent_Radio
	//	*Intent_Route
	//	*Intent_Modem
	//	*Intent_Bearer
	Value isIntent_Value `protobuf_oneof:"value"`
	State *IntentState   `protobuf:"varint,7,opt,name=state,enum=aalyria.spacetime.api.nbi.v1alpha.resources.IntentState,def=1" json:"state,omitempty"`
	// This field is only set after the intent enters the INSTALLING or
	// WITHDRAWING phases. It holds a timestamp indicating when the request was
	// made.
	RequestTimestampUs *int64 `protobuf:"varint,11,opt,name=request_timestamp_us,json=requestTimestampUs" json:"request_timestamp_us,omitempty"`
	// This field is only set after a successful compile phase.
	// The field contains the updates necessary for intent installation.
	CompiledUpdates []*common.ScheduledControlUpdate `protobuf:"bytes,8,rep,name=compiled_updates,json=compiledUpdates" json:"compiled_updates,omitempty"`
	// This field is set and defined if state = FAILED.
	Failure *IntentFailure `protobuf:"bytes,9,opt,name=failure" json:"failure,omitempty"`
	// This field is set in the WITHDRAW_REQ state, and only defined in
	// WITHDRAW_REQ, WITHDRAWING, and WITHDRAWN states.
	Withdrawal *IntentWithdrawal `protobuf:"bytes,14,opt,name=withdrawal" json:"withdrawal,omitempty"`
	// Determines what time the intent should be withdrawn.
	// If left blank, the intent will remain in the INSTALLED state until it is
	// updated to WITHDRAW_REQ or the intent fails.
	//
	// TODO: replace with google.protobuf.Timestamp.
	TimeToWithdraw *common.DateTime `protobuf:"bytes,15,opt,name=time_to_withdraw,json=timeToWithdraw" json:"time_to_withdraw,omitempty"`
	// An annotation indicating the service requests that the intent supports over
	// time.
	DependentServiceRequests []*Intent_ServiceRequestAndIntervals `protobuf:"bytes,16,rep,name=dependent_service_requests,json=dependentServiceRequests" json:"dependent_service_requests,omitempty"`
	// This field is only set after a successful compile phase.
	// The field contains the updates necessary for intent withdrawal.
	CompiledWithdrawalUpdates []*common.ScheduledControlUpdate `protobuf:"bytes,17,rep,name=compiled_withdrawal_updates,json=compiledWithdrawalUpdates" json:"compiled_withdrawal_updates,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for Intent fields.
const (
	Default_Intent_State = IntentState_INSTALL_REQ
)

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in api/nbi/v1alpha/resources/intent.proto.
func (x *Intent) GetAppId() string {
	if x != nil && x.AppId != nil {
		return *x.AppId
	}
	return ""
}

func (x *Intent) GetTimeToEnact() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeToEnact
	}
	return nil
}

func (x *Intent) GetValue() isIntent_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Intent) GetLink() *LinkIntent {
	if x != nil {
		if x, ok := x.Value.(*Intent_Link); ok {
			return x.Link
		}
	}
	return nil
}

func (x *Intent) GetRadio() *RadioIntent {
	if x != nil {
		if x, ok := x.Value.(*Intent_Radio); ok {
			return x.Radio
		}
	}
	return nil
}

func (x *Intent) GetRoute() *PathIntent {
	if x != nil {
		if x, ok := x.Value.(*Intent_Route); ok {
			return x.Route
		}
	}
	return nil
}

func (x *Intent) GetModem() *ModemIntent {
	if x != nil {
		if x, ok := x.Value.(*Intent_Modem); ok {
			return x.Modem
		}
	}
	return nil
}

func (x *Intent) GetBearer() *BearerIntent {
	if x != nil {
		if x, ok := x.Value.(*Intent_Bearer); ok {
			return x.Bearer
		}
	}
	return nil
}

func (x *Intent) GetState() IntentState {
	if x != nil && x.State != nil {
		return *x.State
	}
	return Default_Intent_State
}

func (x *Intent) GetRequestTimestampUs() int64 {
	if x != nil && x.RequestTimestampUs != nil {
		return *x.RequestTimestampUs
	}
	return 0
}

func (x *Intent) GetCompiledUpdates() []*common.ScheduledControlUpdate {
	if x != nil {
		return x.CompiledUpdates
	}
	return nil
}

func (x *Intent) GetFailure() *IntentFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *Intent) GetWithdrawal() *IntentWithdrawal {
	if x != nil {
		return x.Withdrawal
	}
	return nil
}

func (x *Intent) GetTimeToWithdraw() *common.DateTime {
	if x != nil {
		return x.TimeToWithdraw
	}
	return nil
}

func (x *Intent) GetDependentServiceRequests() []*Intent_ServiceRequestAndIntervals {
	if x != nil {
		return x.DependentServiceRequests
	}
	return nil
}

func (x *Intent) GetCompiledWithdrawalUpdates() []*common.ScheduledControlUpdate {
	if x != nil {
		return x.CompiledWithdrawalUpdates
	}
	return nil
}

type isIntent_Value interface {
	isIntent_Value()
}

type Intent_Link struct {
	Link *LinkIntent `protobuf:"bytes,4,opt,name=link,oneof"`
}

type Intent_Radio struct {
	Radio *RadioIntent `protobuf:"bytes,5,opt,name=radio,oneof"`
}

type Intent_Route struct {
	Route *PathIntent `protobuf:"bytes,6,opt,name=route,oneof"`
}

type Intent_Modem struct {
	Modem *ModemIntent `protobuf:"bytes,18,opt,name=modem,oneof"`
}

type Intent_Bearer struct {
	Bearer *BearerIntent `protobuf:"bytes,19,opt,name=bearer,oneof"`
}

func (*Intent_Link) isIntent_Value() {}

func (*Intent_Radio) isIntent_Value() {}

func (*Intent_Route) isIntent_Value() {}

func (*Intent_Modem) isIntent_Value() {}

func (*Intent_Bearer) isIntent_Value() {}

// Models an intent to configure steerable beams and/or radio resources.
type LinkIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to LinkType:
	//
	//	*LinkIntent_DirectionalLink
	//	*LinkIntent_BidirectionalLink
	LinkType      isLinkIntent_LinkType `protobuf_oneof:"link_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkIntent) Reset() {
	*x = LinkIntent{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkIntent) ProtoMessage() {}

func (x *LinkIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkIntent.ProtoReflect.Descriptor instead.
func (*LinkIntent) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{1}
}

func (x *LinkIntent) GetLinkType() isLinkIntent_LinkType {
	if x != nil {
		return x.LinkType
	}
	return nil
}

func (x *LinkIntent) GetDirectionalLink() *DirectionalLink {
	if x != nil {
		if x, ok := x.LinkType.(*LinkIntent_DirectionalLink); ok {
			return x.DirectionalLink
		}
	}
	return nil
}

func (x *LinkIntent) GetBidirectionalLink() *BidirectionalLink {
	if x != nil {
		if x, ok := x.LinkType.(*LinkIntent_BidirectionalLink); ok {
			return x.BidirectionalLink
		}
	}
	return nil
}

type isLinkIntent_LinkType interface {
	isLinkIntent_LinkType()
}

type LinkIntent_DirectionalLink struct {
	// Configures a single wireless interface.
	DirectionalLink *DirectionalLink `protobuf:"bytes,3,opt,name=directional_link,json=directionalLink,oneof"`
}

type LinkIntent_BidirectionalLink struct {
	// Configures a point-to-point link between a pair of wireless interfaces.
	BidirectionalLink *BidirectionalLink `protobuf:"bytes,2,opt,name=bidirectional_link,json=bidirectionalLink,oneof"`
}

func (*LinkIntent_DirectionalLink) isLinkIntent_LinkType() {}

func (*LinkIntent_BidirectionalLink) isLinkIntent_LinkType() {}

// Models an intent to change the radio parameters of one or more radios.
// In practice, apps are advised to only use repeated entries if the changes
// are related (for example, to set the transmiter and receiver participating
// in the same wireless link to use the same radio channel).
type RadioIntent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Configurations []*RadioConfiguration  `protobuf:"bytes,2,rep,name=configurations" json:"configurations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RadioIntent) Reset() {
	*x = RadioIntent{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioIntent) ProtoMessage() {}

func (x *RadioIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioIntent.ProtoReflect.Descriptor instead.
func (*RadioIntent) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{2}
}

func (x *RadioIntent) GetConfigurations() []*RadioConfiguration {
	if x != nil {
		return x.Configurations
	}
	return nil
}

// Models a route/path through the network.
type PathIntent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The network node/element that is the source of the network path.
	//
	// Deprecated: Marked as deprecated in api/nbi/v1alpha/resources/intent.proto.
	SrcElementId *string `protobuf:"bytes,1,opt,name=src_element_id,json=srcElementId" json:"src_element_id,omitempty"`
	// The network node/element that is the destination of the network path.
	//
	// Deprecated: Marked as deprecated in api/nbi/v1alpha/resources/intent.proto.
	DstElementId *string `protobuf:"bytes,2,opt,name=dst_element_id,json=dstElementId" json:"dst_element_id,omitempty"`
	// Defines rules for matching flows that should be forwarded along the path..
	Classifier *common.FlowClassifier `protobuf:"bytes,10,opt,name=classifier" json:"classifier,omitempty"`
	// The path segments that comprise the route.
	PathSegments  []*NetworkLink `protobuf:"bytes,3,rep,name=path_segments,json=pathSegments" json:"path_segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathIntent) Reset() {
	*x = PathIntent{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathIntent) ProtoMessage() {}

func (x *PathIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathIntent.ProtoReflect.Descriptor instead.
func (*PathIntent) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{3}
}

// Deprecated: Marked as deprecated in api/nbi/v1alpha/resources/intent.proto.
func (x *PathIntent) GetSrcElementId() string {
	if x != nil && x.SrcElementId != nil {
		return *x.SrcElementId
	}
	return ""
}

// Deprecated: Marked as deprecated in api/nbi/v1alpha/resources/intent.proto.
func (x *PathIntent) GetDstElementId() string {
	if x != nil && x.DstElementId != nil {
		return *x.DstElementId
	}
	return ""
}

func (x *PathIntent) GetClassifier() *common.FlowClassifier {
	if x != nil {
		return x.Classifier
	}
	return nil
}

func (x *PathIntent) GetPathSegments() []*NetworkLink {
	if x != nil {
		return x.PathSegments
	}
	return nil
}

type ModemIntent struct {
	state       protoimpl.MessageState     `protogen:"open.v1"`
	InterfaceId *common.NetworkInterfaceId `protobuf:"bytes,1,opt,name=interface_id,json=interfaceId" json:"interface_id,omitempty"`
	// The collection of beams to be illuminated. The beams are to be illuminated
	// one-at-a-time in a repeating sequence determined by the
	// beam_hopping_time_slots.
	Beams []*Beam `protobuf:"bytes,2,rep,name=beams" json:"beams,omitempty"`
	// A collection of beam-hopping time slots representing a beam-hopping frame.
	// Each slot consists of a zero-based index into the collection of beams,
	// representing the beam to be illuminated during that time slot. A value of
	// -1 represents that no beam should be illuminated during that time slot.
	BeamHoppingTimeSlots []int32 `protobuf:"varint,3,rep,name=beam_hopping_time_slots,json=beamHoppingTimeSlots" json:"beam_hopping_time_slots,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ModemIntent) Reset() {
	*x = ModemIntent{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModemIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemIntent) ProtoMessage() {}

func (x *ModemIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemIntent.ProtoReflect.Descriptor instead.
func (*ModemIntent) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{4}
}

func (x *ModemIntent) GetInterfaceId() *common.NetworkInterfaceId {
	if x != nil {
		return x.InterfaceId
	}
	return nil
}

func (x *ModemIntent) GetBeams() []*Beam {
	if x != nil {
		return x.Beams
	}
	return nil
}

func (x *ModemIntent) GetBeamHoppingTimeSlots() []int32 {
	if x != nil {
		return x.BeamHoppingTimeSlots
	}
	return nil
}

type Beam struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the NMTS EK_ANTENNA transmitting and/or receiving via the beam.
	Antenna *string          `protobuf:"bytes,5,opt,name=antenna" json:"antenna,omitempty"`
	Target  *BeamTarget      `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Rx      *RxConfiguration `protobuf:"bytes,2,opt,name=rx" json:"rx,omitempty"`
	Tx      *TxConfiguration `protobuf:"bytes,3,opt,name=tx" json:"tx,omitempty"`
	// The collection of endpoints served by the beam.
	// For example, a collection of user terminals (UTs) served.
	//
	// Each endpoint is the ID of a network node in Spacetime's network model.
	Endpoints     []*Endpoint `protobuf:"bytes,4,rep,name=endpoints" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Beam) Reset() {
	*x = Beam{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beam) ProtoMessage() {}

func (x *Beam) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beam.ProtoReflect.Descriptor instead.
func (*Beam) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{5}
}

func (x *Beam) GetAntenna() string {
	if x != nil && x.Antenna != nil {
		return *x.Antenna
	}
	return ""
}

func (x *Beam) GetTarget() *BeamTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Beam) GetRx() *RxConfiguration {
	if x != nil {
		return x.Rx
	}
	return nil
}

func (x *Beam) GetTx() *TxConfiguration {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *Beam) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RxConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PortId             *string                `protobuf:"bytes,9,opt,name=port_id,json=portId" json:"port_id,omitempty"`
	DemodulatorId      *string                `protobuf:"bytes,6,opt,name=demodulator_id,json=demodulatorId" json:"demodulator_id,omitempty"`
	ReceiverId         *string                `protobuf:"bytes,8,opt,name=receiver_id,json=receiverId" json:"receiver_id,omitempty"`
	CenterFrequencyHz  *uint64                `protobuf:"varint,1,opt,name=center_frequency_hz,json=centerFrequencyHz" json:"center_frequency_hz,omitempty"`
	ChannelBandwidthHz *uint64                `protobuf:"varint,2,opt,name=channel_bandwidth_hz,json=channelBandwidthHz" json:"channel_bandwidth_hz,omitempty"`
	Polarization       *Polarization          `protobuf:"varint,3,opt,name=polarization,enum=aalyria.spacetime.api.nbi.v1alpha.resources.Polarization" json:"polarization,omitempty"`
	// Symbol rate in Megasymbols per second.
	SymbolRateMsps *float64 `protobuf:"fixed64,5,opt,name=symbol_rate_msps,json=symbolRateMsps" json:"symbol_rate_msps,omitempty"`
	// This value corresponds to the nmts.v1.ek.physical.Carrier.waveform of the
	// carrier assigned to this beam. nmts.v1.ek.physical.Carriers are defined in
	// nmts.v1.ek.physical.CarrierConfigurations.
	Waveform        *string  `protobuf:"bytes,4,opt,name=waveform" json:"waveform,omitempty"`
	ExpectedRxPower *RxPower `protobuf:"bytes,7,opt,name=expected_rx_power,json=expectedRxPower" json:"expected_rx_power,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RxConfiguration) Reset() {
	*x = RxConfiguration{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RxConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RxConfiguration) ProtoMessage() {}

func (x *RxConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RxConfiguration.ProtoReflect.Descriptor instead.
func (*RxConfiguration) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{6}
}

func (x *RxConfiguration) GetPortId() string {
	if x != nil && x.PortId != nil {
		return *x.PortId
	}
	return ""
}

func (x *RxConfiguration) GetDemodulatorId() string {
	if x != nil && x.DemodulatorId != nil {
		return *x.DemodulatorId
	}
	return ""
}

func (x *RxConfiguration) GetReceiverId() string {
	if x != nil && x.ReceiverId != nil {
		return *x.ReceiverId
	}
	return ""
}

func (x *RxConfiguration) GetCenterFrequencyHz() uint64 {
	if x != nil && x.CenterFrequencyHz != nil {
		return *x.CenterFrequencyHz
	}
	return 0
}

func (x *RxConfiguration) GetChannelBandwidthHz() uint64 {
	if x != nil && x.ChannelBandwidthHz != nil {
		return *x.ChannelBandwidthHz
	}
	return 0
}

func (x *RxConfiguration) GetPolarization() Polarization {
	if x != nil && x.Polarization != nil {
		return *x.Polarization
	}
	return Polarization_POLARIZATION_UNSPECIFIED
}

func (x *RxConfiguration) GetSymbolRateMsps() float64 {
	if x != nil && x.SymbolRateMsps != nil {
		return *x.SymbolRateMsps
	}
	return 0
}

func (x *RxConfiguration) GetWaveform() string {
	if x != nil && x.Waveform != nil {
		return *x.Waveform
	}
	return ""
}

func (x *RxConfiguration) GetExpectedRxPower() *RxPower {
	if x != nil {
		return x.ExpectedRxPower
	}
	return nil
}

type TxConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PortId             *string                `protobuf:"bytes,10,opt,name=port_id,json=portId" json:"port_id,omitempty"`
	ModulatorId        *string                `protobuf:"bytes,8,opt,name=modulator_id,json=modulatorId" json:"modulator_id,omitempty"`
	TransmitterId      *string                `protobuf:"bytes,9,opt,name=transmitter_id,json=transmitterId" json:"transmitter_id,omitempty"`
	CenterFrequencyHz  *uint64                `protobuf:"varint,1,opt,name=center_frequency_hz,json=centerFrequencyHz" json:"center_frequency_hz,omitempty"`
	ChannelBandwidthHz *uint64                `protobuf:"varint,2,opt,name=channel_bandwidth_hz,json=channelBandwidthHz" json:"channel_bandwidth_hz,omitempty"`
	Polarization       *Polarization          `protobuf:"varint,3,opt,name=polarization,enum=aalyria.spacetime.api.nbi.v1alpha.resources.Polarization" json:"polarization,omitempty"`
	// Transmit power in Watts.
	PowerW *float64 `protobuf:"fixed64,5,opt,name=power_w,json=powerW" json:"power_w,omitempty"`
	// Symbol rate in Megasymbols per second.
	SymbolRateMsps *float64 `protobuf:"fixed64,6,opt,name=symbol_rate_msps,json=symbolRateMsps" json:"symbol_rate_msps,omitempty"`
	// This value corresponds to the nmts.v1.ek.physical.Carrier.waveform of the
	// carrier assigned to this beam. nmts.v1.ek.physical.Carriers are defined in
	// nmts.v1.ek.physical.CarrierConfigurations.
	Waveform *string `protobuf:"bytes,4,opt,name=waveform" json:"waveform,omitempty"`
	// The lowest MODCOD common among all endpoints.
	LowestCommonModcod *string `protobuf:"bytes,7,opt,name=lowest_common_modcod,json=lowestCommonModcod" json:"lowest_common_modcod,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TxConfiguration) Reset() {
	*x = TxConfiguration{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxConfiguration) ProtoMessage() {}

func (x *TxConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxConfiguration.ProtoReflect.Descriptor instead.
func (*TxConfiguration) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{7}
}

func (x *TxConfiguration) GetPortId() string {
	if x != nil && x.PortId != nil {
		return *x.PortId
	}
	return ""
}

func (x *TxConfiguration) GetModulatorId() string {
	if x != nil && x.ModulatorId != nil {
		return *x.ModulatorId
	}
	return ""
}

func (x *TxConfiguration) GetTransmitterId() string {
	if x != nil && x.TransmitterId != nil {
		return *x.TransmitterId
	}
	return ""
}

func (x *TxConfiguration) GetCenterFrequencyHz() uint64 {
	if x != nil && x.CenterFrequencyHz != nil {
		return *x.CenterFrequencyHz
	}
	return 0
}

func (x *TxConfiguration) GetChannelBandwidthHz() uint64 {
	if x != nil && x.ChannelBandwidthHz != nil {
		return *x.ChannelBandwidthHz
	}
	return 0
}

func (x *TxConfiguration) GetPolarization() Polarization {
	if x != nil && x.Polarization != nil {
		return *x.Polarization
	}
	return Polarization_POLARIZATION_UNSPECIFIED
}

func (x *TxConfiguration) GetPowerW() float64 {
	if x != nil && x.PowerW != nil {
		return *x.PowerW
	}
	return 0
}

func (x *TxConfiguration) GetSymbolRateMsps() float64 {
	if x != nil && x.SymbolRateMsps != nil {
		return *x.SymbolRateMsps
	}
	return 0
}

func (x *TxConfiguration) GetWaveform() string {
	if x != nil && x.Waveform != nil {
		return *x.Waveform
	}
	return ""
}

func (x *TxConfiguration) GetLowestCommonModcod() string {
	if x != nil && x.LowestCommonModcod != nil {
		return *x.LowestCommonModcod
	}
	return ""
}

type Endpoint struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	LowestSupportedRxModcod  *string                `protobuf:"bytes,2,opt,name=lowest_supported_rx_modcod,json=lowestSupportedRxModcod" json:"lowest_supported_rx_modcod,omitempty"`
	RxReferenceThroughputBps *float64               `protobuf:"fixed64,3,opt,name=rx_reference_throughput_bps,json=rxReferenceThroughputBps" json:"rx_reference_throughput_bps,omitempty"`
	TxReferenceThroughputBps *float64               `protobuf:"fixed64,4,opt,name=tx_reference_throughput_bps,json=txReferenceThroughputBps" json:"tx_reference_throughput_bps,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{8}
}

func (x *Endpoint) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Endpoint) GetLowestSupportedRxModcod() string {
	if x != nil && x.LowestSupportedRxModcod != nil {
		return *x.LowestSupportedRxModcod
	}
	return ""
}

func (x *Endpoint) GetRxReferenceThroughputBps() float64 {
	if x != nil && x.RxReferenceThroughputBps != nil {
		return *x.RxReferenceThroughputBps
	}
	return 0
}

func (x *Endpoint) GetTxReferenceThroughputBps() float64 {
	if x != nil && x.TxReferenceThroughputBps != nil {
		return *x.TxReferenceThroughputBps
	}
	return 0
}

// IntentFailure provides context on the failure of an intent. It's purpose is
// to allow apps to make better decision when faced with failures.
type IntentFailure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Failure type is set if the state = FAILED.
	Type *IntentFailure_IntentFailureType `protobuf:"varint,1,opt,name=type,enum=aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure_IntentFailureType" json:"type,omitempty"`
	// This field is set if type = PRECONDITION_FAILED.
	PreconditionFailure *IntentFailure `protobuf:"bytes,2,opt,name=precondition_failure,json=preconditionFailure" json:"precondition_failure,omitempty"`
	// Human readable description of the failure.
	Description *string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	// This field is set if failure_type = AGENT_INSTALLATION_FAILURE,
	// UNREACHABLE_AGENT, UNEXPECTED_CDPI_STATE_CHANGE, or SDN_INTERNAL_ERROR.
	AgentIds []string `protobuf:"bytes,4,rep,name=agent_ids,json=agentIds" json:"agent_ids,omitempty"`
	// This field is set if failure_type = AGENT_INSTALLATION_FAILURE.
	AgentFailureCode *code.Code `protobuf:"varint,5,opt,name=agent_failure_code,json=agentFailureCode,enum=google.rpc.Code" json:"agent_failure_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IntentFailure) Reset() {
	*x = IntentFailure{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentFailure) ProtoMessage() {}

func (x *IntentFailure) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentFailure.ProtoReflect.Descriptor instead.
func (*IntentFailure) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{9}
}

func (x *IntentFailure) GetType() IntentFailure_IntentFailureType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return IntentFailure_UNKNOWN
}

func (x *IntentFailure) GetPreconditionFailure() *IntentFailure {
	if x != nil {
		return x.PreconditionFailure
	}
	return nil
}

func (x *IntentFailure) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *IntentFailure) GetAgentIds() []string {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

func (x *IntentFailure) GetAgentFailureCode() code.Code {
	if x != nil && x.AgentFailureCode != nil {
		return *x.AgentFailureCode
	}
	return code.Code(0)
}

// IntentWithdrawal can expose more information about why an app chose to
// withdraw an intent. It is designed to surface decision making information to
// administrators to explain the SDN behavior.
type IntentWithdrawal struct {
	state protoimpl.MessageState         `protogen:"open.v1"`
	Type  *IntentWithdrawal_WithdrawType `protobuf:"varint,1,opt,name=type,enum=aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal_WithdrawType" json:"type,omitempty"`
	// Human readable details of the withdraw reason.
	Description   *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentWithdrawal) Reset() {
	*x = IntentWithdrawal{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentWithdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentWithdrawal) ProtoMessage() {}

func (x *IntentWithdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentWithdrawal.ProtoReflect.Descriptor instead.
func (*IntentWithdrawal) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{10}
}

func (x *IntentWithdrawal) GetType() IntentWithdrawal_WithdrawType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return IntentWithdrawal_UNKNOWN
}

func (x *IntentWithdrawal) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// A bearer intent represents an intent to establish a bearer towards a
// connectivity service provider's network via an Interconnect API.
type BearerIntent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProviderId *string                `protobuf:"bytes,1,opt,name=provider_id,json=providerId" json:"provider_id,omitempty"`
	// The modulator that is to connect with a demodulator in the provider's
	// network.
	ModulatorId *string `protobuf:"bytes,2,opt,name=modulator_id,json=modulatorId" json:"modulator_id,omitempty"`
	// The demodulator that is to connect with a modulator in the provider's
	// network.
	DemodulatorId *string `protobuf:"bytes,3,opt,name=demodulator_id,json=demodulatorId" json:"demodulator_id,omitempty"`
	// The ID of the network node associated with the modulator and demodulator
	// above.
	NetworkNodeId *string `protobuf:"bytes,10,opt,name=network_node_id,json=networkNodeId" json:"network_node_id,omitempty"`
	// For non-NMTS environments, the interface that is to connect with the
	// provider's network.
	Transceiver *common.NetworkInterfaceId `protobuf:"bytes,4,opt,name=transceiver" json:"transceiver,omitempty"`
	// The ID of the InterconectTarget through which the connection is to be
	// established.
	TargetId            *string `protobuf:"bytes,5,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	RxCenterFrequencyHz *int64  `protobuf:"varint,6,opt,name=rx_center_frequency_hz,json=rxCenterFrequencyHz" json:"rx_center_frequency_hz,omitempty"`
	RxBandwidthHz       *int64  `protobuf:"varint,7,opt,name=rx_bandwidth_hz,json=rxBandwidthHz" json:"rx_bandwidth_hz,omitempty"`
	TxCenterFrequencyHz *int64  `protobuf:"varint,8,opt,name=tx_center_frequency_hz,json=txCenterFrequencyHz" json:"tx_center_frequency_hz,omitempty"`
	TxBandwidthHz       *int64  `protobuf:"varint,9,opt,name=tx_bandwidth_hz,json=txBandwidthHz" json:"tx_bandwidth_hz,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BearerIntent) Reset() {
	*x = BearerIntent{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BearerIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BearerIntent) ProtoMessage() {}

func (x *BearerIntent) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BearerIntent.ProtoReflect.Descriptor instead.
func (*BearerIntent) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{11}
}

func (x *BearerIntent) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *BearerIntent) GetModulatorId() string {
	if x != nil && x.ModulatorId != nil {
		return *x.ModulatorId
	}
	return ""
}

func (x *BearerIntent) GetDemodulatorId() string {
	if x != nil && x.DemodulatorId != nil {
		return *x.DemodulatorId
	}
	return ""
}

func (x *BearerIntent) GetNetworkNodeId() string {
	if x != nil && x.NetworkNodeId != nil {
		return *x.NetworkNodeId
	}
	return ""
}

func (x *BearerIntent) GetTransceiver() *common.NetworkInterfaceId {
	if x != nil {
		return x.Transceiver
	}
	return nil
}

func (x *BearerIntent) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *BearerIntent) GetRxCenterFrequencyHz() int64 {
	if x != nil && x.RxCenterFrequencyHz != nil {
		return *x.RxCenterFrequencyHz
	}
	return 0
}

func (x *BearerIntent) GetRxBandwidthHz() int64 {
	if x != nil && x.RxBandwidthHz != nil {
		return *x.RxBandwidthHz
	}
	return 0
}

func (x *BearerIntent) GetTxCenterFrequencyHz() int64 {
	if x != nil && x.TxCenterFrequencyHz != nil {
		return *x.TxCenterFrequencyHz
	}
	return 0
}

func (x *BearerIntent) GetTxBandwidthHz() int64 {
	if x != nil && x.TxBandwidthHz != nil {
		return *x.TxBandwidthHz
	}
	return 0
}

type Intent_ServiceRequestAndIntervals struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceRequestId *string                `protobuf:"bytes,1,opt,name=service_request_id,json=serviceRequestId" json:"service_request_id,omitempty"`
	Interval         []*interval.Interval   `protobuf:"bytes,2,rep,name=interval" json:"interval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Intent_ServiceRequestAndIntervals) Reset() {
	*x = Intent_ServiceRequestAndIntervals{}
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent_ServiceRequestAndIntervals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent_ServiceRequestAndIntervals) ProtoMessage() {}

func (x *Intent_ServiceRequestAndIntervals) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_resources_intent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent_ServiceRequestAndIntervals.ProtoReflect.Descriptor instead.
func (*Intent_ServiceRequestAndIntervals) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Intent_ServiceRequestAndIntervals) GetServiceRequestId() string {
	if x != nil && x.ServiceRequestId != nil {
		return *x.ServiceRequestId
	}
	return ""
}

func (x *Intent_ServiceRequestAndIntervals) GetInterval() []*interval.Interval {
	if x != nil {
		return x.Interval
	}
	return nil
}

var File_api_nbi_v1alpha_resources_intent_proto protoreflect.FileDescriptor

const file_api_nbi_v1alpha_resources_intent_proto_rawDesc = "" +
	"\n" +
	"&api/nbi/v1alpha/resources/intent.proto\x12+aalyria.spacetime.api.nbi.v1alpha.resources\x1a\x18api/common/control.proto\x1a\x18api/common/network.proto\x1a\x15api/common/time.proto\x1a,api/nbi/v1alpha/resources/network_link.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15google/rpc/code.proto\x1a\x1agoogle/type/interval.proto\"\x9c\v\n" +
	"\x06Intent\x12\x19\n" +
	"\x06app_id\x18\x01 \x01(\tB\x02\x18\x01R\x05appId\x12>\n" +
	"\rtime_to_enact\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vtimeToEnact\x12M\n" +
	"\x04link\x18\x04 \x01(\v27.aalyria.spacetime.api.nbi.v1alpha.resources.LinkIntentH\x00R\x04link\x12P\n" +
	"\x05radio\x18\x05 \x01(\v28.aalyria.spacetime.api.nbi.v1alpha.resources.RadioIntentH\x00R\x05radio\x12O\n" +
	"\x05route\x18\x06 \x01(\v27.aalyria.spacetime.api.nbi.v1alpha.resources.PathIntentH\x00R\x05route\x12P\n" +
	"\x05modem\x18\x12 \x01(\v28.aalyria.spacetime.api.nbi.v1alpha.resources.ModemIntentH\x00R\x05modem\x12S\n" +
	"\x06bearer\x18\x13 \x01(\v29.aalyria.spacetime.api.nbi.v1alpha.resources.BearerIntentH\x00R\x06bearer\x12[\n" +
	"\x05state\x18\a \x01(\x0e28.aalyria.spacetime.api.nbi.v1alpha.resources.IntentState:\vINSTALL_REQR\x05state\x120\n" +
	"\x14request_timestamp_us\x18\v \x01(\x03R\x12requestTimestampUs\x12_\n" +
	"\x10compiled_updates\x18\b \x03(\v24.aalyria.spacetime.api.common.ScheduledControlUpdateR\x0fcompiledUpdates\x12T\n" +
	"\afailure\x18\t \x01(\v2:.aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailureR\afailure\x12]\n" +
	"\n" +
	"withdrawal\x18\x0e \x01(\v2=.aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawalR\n" +
	"withdrawal\x12P\n" +
	"\x10time_to_withdraw\x18\x0f \x01(\v2&.aalyria.spacetime.api.common.DateTimeR\x0etimeToWithdraw\x12\x8c\x01\n" +
	"\x1adependent_service_requests\x18\x10 \x03(\v2N.aalyria.spacetime.api.nbi.v1alpha.resources.Intent.ServiceRequestAndIntervalsR\x18dependentServiceRequests\x12t\n" +
	"\x1bcompiled_withdrawal_updates\x18\x11 \x03(\v24.aalyria.spacetime.api.common.ScheduledControlUpdateR\x19compiledWithdrawalUpdates\x1a}\n" +
	"\x1aServiceRequestAndIntervals\x12,\n" +
	"\x12service_request_id\x18\x01 \x01(\tR\x10serviceRequestId\x121\n" +
	"\binterval\x18\x02 \x03(\v2\x15.google.type.IntervalR\bintervalB\a\n" +
	"\x05valueJ\x04\b\x02\x10\x03J\x04\b\n" +
	"\x10\vJ\x04\b\f\x10\rJ\b\b\x14\x10\x80\x80\x80\x80\x02\"\x85\x02\n" +
	"\n" +
	"LinkIntent\x12i\n" +
	"\x10directional_link\x18\x03 \x01(\v2<.aalyria.spacetime.api.nbi.v1alpha.resources.DirectionalLinkH\x00R\x0fdirectionalLink\x12o\n" +
	"\x12bidirectional_link\x18\x02 \x01(\v2>.aalyria.spacetime.api.nbi.v1alpha.resources.BidirectionalLinkH\x00R\x11bidirectionalLinkB\v\n" +
	"\tlink_typeJ\x04\b\x01\x10\x02J\b\b\x04\x10\x80\x80\x80\x80\x02\"\x86\x01\n" +
	"\vRadioIntent\x12g\n" +
	"\x0econfigurations\x18\x02 \x03(\v2?.aalyria.spacetime.api.nbi.v1alpha.resources.RadioConfigurationR\x0econfigurationsJ\x04\b\x01\x10\x02J\b\b\x03\x10\x80\x80\x80\x80\x02\"\x9d\x02\n" +
	"\n" +
	"PathIntent\x12(\n" +
	"\x0esrc_element_id\x18\x01 \x01(\tB\x02\x18\x01R\fsrcElementId\x12(\n" +
	"\x0edst_element_id\x18\x02 \x01(\tB\x02\x18\x01R\fdstElementId\x12L\n" +
	"\n" +
	"classifier\x18\n" +
	" \x01(\v2,.aalyria.spacetime.api.common.FlowClassifierR\n" +
	"classifier\x12]\n" +
	"\rpath_segments\x18\x03 \x03(\v28.aalyria.spacetime.api.nbi.v1alpha.resources.NetworkLinkR\fpathSegmentsJ\x04\b\x04\x10\tJ\b\b\v\x10\x80\x80\x80\x80\x02\"\xe2\x01\n" +
	"\vModemIntent\x12S\n" +
	"\finterface_id\x18\x01 \x01(\v20.aalyria.spacetime.api.common.NetworkInterfaceIdR\vinterfaceId\x12G\n" +
	"\x05beams\x18\x02 \x03(\v21.aalyria.spacetime.api.nbi.v1alpha.resources.BeamR\x05beams\x125\n" +
	"\x17beam_hopping_time_slots\x18\x03 \x03(\x05R\x14beamHoppingTimeSlots\"\xe2\x02\n" +
	"\x04Beam\x12\x18\n" +
	"\aantenna\x18\x05 \x01(\tR\aantenna\x12O\n" +
	"\x06target\x18\x01 \x01(\v27.aalyria.spacetime.api.nbi.v1alpha.resources.BeamTargetR\x06target\x12L\n" +
	"\x02rx\x18\x02 \x01(\v2<.aalyria.spacetime.api.nbi.v1alpha.resources.RxConfigurationR\x02rx\x12L\n" +
	"\x02tx\x18\x03 \x01(\v2<.aalyria.spacetime.api.nbi.v1alpha.resources.TxConfigurationR\x02tx\x12S\n" +
	"\tendpoints\x18\x04 \x03(\v25.aalyria.spacetime.api.nbi.v1alpha.resources.EndpointR\tendpoints\"\xdb\x03\n" +
	"\x0fRxConfiguration\x12\x17\n" +
	"\aport_id\x18\t \x01(\tR\x06portId\x12%\n" +
	"\x0edemodulator_id\x18\x06 \x01(\tR\rdemodulatorId\x12\x1f\n" +
	"\vreceiver_id\x18\b \x01(\tR\n" +
	"receiverId\x12.\n" +
	"\x13center_frequency_hz\x18\x01 \x01(\x04R\x11centerFrequencyHz\x120\n" +
	"\x14channel_bandwidth_hz\x18\x02 \x01(\x04R\x12channelBandwidthHz\x12]\n" +
	"\fpolarization\x18\x03 \x01(\x0e29.aalyria.spacetime.api.nbi.v1alpha.resources.PolarizationR\fpolarization\x12(\n" +
	"\x10symbol_rate_msps\x18\x05 \x01(\x01R\x0esymbolRateMsps\x12\x1a\n" +
	"\bwaveform\x18\x04 \x01(\tR\bwaveform\x12`\n" +
	"\x11expected_rx_power\x18\a \x01(\v24.aalyria.spacetime.api.nbi.v1alpha.resources.RxPowerR\x0fexpectedRxPower\"\xc6\x03\n" +
	"\x0fTxConfiguration\x12\x17\n" +
	"\aport_id\x18\n" +
	" \x01(\tR\x06portId\x12!\n" +
	"\fmodulator_id\x18\b \x01(\tR\vmodulatorId\x12%\n" +
	"\x0etransmitter_id\x18\t \x01(\tR\rtransmitterId\x12.\n" +
	"\x13center_frequency_hz\x18\x01 \x01(\x04R\x11centerFrequencyHz\x120\n" +
	"\x14channel_bandwidth_hz\x18\x02 \x01(\x04R\x12channelBandwidthHz\x12]\n" +
	"\fpolarization\x18\x03 \x01(\x0e29.aalyria.spacetime.api.nbi.v1alpha.resources.PolarizationR\fpolarization\x12\x17\n" +
	"\apower_w\x18\x05 \x01(\x01R\x06powerW\x12(\n" +
	"\x10symbol_rate_msps\x18\x06 \x01(\x01R\x0esymbolRateMsps\x12\x1a\n" +
	"\bwaveform\x18\x04 \x01(\tR\bwaveform\x120\n" +
	"\x14lowest_common_modcod\x18\a \x01(\tR\x12lowestCommonModcod\"\xd5\x01\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x1alowest_supported_rx_modcod\x18\x02 \x01(\tR\x17lowestSupportedRxModcod\x12=\n" +
	"\x1brx_reference_throughput_bps\x18\x03 \x01(\x01R\x18rxReferenceThroughputBps\x12=\n" +
	"\x1btx_reference_throughput_bps\x18\x04 \x01(\x01R\x18txReferenceThroughputBps\"\xf0\x04\n" +
	"\rIntentFailure\x12`\n" +
	"\x04type\x18\x01 \x01(\x0e2L.aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure.IntentFailureTypeR\x04type\x12m\n" +
	"\x14precondition_failure\x18\x02 \x01(\v2:.aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailureR\x13preconditionFailure\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tagent_ids\x18\x04 \x03(\tR\bagentIds\x12>\n" +
	"\x12agent_failure_code\x18\x05 \x01(\x0e2\x10.google.rpc.CodeR\x10agentFailureCode\"\x84\x02\n" +
	"\x11IntentFailureType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x17\n" +
	"\x13COMPILATION_FAILURE\x10\x01\x12\x1e\n" +
	"\x1aAGENT_INSTALLATION_FAILURE\x10\x02\x12\x15\n" +
	"\x11UNREACHABLE_AGENT\x10\x03\x12 \n" +
	"\x1cUNEXPECTED_CDPI_STATE_CHANGE\x10\x04\x12\x17\n" +
	"\x13PRECONDITION_FAILED\x10\x05\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x06\x12\x18\n" +
	"\x14PRECONDITION_EXPIRED\x10\a\x12\x16\n" +
	"\x12SDN_INTERNAL_ERROR\x10\t\"\x04\b\b\x10\b\"\b\b\n" +
	"\x10\xff\xff\xff\xff\aJ\b\b\x06\x10\x80\x80\x80\x80\x02\"\xe9\x01\n" +
	"\x10IntentWithdrawal\x12^\n" +
	"\x04type\x18\x01 \x01(\x0e2J.aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal.WithdrawTypeR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"I\n" +
	"\fWithdrawType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fINACCESSIBLE\x10\x01\x12\x10\n" +
	"\fNOT_REQUIRED\x10\x02\"\b\b\x03\x10\xff\xff\xff\xff\aJ\b\b\x03\x10\x80\x80\x80\x80\x02\"\xcc\x03\n" +
	"\fBearerIntent\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fmodulator_id\x18\x02 \x01(\tR\vmodulatorId\x12%\n" +
	"\x0edemodulator_id\x18\x03 \x01(\tR\rdemodulatorId\x12&\n" +
	"\x0fnetwork_node_id\x18\n" +
	" \x01(\tR\rnetworkNodeId\x12R\n" +
	"\vtransceiver\x18\x04 \x01(\v20.aalyria.spacetime.api.common.NetworkInterfaceIdR\vtransceiver\x12\x1b\n" +
	"\ttarget_id\x18\x05 \x01(\tR\btargetId\x123\n" +
	"\x16rx_center_frequency_hz\x18\x06 \x01(\x03R\x13rxCenterFrequencyHz\x12&\n" +
	"\x0frx_bandwidth_hz\x18\a \x01(\x03R\rrxBandwidthHz\x123\n" +
	"\x16tx_center_frequency_hz\x18\b \x01(\x03R\x13txCenterFrequencyHz\x12&\n" +
	"\x0ftx_bandwidth_hz\x18\t \x01(\x03R\rtxBandwidthHz*\xb0\x01\n" +
	"\vIntentState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0f\n" +
	"\vINSTALL_REQ\x10\x01\x12\r\n" +
	"\tSCHEDULED\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"SCHEDULING\x10\f\x12\x0e\n" +
	"\n" +
	"INSTALLING\x10\x03\x12\r\n" +
	"\tINSTALLED\x10\x04\x12\x10\n" +
	"\fWITHDRAW_REQ\x10\x05\x12\x0f\n" +
	"\vWITHDRAWING\x10\x06\x12\n" +
	"\n" +
	"\x06FAILED\x10\b\"\x04\b\x02\x10\x02\"\x04\b\a\x10\a\"\x04\b\t\x10\t\"\x04\b\v\x10\v*Z\n" +
	"\fPolarization\x12\x1c\n" +
	"\x18POLARIZATION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POLARIZATION_LHCP\x10\x01\x12\x15\n" +
	"\x11POLARIZATION_RHCP\x10\x02Bb\n" +
	"/com.aalyria.spacetime.api.nbi.v1alpha.resourcesZ/aalyria.com/spacetime/api/nbi/v1alpha/resources"

var (
	file_api_nbi_v1alpha_resources_intent_proto_rawDescOnce sync.Once
	file_api_nbi_v1alpha_resources_intent_proto_rawDescData []byte
)

func file_api_nbi_v1alpha_resources_intent_proto_rawDescGZIP() []byte {
	file_api_nbi_v1alpha_resources_intent_proto_rawDescOnce.Do(func() {
		file_api_nbi_v1alpha_resources_intent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_resources_intent_proto_rawDesc), len(file_api_nbi_v1alpha_resources_intent_proto_rawDesc)))
	})
	return file_api_nbi_v1alpha_resources_intent_proto_rawDescData
}

var file_api_nbi_v1alpha_resources_intent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_nbi_v1alpha_resources_intent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_nbi_v1alpha_resources_intent_proto_goTypes = []any{
	(IntentState)(0),                          // 0: aalyria.spacetime.api.nbi.v1alpha.resources.IntentState
	(Polarization)(0),                         // 1: aalyria.spacetime.api.nbi.v1alpha.resources.Polarization
	(IntentFailure_IntentFailureType)(0),      // 2: aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure.IntentFailureType
	(IntentWithdrawal_WithdrawType)(0),        // 3: aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal.WithdrawType
	(*Intent)(nil),                            // 4: aalyria.spacetime.api.nbi.v1alpha.resources.Intent
	(*LinkIntent)(nil),                        // 5: aalyria.spacetime.api.nbi.v1alpha.resources.LinkIntent
	(*RadioIntent)(nil),                       // 6: aalyria.spacetime.api.nbi.v1alpha.resources.RadioIntent
	(*PathIntent)(nil),                        // 7: aalyria.spacetime.api.nbi.v1alpha.resources.PathIntent
	(*ModemIntent)(nil),                       // 8: aalyria.spacetime.api.nbi.v1alpha.resources.ModemIntent
	(*Beam)(nil),                              // 9: aalyria.spacetime.api.nbi.v1alpha.resources.Beam
	(*RxConfiguration)(nil),                   // 10: aalyria.spacetime.api.nbi.v1alpha.resources.RxConfiguration
	(*TxConfiguration)(nil),                   // 11: aalyria.spacetime.api.nbi.v1alpha.resources.TxConfiguration
	(*Endpoint)(nil),                          // 12: aalyria.spacetime.api.nbi.v1alpha.resources.Endpoint
	(*IntentFailure)(nil),                     // 13: aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure
	(*IntentWithdrawal)(nil),                  // 14: aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal
	(*BearerIntent)(nil),                      // 15: aalyria.spacetime.api.nbi.v1alpha.resources.BearerIntent
	(*Intent_ServiceRequestAndIntervals)(nil), // 16: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.ServiceRequestAndIntervals
	(*timestamppb.Timestamp)(nil),             // 17: google.protobuf.Timestamp
	(*common.ScheduledControlUpdate)(nil),     // 18: aalyria.spacetime.api.common.ScheduledControlUpdate
	(*common.DateTime)(nil),                   // 19: aalyria.spacetime.api.common.DateTime
	(*DirectionalLink)(nil),                   // 20: aalyria.spacetime.api.nbi.v1alpha.resources.DirectionalLink
	(*BidirectionalLink)(nil),                 // 21: aalyria.spacetime.api.nbi.v1alpha.resources.BidirectionalLink
	(*RadioConfiguration)(nil),                // 22: aalyria.spacetime.api.nbi.v1alpha.resources.RadioConfiguration
	(*common.FlowClassifier)(nil),             // 23: aalyria.spacetime.api.common.FlowClassifier
	(*NetworkLink)(nil),                       // 24: aalyria.spacetime.api.nbi.v1alpha.resources.NetworkLink
	(*common.NetworkInterfaceId)(nil),         // 25: aalyria.spacetime.api.common.NetworkInterfaceId
	(*BeamTarget)(nil),                        // 26: aalyria.spacetime.api.nbi.v1alpha.resources.BeamTarget
	(*RxPower)(nil),                           // 27: aalyria.spacetime.api.nbi.v1alpha.resources.RxPower
	(code.Code)(0),                            // 28: google.rpc.Code
	(*interval.Interval)(nil),                 // 29: google.type.Interval
}
var file_api_nbi_v1alpha_resources_intent_proto_depIdxs = []int32{
	17, // 0: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.time_to_enact:type_name -> google.protobuf.Timestamp
	5,  // 1: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.link:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.LinkIntent
	6,  // 2: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.radio:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.RadioIntent
	7,  // 3: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.route:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.PathIntent
	8,  // 4: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.modem:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.ModemIntent
	15, // 5: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.bearer:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.BearerIntent
	0,  // 6: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.state:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.IntentState
	18, // 7: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.compiled_updates:type_name -> aalyria.spacetime.api.common.ScheduledControlUpdate
	13, // 8: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.failure:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure
	14, // 9: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.withdrawal:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal
	19, // 10: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.time_to_withdraw:type_name -> aalyria.spacetime.api.common.DateTime
	16, // 11: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.dependent_service_requests:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.Intent.ServiceRequestAndIntervals
	18, // 12: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.compiled_withdrawal_updates:type_name -> aalyria.spacetime.api.common.ScheduledControlUpdate
	20, // 13: aalyria.spacetime.api.nbi.v1alpha.resources.LinkIntent.directional_link:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.DirectionalLink
	21, // 14: aalyria.spacetime.api.nbi.v1alpha.resources.LinkIntent.bidirectional_link:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.BidirectionalLink
	22, // 15: aalyria.spacetime.api.nbi.v1alpha.resources.RadioIntent.configurations:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.RadioConfiguration
	23, // 16: aalyria.spacetime.api.nbi.v1alpha.resources.PathIntent.classifier:type_name -> aalyria.spacetime.api.common.FlowClassifier
	24, // 17: aalyria.spacetime.api.nbi.v1alpha.resources.PathIntent.path_segments:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.NetworkLink
	25, // 18: aalyria.spacetime.api.nbi.v1alpha.resources.ModemIntent.interface_id:type_name -> aalyria.spacetime.api.common.NetworkInterfaceId
	9,  // 19: aalyria.spacetime.api.nbi.v1alpha.resources.ModemIntent.beams:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.Beam
	26, // 20: aalyria.spacetime.api.nbi.v1alpha.resources.Beam.target:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.BeamTarget
	10, // 21: aalyria.spacetime.api.nbi.v1alpha.resources.Beam.rx:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.RxConfiguration
	11, // 22: aalyria.spacetime.api.nbi.v1alpha.resources.Beam.tx:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.TxConfiguration
	12, // 23: aalyria.spacetime.api.nbi.v1alpha.resources.Beam.endpoints:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.Endpoint
	1,  // 24: aalyria.spacetime.api.nbi.v1alpha.resources.RxConfiguration.polarization:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.Polarization
	27, // 25: aalyria.spacetime.api.nbi.v1alpha.resources.RxConfiguration.expected_rx_power:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.RxPower
	1,  // 26: aalyria.spacetime.api.nbi.v1alpha.resources.TxConfiguration.polarization:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.Polarization
	2,  // 27: aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure.type:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure.IntentFailureType
	13, // 28: aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure.precondition_failure:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure
	28, // 29: aalyria.spacetime.api.nbi.v1alpha.resources.IntentFailure.agent_failure_code:type_name -> google.rpc.Code
	3,  // 30: aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal.type:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.IntentWithdrawal.WithdrawType
	25, // 31: aalyria.spacetime.api.nbi.v1alpha.resources.BearerIntent.transceiver:type_name -> aalyria.spacetime.api.common.NetworkInterfaceId
	29, // 32: aalyria.spacetime.api.nbi.v1alpha.resources.Intent.ServiceRequestAndIntervals.interval:type_name -> google.type.Interval
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_api_nbi_v1alpha_resources_intent_proto_init() }
func file_api_nbi_v1alpha_resources_intent_proto_init() {
	if File_api_nbi_v1alpha_resources_intent_proto != nil {
		return
	}
	file_api_nbi_v1alpha_resources_network_link_proto_init()
	file_api_nbi_v1alpha_resources_intent_proto_msgTypes[0].OneofWrappers = []any{
		(*Intent_Link)(nil),
		(*Intent_Radio)(nil),
		(*Intent_Route)(nil),
		(*Intent_Modem)(nil),
		(*Intent_Bearer)(nil),
	}
	file_api_nbi_v1alpha_resources_intent_proto_msgTypes[1].OneofWrappers = []any{
		(*LinkIntent_DirectionalLink)(nil),
		(*LinkIntent_BidirectionalLink)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_resources_intent_proto_rawDesc), len(file_api_nbi_v1alpha_resources_intent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_nbi_v1alpha_resources_intent_proto_goTypes,
		DependencyIndexes: file_api_nbi_v1alpha_resources_intent_proto_depIdxs,
		EnumInfos:         file_api_nbi_v1alpha_resources_intent_proto_enumTypes,
		MessageInfos:      file_api_nbi_v1alpha_resources_intent_proto_msgTypes,
	}.Build()
	File_api_nbi_v1alpha_resources_intent_proto = out.File
	file_api_nbi_v1alpha_resources_intent_proto_goTypes = nil
	file_api_nbi_v1alpha_resources_intent_proto_depIdxs = nil
}
