// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: nmts/v1/proto/types/geophys/coordinates.proto

package geophys

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinateFrame int32

const (
	CoordinateFrame_COORDINATE_FRAME_UNSPECIFIED CoordinateFrame = 0
	CoordinateFrame_COORDINATE_FRAME_ECEF        CoordinateFrame = 1
	CoordinateFrame_COORDINATE_FRAME_WGS84       CoordinateFrame = 2
)

// Enum value maps for CoordinateFrame.
var (
	CoordinateFrame_name = map[int32]string{
		0: "COORDINATE_FRAME_UNSPECIFIED",
		1: "COORDINATE_FRAME_ECEF",
		2: "COORDINATE_FRAME_WGS84",
	}
	CoordinateFrame_value = map[string]int32{
		"COORDINATE_FRAME_UNSPECIFIED": 0,
		"COORDINATE_FRAME_ECEF":        1,
		"COORDINATE_FRAME_WGS84":       2,
	}
)

func (x CoordinateFrame) Enum() *CoordinateFrame {
	p := new(CoordinateFrame)
	*p = x
	return p
}

func (x CoordinateFrame) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoordinateFrame) Descriptor() protoreflect.EnumDescriptor {
	return file_nmts_v1_proto_types_geophys_coordinates_proto_enumTypes[0].Descriptor()
}

func (CoordinateFrame) Type() protoreflect.EnumType {
	return &file_nmts_v1_proto_types_geophys_coordinates_proto_enumTypes[0]
}

func (x CoordinateFrame) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoordinateFrame.Descriptor instead.
func (CoordinateFrame) EnumDescriptor() ([]byte, []int) {
	return file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescGZIP(), []int{0}
}

var File_nmts_v1_proto_types_geophys_coordinates_proto protoreflect.FileDescriptor

const file_nmts_v1_proto_types_geophys_coordinates_proto_rawDesc = "" +
	"\n" +
	"-nmts/v1/proto/types/geophys/coordinates.proto\x12\x15nmts.v1.types.geophys*j\n" +
	"\x0fCoordinateFrame\x12 \n" +
	"\x1cCOORDINATE_FRAME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COORDINATE_FRAME_ECEF\x10\x01\x12\x1a\n" +
	"\x16COORDINATE_FRAME_WGS84\x10\x02B3Z1aalyria.com/spacetime/nmts/v1/proto/types/geophysb\x06proto3"

var (
	file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescOnce sync.Once
	file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescData []byte
)

func file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescGZIP() []byte {
	file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescOnce.Do(func() {
		file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nmts_v1_proto_types_geophys_coordinates_proto_rawDesc), len(file_nmts_v1_proto_types_geophys_coordinates_proto_rawDesc)))
	})
	return file_nmts_v1_proto_types_geophys_coordinates_proto_rawDescData
}

var file_nmts_v1_proto_types_geophys_coordinates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nmts_v1_proto_types_geophys_coordinates_proto_goTypes = []any{
	(CoordinateFrame)(0), // 0: nmts.v1.types.geophys.CoordinateFrame
}
var file_nmts_v1_proto_types_geophys_coordinates_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nmts_v1_proto_types_geophys_coordinates_proto_init() }
func file_nmts_v1_proto_types_geophys_coordinates_proto_init() {
	if File_nmts_v1_proto_types_geophys_coordinates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nmts_v1_proto_types_geophys_coordinates_proto_rawDesc), len(file_nmts_v1_proto_types_geophys_coordinates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nmts_v1_proto_types_geophys_coordinates_proto_goTypes,
		DependencyIndexes: file_nmts_v1_proto_types_geophys_coordinates_proto_depIdxs,
		EnumInfos:         file_nmts_v1_proto_types_geophys_coordinates_proto_enumTypes,
	}.Build()
	File_nmts_v1_proto_types_geophys_coordinates_proto = out.File
	file_nmts_v1_proto_types_geophys_coordinates_proto_goTypes = nil
	file_nmts_v1_proto_types_geophys_coordinates_proto_depIdxs = nil
}
