// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/common/control_flow.proto

package common

import (
	types "aalyria.com/spacetime/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies add or remove.
type FlowUpdate_Operation int32

const (
	FlowUpdate_UNKNOWN FlowUpdate_Operation = 0
	FlowUpdate_ADD     FlowUpdate_Operation = 1
	FlowUpdate_DELETE  FlowUpdate_Operation = 2
)

// Enum value maps for FlowUpdate_Operation.
var (
	FlowUpdate_Operation_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADD",
		2: "DELETE",
	}
	FlowUpdate_Operation_value = map[string]int32{
		"UNKNOWN": 0,
		"ADD":     1,
		"DELETE":  2,
	}
)

func (x FlowUpdate_Operation) Enum() *FlowUpdate_Operation {
	p := new(FlowUpdate_Operation)
	*p = x
	return p
}

func (x FlowUpdate_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowUpdate_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_control_flow_proto_enumTypes[0].Descriptor()
}

func (FlowUpdate_Operation) Type() protoreflect.EnumType {
	return &file_api_common_control_flow_proto_enumTypes[0]
}

func (x FlowUpdate_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FlowUpdate_Operation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FlowUpdate_Operation(num)
	return nil
}

// Deprecated: Use FlowUpdate_Operation.Descriptor instead.
func (FlowUpdate_Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{0, 0}
}

type FlowRule_ActionBucket_Action_SetField_Field int32

const (
	FlowRule_ActionBucket_Action_SetField_FIELD_UNSPECIFIED FlowRule_ActionBucket_Action_SetField_Field = 0
	FlowRule_ActionBucket_Action_SetField_FIELD_ETH_DST     FlowRule_ActionBucket_Action_SetField_Field = 2
	// Only the MPLS label, does not alter any of the other fields of
	// the Label Stack Entry (RFC 3032 section-2.1).
	FlowRule_ActionBucket_Action_SetField_FIELD_MPLS     FlowRule_ActionBucket_Action_SetField_Field = 3
	FlowRule_ActionBucket_Action_SetField_FIELD_CTAG     FlowRule_ActionBucket_Action_SetField_Field = 4
	FlowRule_ActionBucket_Action_SetField_FIELD_PBB_ITAG FlowRule_ActionBucket_Action_SetField_Field = 5
)

// Enum value maps for FlowRule_ActionBucket_Action_SetField_Field.
var (
	FlowRule_ActionBucket_Action_SetField_Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		2: "FIELD_ETH_DST",
		3: "FIELD_MPLS",
		4: "FIELD_CTAG",
		5: "FIELD_PBB_ITAG",
	}
	FlowRule_ActionBucket_Action_SetField_Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"FIELD_ETH_DST":     2,
		"FIELD_MPLS":        3,
		"FIELD_CTAG":        4,
		"FIELD_PBB_ITAG":    5,
	}
)

func (x FlowRule_ActionBucket_Action_SetField_Field) Enum() *FlowRule_ActionBucket_Action_SetField_Field {
	p := new(FlowRule_ActionBucket_Action_SetField_Field)
	*p = x
	return p
}

func (x FlowRule_ActionBucket_Action_SetField_Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowRule_ActionBucket_Action_SetField_Field) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_control_flow_proto_enumTypes[1].Descriptor()
}

func (FlowRule_ActionBucket_Action_SetField_Field) Type() protoreflect.EnumType {
	return &file_api_common_control_flow_proto_enumTypes[1]
}

func (x FlowRule_ActionBucket_Action_SetField_Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FlowRule_ActionBucket_Action_SetField_Field) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FlowRule_ActionBucket_Action_SetField_Field(num)
	return nil
}

// Deprecated: Use FlowRule_ActionBucket_Action_SetField_Field.Descriptor instead.
func (FlowRule_ActionBucket_Action_SetField_Field) EnumDescriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 0, 0}
}

type FlowRule_ActionBucket_Action_PushHeader_Field int32

const (
	FlowRule_ActionBucket_Action_PushHeader_FIELD_UNSPECIFIED FlowRule_ActionBucket_Action_PushHeader_Field = 0
	FlowRule_ActionBucket_Action_PushHeader_FIELD_MPLS        FlowRule_ActionBucket_Action_PushHeader_Field = 1
	FlowRule_ActionBucket_Action_PushHeader_FIELD_CTAG        FlowRule_ActionBucket_Action_PushHeader_Field = 2
	FlowRule_ActionBucket_Action_PushHeader_FIELD_PBB         FlowRule_ActionBucket_Action_PushHeader_Field = 3
)

// Enum value maps for FlowRule_ActionBucket_Action_PushHeader_Field.
var (
	FlowRule_ActionBucket_Action_PushHeader_Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		1: "FIELD_MPLS",
		2: "FIELD_CTAG",
		3: "FIELD_PBB",
	}
	FlowRule_ActionBucket_Action_PushHeader_Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"FIELD_MPLS":        1,
		"FIELD_CTAG":        2,
		"FIELD_PBB":         3,
	}
)

func (x FlowRule_ActionBucket_Action_PushHeader_Field) Enum() *FlowRule_ActionBucket_Action_PushHeader_Field {
	p := new(FlowRule_ActionBucket_Action_PushHeader_Field)
	*p = x
	return p
}

func (x FlowRule_ActionBucket_Action_PushHeader_Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowRule_ActionBucket_Action_PushHeader_Field) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_control_flow_proto_enumTypes[2].Descriptor()
}

func (FlowRule_ActionBucket_Action_PushHeader_Field) Type() protoreflect.EnumType {
	return &file_api_common_control_flow_proto_enumTypes[2]
}

func (x FlowRule_ActionBucket_Action_PushHeader_Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FlowRule_ActionBucket_Action_PushHeader_Field) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FlowRule_ActionBucket_Action_PushHeader_Field(num)
	return nil
}

// Deprecated: Use FlowRule_ActionBucket_Action_PushHeader_Field.Descriptor instead.
func (FlowRule_ActionBucket_Action_PushHeader_Field) EnumDescriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 2, 0}
}

type FlowRule_ActionBucket_Action_PopHeader_Field int32

const (
	FlowRule_ActionBucket_Action_PopHeader_FIELD_UNSPECIFIED FlowRule_ActionBucket_Action_PopHeader_Field = 0
	FlowRule_ActionBucket_Action_PopHeader_FIELD_MPLS        FlowRule_ActionBucket_Action_PopHeader_Field = 1
	FlowRule_ActionBucket_Action_PopHeader_FIELD_CTAG        FlowRule_ActionBucket_Action_PopHeader_Field = 2
	FlowRule_ActionBucket_Action_PopHeader_FIELD_PBB         FlowRule_ActionBucket_Action_PopHeader_Field = 3
)

// Enum value maps for FlowRule_ActionBucket_Action_PopHeader_Field.
var (
	FlowRule_ActionBucket_Action_PopHeader_Field_name = map[int32]string{
		0: "FIELD_UNSPECIFIED",
		1: "FIELD_MPLS",
		2: "FIELD_CTAG",
		3: "FIELD_PBB",
	}
	FlowRule_ActionBucket_Action_PopHeader_Field_value = map[string]int32{
		"FIELD_UNSPECIFIED": 0,
		"FIELD_MPLS":        1,
		"FIELD_CTAG":        2,
		"FIELD_PBB":         3,
	}
)

func (x FlowRule_ActionBucket_Action_PopHeader_Field) Enum() *FlowRule_ActionBucket_Action_PopHeader_Field {
	p := new(FlowRule_ActionBucket_Action_PopHeader_Field)
	*p = x
	return p
}

func (x FlowRule_ActionBucket_Action_PopHeader_Field) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowRule_ActionBucket_Action_PopHeader_Field) Descriptor() protoreflect.EnumDescriptor {
	return file_api_common_control_flow_proto_enumTypes[3].Descriptor()
}

func (FlowRule_ActionBucket_Action_PopHeader_Field) Type() protoreflect.EnumType {
	return &file_api_common_control_flow_proto_enumTypes[3]
}

func (x FlowRule_ActionBucket_Action_PopHeader_Field) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FlowRule_ActionBucket_Action_PopHeader_Field) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FlowRule_ActionBucket_Action_PopHeader_Field(num)
	return nil
}

// Deprecated: Use FlowRule_ActionBucket_Action_PopHeader_Field.Descriptor instead.
func (FlowRule_ActionBucket_Action_PopHeader_Field) EnumDescriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 3, 0}
}

// Specifies an update to the state of a switch or router.
type FlowUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A globally unique identifier for this rule.
	FlowRuleId *string               `protobuf:"bytes,1,opt,name=flow_rule_id,json=flowRuleId" json:"flow_rule_id,omitempty"`
	Operation  *FlowUpdate_Operation `protobuf:"varint,2,opt,name=operation,enum=aalyria.spacetime.api.common.FlowUpdate_Operation" json:"operation,omitempty"`
	// The rule and associated actions to which the operation is applied.
	Rule *FlowRule `protobuf:"bytes,3,opt,name=rule" json:"rule,omitempty"`
	// Optional monotonically increasing sequence number, which may jump by more
	// than 1.
	SequenceNumber *int64 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FlowUpdate) Reset() {
	*x = FlowUpdate{}
	mi := &file_api_common_control_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowUpdate) ProtoMessage() {}

func (x *FlowUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowUpdate.ProtoReflect.Descriptor instead.
func (*FlowUpdate) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{0}
}

func (x *FlowUpdate) GetFlowRuleId() string {
	if x != nil && x.FlowRuleId != nil {
		return *x.FlowRuleId
	}
	return ""
}

func (x *FlowUpdate) GetOperation() FlowUpdate_Operation {
	if x != nil && x.Operation != nil {
		return *x.Operation
	}
	return FlowUpdate_UNKNOWN
}

func (x *FlowUpdate) GetRule() *FlowRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *FlowUpdate) GetSequenceNumber() int64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

// Next ID: 8
type FlowRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Classifies packets that match this rule.
	Classifier    *PacketClassifier        `protobuf:"bytes,5,opt,name=classifier" json:"classifier,omitempty"`
	ActionBucket  []*FlowRule_ActionBucket `protobuf:"bytes,4,rep,name=action_bucket,json=actionBucket" json:"action_bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule) Reset() {
	*x = FlowRule{}
	mi := &file_api_common_control_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule) ProtoMessage() {}

func (x *FlowRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule.ProtoReflect.Descriptor instead.
func (*FlowRule) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1}
}

func (x *FlowRule) GetClassifier() *PacketClassifier {
	if x != nil {
		return x.Classifier
	}
	return nil
}

func (x *FlowRule) GetActionBucket() []*FlowRule_ActionBucket {
	if x != nil {
		return x.ActionBucket
	}
	return nil
}

type FlowState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time at which the state was captured by the network element.
	Timestamp *DateTime `protobuf:"bytes,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// A list of all active flow rule ids.
	FlowRuleIds   []string `protobuf:"bytes,3,rep,name=flow_rule_ids,json=flowRuleIds" json:"flow_rule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowState) Reset() {
	*x = FlowState{}
	mi := &file_api_common_control_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowState) ProtoMessage() {}

func (x *FlowState) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowState.ProtoReflect.Descriptor instead.
func (*FlowState) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{2}
}

func (x *FlowState) GetTimestamp() *DateTime {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FlowState) GetFlowRuleIds() []string {
	if x != nil {
		return x.FlowRuleIds
	}
	return nil
}

// Specifies one or more groups of actions to take on matched packets.
// Actions are enacted sequentially within an action bucket.  For example,
// if a packet needs to be copied and forwarded out multiple interfaces on
// the same network node, action buckets may be defined where each bucket
// consists of two sequential actions: (1) setting the destination MAC
// address, and (2) forwarding the packet out of a specified port.
type FlowRule_ActionBucket struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Action        []*FlowRule_ActionBucket_Action `protobuf:"bytes,1,rep,name=action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule_ActionBucket) Reset() {
	*x = FlowRule_ActionBucket{}
	mi := &file_api_common_control_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule_ActionBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule_ActionBucket) ProtoMessage() {}

func (x *FlowRule_ActionBucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule_ActionBucket.ProtoReflect.Descriptor instead.
func (*FlowRule_ActionBucket) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FlowRule_ActionBucket) GetAction() []*FlowRule_ActionBucket_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type FlowRule_ActionBucket_Action struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ActionType:
	//
	//	*FlowRule_ActionBucket_Action_SetField_
	//	*FlowRule_ActionBucket_Action_Forward_
	//	*FlowRule_ActionBucket_Action_PushHeader_
	//	*FlowRule_ActionBucket_Action_PopHeader_
	ActionType    isFlowRule_ActionBucket_Action_ActionType `protobuf_oneof:"action_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule_ActionBucket_Action) Reset() {
	*x = FlowRule_ActionBucket_Action{}
	mi := &file_api_common_control_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule_ActionBucket_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule_ActionBucket_Action) ProtoMessage() {}

func (x *FlowRule_ActionBucket_Action) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule_ActionBucket_Action.ProtoReflect.Descriptor instead.
func (*FlowRule_ActionBucket_Action) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *FlowRule_ActionBucket_Action) GetActionType() isFlowRule_ActionBucket_Action_ActionType {
	if x != nil {
		return x.ActionType
	}
	return nil
}

func (x *FlowRule_ActionBucket_Action) GetSetField() *FlowRule_ActionBucket_Action_SetField {
	if x != nil {
		if x, ok := x.ActionType.(*FlowRule_ActionBucket_Action_SetField_); ok {
			return x.SetField
		}
	}
	return nil
}

func (x *FlowRule_ActionBucket_Action) GetForward() *FlowRule_ActionBucket_Action_Forward {
	if x != nil {
		if x, ok := x.ActionType.(*FlowRule_ActionBucket_Action_Forward_); ok {
			return x.Forward
		}
	}
	return nil
}

func (x *FlowRule_ActionBucket_Action) GetPushHeader() *FlowRule_ActionBucket_Action_PushHeader {
	if x != nil {
		if x, ok := x.ActionType.(*FlowRule_ActionBucket_Action_PushHeader_); ok {
			return x.PushHeader
		}
	}
	return nil
}

func (x *FlowRule_ActionBucket_Action) GetPopHeader() *FlowRule_ActionBucket_Action_PopHeader {
	if x != nil {
		if x, ok := x.ActionType.(*FlowRule_ActionBucket_Action_PopHeader_); ok {
			return x.PopHeader
		}
	}
	return nil
}

type isFlowRule_ActionBucket_Action_ActionType interface {
	isFlowRule_ActionBucket_Action_ActionType()
}

type FlowRule_ActionBucket_Action_SetField_ struct {
	SetField *FlowRule_ActionBucket_Action_SetField `protobuf:"bytes,1,opt,name=set_field,json=setField,oneof"`
}

type FlowRule_ActionBucket_Action_Forward_ struct {
	Forward *FlowRule_ActionBucket_Action_Forward `protobuf:"bytes,2,opt,name=forward,oneof"`
}

type FlowRule_ActionBucket_Action_PushHeader_ struct {
	PushHeader *FlowRule_ActionBucket_Action_PushHeader `protobuf:"bytes,3,opt,name=push_header,json=pushHeader,oneof"`
}

type FlowRule_ActionBucket_Action_PopHeader_ struct {
	PopHeader *FlowRule_ActionBucket_Action_PopHeader `protobuf:"bytes,4,opt,name=pop_header,json=popHeader,oneof"`
}

func (*FlowRule_ActionBucket_Action_SetField_) isFlowRule_ActionBucket_Action_ActionType() {}

func (*FlowRule_ActionBucket_Action_Forward_) isFlowRule_ActionBucket_Action_ActionType() {}

func (*FlowRule_ActionBucket_Action_PushHeader_) isFlowRule_ActionBucket_Action_ActionType() {}

func (*FlowRule_ActionBucket_Action_PopHeader_) isFlowRule_ActionBucket_Action_ActionType() {}

type FlowRule_ActionBucket_Action_SetField struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Field         *FlowRule_ActionBucket_Action_SetField_Field `protobuf:"varint,1,opt,name=field,enum=aalyria.spacetime.api.common.FlowRule_ActionBucket_Action_SetField_Field" json:"field,omitempty"`
	ValueAscii    *string                                      `protobuf:"bytes,3,opt,name=value_ascii,json=valueAscii" json:"value_ascii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule_ActionBucket_Action_SetField) Reset() {
	*x = FlowRule_ActionBucket_Action_SetField{}
	mi := &file_api_common_control_flow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule_ActionBucket_Action_SetField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule_ActionBucket_Action_SetField) ProtoMessage() {}

func (x *FlowRule_ActionBucket_Action_SetField) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule_ActionBucket_Action_SetField.ProtoReflect.Descriptor instead.
func (*FlowRule_ActionBucket_Action_SetField) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

func (x *FlowRule_ActionBucket_Action_SetField) GetField() FlowRule_ActionBucket_Action_SetField_Field {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return FlowRule_ActionBucket_Action_SetField_FIELD_UNSPECIFIED
}

func (x *FlowRule_ActionBucket_Action_SetField) GetValueAscii() string {
	if x != nil && x.ValueAscii != nil {
		return *x.ValueAscii
	}
	return ""
}

// Forward specifies details of the forwarding action to be configured
type FlowRule_ActionBucket_Action_Forward struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// out_interface_id specifies the outbound interface_id over which to
	// forward traffic. This interface_id is the node-unique identifier
	// specified in NetworkNode.
	OutInterfaceId *string `protobuf:"bytes,1,opt,name=out_interface_id,json=outInterfaceId" json:"out_interface_id,omitempty"`
	// next_hop_ip (sometimes known as gateway IP) to direct traffic to.
	// May be IPv4 or IPv6.
	NextHopIp     *string `protobuf:"bytes,2,opt,name=next_hop_ip,json=nextHopIp" json:"next_hop_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule_ActionBucket_Action_Forward) Reset() {
	*x = FlowRule_ActionBucket_Action_Forward{}
	mi := &file_api_common_control_flow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule_ActionBucket_Action_Forward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule_ActionBucket_Action_Forward) ProtoMessage() {}

func (x *FlowRule_ActionBucket_Action_Forward) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule_ActionBucket_Action_Forward.ProtoReflect.Descriptor instead.
func (*FlowRule_ActionBucket_Action_Forward) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 1}
}

func (x *FlowRule_ActionBucket_Action_Forward) GetOutInterfaceId() string {
	if x != nil && x.OutInterfaceId != nil {
		return *x.OutInterfaceId
	}
	return ""
}

func (x *FlowRule_ActionBucket_Action_Forward) GetNextHopIp() string {
	if x != nil && x.NextHopIp != nil {
		return *x.NextHopIp
	}
	return ""
}

// Vis. OpenFlow Switch Specification v1.5.1 S5.8, multiple
// PushHeader/SetField actions can be enacted in a list for richer MPLS
// stack manipulation or Ethernet VLAN/PBB tagging/encapsulation
// operations.
//
// As per the OpenFlow Switch Specification, "[t]he Push tag actions
// always insert a new tag header in the outermost valid location for
// that tag, as defined by the specifications governing that tag."
type FlowRule_ActionBucket_Action_PushHeader struct {
	state protoimpl.MessageState                         `protogen:"open.v1"`
	Field *FlowRule_ActionBucket_Action_PushHeader_Field `protobuf:"varint,1,opt,name=field,enum=aalyria.spacetime.api.common.FlowRule_ActionBucket_Action_PushHeader_Field" json:"field,omitempty"`
	// EtherType is important for field types that have multiple possible
	// EtherTypes values, e.g. VLAN C-TAG vs S-TAG or MPLS downstream vs.
	// "upstream" -assigned.
	EtherType     *types.EtherType `protobuf:"bytes,2,opt,name=ether_type,json=etherType" json:"ether_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule_ActionBucket_Action_PushHeader) Reset() {
	*x = FlowRule_ActionBucket_Action_PushHeader{}
	mi := &file_api_common_control_flow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule_ActionBucket_Action_PushHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule_ActionBucket_Action_PushHeader) ProtoMessage() {}

func (x *FlowRule_ActionBucket_Action_PushHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule_ActionBucket_Action_PushHeader.ProtoReflect.Descriptor instead.
func (*FlowRule_ActionBucket_Action_PushHeader) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 2}
}

func (x *FlowRule_ActionBucket_Action_PushHeader) GetField() FlowRule_ActionBucket_Action_PushHeader_Field {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return FlowRule_ActionBucket_Action_PushHeader_FIELD_UNSPECIFIED
}

func (x *FlowRule_ActionBucket_Action_PushHeader) GetEtherType() *types.EtherType {
	if x != nil {
		return x.EtherType
	}
	return nil
}

type FlowRule_ActionBucket_Action_PopHeader struct {
	state protoimpl.MessageState                        `protogen:"open.v1"`
	Field *FlowRule_ActionBucket_Action_PopHeader_Field `protobuf:"varint,1,opt,name=field,enum=aalyria.spacetime.api.common.FlowRule_ActionBucket_Action_PopHeader_Field" json:"field,omitempty"`
	// As per the OpenFlow Switch Specification, "[t]he Ethertype is used
	// as the Ethertype for the resulting packet", e.g. when popping the
	// last MPLS label stack entry in a stack.
	EtherType     *types.EtherType `protobuf:"bytes,2,opt,name=ether_type,json=etherType" json:"ether_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowRule_ActionBucket_Action_PopHeader) Reset() {
	*x = FlowRule_ActionBucket_Action_PopHeader{}
	mi := &file_api_common_control_flow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowRule_ActionBucket_Action_PopHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowRule_ActionBucket_Action_PopHeader) ProtoMessage() {}

func (x *FlowRule_ActionBucket_Action_PopHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_control_flow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowRule_ActionBucket_Action_PopHeader.ProtoReflect.Descriptor instead.
func (*FlowRule_ActionBucket_Action_PopHeader) Descriptor() ([]byte, []int) {
	return file_api_common_control_flow_proto_rawDescGZIP(), []int{1, 0, 0, 3}
}

func (x *FlowRule_ActionBucket_Action_PopHeader) GetField() FlowRule_ActionBucket_Action_PopHeader_Field {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return FlowRule_ActionBucket_Action_PopHeader_FIELD_UNSPECIFIED
}

func (x *FlowRule_ActionBucket_Action_PopHeader) GetEtherType() *types.EtherType {
	if x != nil {
		return x.EtherType
	}
	return nil
}

var File_api_common_control_flow_proto protoreflect.FileDescriptor

const file_api_common_control_flow_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/common/control_flow.proto\x12\x1caalyria.spacetime.api.common\x1a\x18api/common/network.proto\x1a\x15api/common/time.proto\x1a\x18api/types/ethernet.proto\"\x94\x02\n" +
	"\n" +
	"FlowUpdate\x12 \n" +
	"\fflow_rule_id\x18\x01 \x01(\tR\n" +
	"flowRuleId\x12P\n" +
	"\toperation\x18\x02 \x01(\x0e22.aalyria.spacetime.api.common.FlowUpdate.OperationR\toperation\x12:\n" +
	"\x04rule\x18\x03 \x01(\v2&.aalyria.spacetime.api.common.FlowRuleR\x04rule\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\"-\n" +
	"\tOperation\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ADD\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"\xcb\f\n" +
	"\bFlowRule\x12N\n" +
	"\n" +
	"classifier\x18\x05 \x01(\v2..aalyria.spacetime.api.common.PacketClassifierR\n" +
	"classifier\x12X\n" +
	"\raction_bucket\x18\x04 \x03(\v23.aalyria.spacetime.api.common.FlowRule.ActionBucketR\factionBucket\x1a\x84\v\n" +
	"\fActionBucket\x12R\n" +
	"\x06action\x18\x01 \x03(\v2:.aalyria.spacetime.api.common.FlowRule.ActionBucket.ActionR\x06action\x1a\x9f\n" +
	"\n" +
	"\x06Action\x12b\n" +
	"\tset_field\x18\x01 \x01(\v2C.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetFieldH\x00R\bsetField\x12^\n" +
	"\aforward\x18\x02 \x01(\v2B.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.ForwardH\x00R\aforward\x12h\n" +
	"\vpush_header\x18\x03 \x01(\v2E.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeaderH\x00R\n" +
	"pushHeader\x12e\n" +
	"\n" +
	"pop_header\x18\x04 \x01(\v2D.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeaderH\x00R\tpopHeader\x1a\x83\x02\n" +
	"\bSetField\x12_\n" +
	"\x05field\x18\x01 \x01(\x0e2I.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetField.FieldR\x05field\x12\x1f\n" +
	"\vvalue_ascii\x18\x03 \x01(\tR\n" +
	"valueAscii\"e\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rFIELD_ETH_DST\x10\x02\x12\x0e\n" +
	"\n" +
	"FIELD_MPLS\x10\x03\x12\x0e\n" +
	"\n" +
	"FIELD_CTAG\x10\x04\x12\x12\n" +
	"\x0eFIELD_PBB_ITAG\x10\x05J\x04\b\x02\x10\x03J\b\b\x04\x10\x80\x80\x80\x80\x02\x1aS\n" +
	"\aForward\x12(\n" +
	"\x10out_interface_id\x18\x01 \x01(\tR\x0eoutInterfaceId\x12\x1e\n" +
	"\vnext_hop_ip\x18\x02 \x01(\tR\tnextHopIp\x1a\x85\x02\n" +
	"\n" +
	"PushHeader\x12a\n" +
	"\x05field\x18\x01 \x01(\x0e2K.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader.FieldR\x05field\x12E\n" +
	"\n" +
	"ether_type\x18\x02 \x01(\v2&.aalyria.spacetime.api.types.EtherTypeR\tetherType\"M\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FIELD_MPLS\x10\x01\x12\x0e\n" +
	"\n" +
	"FIELD_CTAG\x10\x02\x12\r\n" +
	"\tFIELD_PBB\x10\x03\x1a\x83\x02\n" +
	"\tPopHeader\x12`\n" +
	"\x05field\x18\x01 \x01(\x0e2J.aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader.FieldR\x05field\x12E\n" +
	"\n" +
	"ether_type\x18\x02 \x01(\v2&.aalyria.spacetime.api.types.EtherTypeR\tetherType\"M\n" +
	"\x05Field\x12\x15\n" +
	"\x11FIELD_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"FIELD_MPLS\x10\x01\x12\x0e\n" +
	"\n" +
	"FIELD_CTAG\x10\x02\x12\r\n" +
	"\tFIELD_PBB\x10\x03B\r\n" +
	"\vaction_typeJ\b\b\x05\x10\x80\x80\x80\x80\x02J\x04\b\x01\x10\x04J\b\b\b\x10\x80\x80\x80\x80\x02\"\x85\x01\n" +
	"\tFlowState\x12D\n" +
	"\ttimestamp\x18\x02 \x01(\v2&.aalyria.spacetime.api.common.DateTimeR\ttimestamp\x12\"\n" +
	"\rflow_rule_ids\x18\x03 \x03(\tR\vflowRuleIdsJ\x04\b\x01\x10\x02J\b\b\x04\x10\x80\x80\x80\x80\x02BD\n" +
	" com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common"

var (
	file_api_common_control_flow_proto_rawDescOnce sync.Once
	file_api_common_control_flow_proto_rawDescData []byte
)

func file_api_common_control_flow_proto_rawDescGZIP() []byte {
	file_api_common_control_flow_proto_rawDescOnce.Do(func() {
		file_api_common_control_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_control_flow_proto_rawDesc), len(file_api_common_control_flow_proto_rawDesc)))
	})
	return file_api_common_control_flow_proto_rawDescData
}

var file_api_common_control_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_common_control_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_common_control_flow_proto_goTypes = []any{
	(FlowUpdate_Operation)(0),                          // 0: aalyria.spacetime.api.common.FlowUpdate.Operation
	(FlowRule_ActionBucket_Action_SetField_Field)(0),   // 1: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetField.Field
	(FlowRule_ActionBucket_Action_PushHeader_Field)(0), // 2: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader.Field
	(FlowRule_ActionBucket_Action_PopHeader_Field)(0),  // 3: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader.Field
	(*FlowUpdate)(nil),                                 // 4: aalyria.spacetime.api.common.FlowUpdate
	(*FlowRule)(nil),                                   // 5: aalyria.spacetime.api.common.FlowRule
	(*FlowState)(nil),                                  // 6: aalyria.spacetime.api.common.FlowState
	(*FlowRule_ActionBucket)(nil),                      // 7: aalyria.spacetime.api.common.FlowRule.ActionBucket
	(*FlowRule_ActionBucket_Action)(nil),               // 8: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action
	(*FlowRule_ActionBucket_Action_SetField)(nil),      // 9: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetField
	(*FlowRule_ActionBucket_Action_Forward)(nil),       // 10: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.Forward
	(*FlowRule_ActionBucket_Action_PushHeader)(nil),    // 11: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader
	(*FlowRule_ActionBucket_Action_PopHeader)(nil),     // 12: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader
	(*PacketClassifier)(nil),                           // 13: aalyria.spacetime.api.common.PacketClassifier
	(*DateTime)(nil),                                   // 14: aalyria.spacetime.api.common.DateTime
	(*types.EtherType)(nil),                            // 15: aalyria.spacetime.api.types.EtherType
}
var file_api_common_control_flow_proto_depIdxs = []int32{
	0,  // 0: aalyria.spacetime.api.common.FlowUpdate.operation:type_name -> aalyria.spacetime.api.common.FlowUpdate.Operation
	5,  // 1: aalyria.spacetime.api.common.FlowUpdate.rule:type_name -> aalyria.spacetime.api.common.FlowRule
	13, // 2: aalyria.spacetime.api.common.FlowRule.classifier:type_name -> aalyria.spacetime.api.common.PacketClassifier
	7,  // 3: aalyria.spacetime.api.common.FlowRule.action_bucket:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket
	14, // 4: aalyria.spacetime.api.common.FlowState.timestamp:type_name -> aalyria.spacetime.api.common.DateTime
	8,  // 5: aalyria.spacetime.api.common.FlowRule.ActionBucket.action:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action
	9,  // 6: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.set_field:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetField
	10, // 7: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.forward:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.Forward
	11, // 8: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.push_header:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader
	12, // 9: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.pop_header:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader
	1,  // 10: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetField.field:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.SetField.Field
	2,  // 11: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader.field:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader.Field
	15, // 12: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PushHeader.ether_type:type_name -> aalyria.spacetime.api.types.EtherType
	3,  // 13: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader.field:type_name -> aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader.Field
	15, // 14: aalyria.spacetime.api.common.FlowRule.ActionBucket.Action.PopHeader.ether_type:type_name -> aalyria.spacetime.api.types.EtherType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_common_control_flow_proto_init() }
func file_api_common_control_flow_proto_init() {
	if File_api_common_control_flow_proto != nil {
		return
	}
	file_api_common_network_proto_init()
	file_api_common_time_proto_init()
	file_api_common_control_flow_proto_msgTypes[4].OneofWrappers = []any{
		(*FlowRule_ActionBucket_Action_SetField_)(nil),
		(*FlowRule_ActionBucket_Action_Forward_)(nil),
		(*FlowRule_ActionBucket_Action_PushHeader_)(nil),
		(*FlowRule_ActionBucket_Action_PopHeader_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_control_flow_proto_rawDesc), len(file_api_common_control_flow_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_control_flow_proto_goTypes,
		DependencyIndexes: file_api_common_control_flow_proto_depIdxs,
		EnumInfos:         file_api_common_control_flow_proto_enumTypes,
		MessageInfos:      file_api_common_control_flow_proto_msgTypes,
	}.Build()
	File_api_common_control_flow_proto = out.File
	file_api_common_control_flow_proto_goTypes = nil
	file_api_common_control_flow_proto_depIdxs = nil
}
