// Copyright (c) Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/common/field_mask.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FieldMask is the same exact message as google.protobuf.FieldMask. It should
// be wire compatible. The only difference is that the regular
// google.protobuf.FieldMask has special support in the common Protobuf JSON
// serialization and deserialization routines. Field masks that would
// structurally be represented as ["a.b.c", "a.b.d"] are transformed into
// "a.b.c,a.b.d". This one doesn't. This is important because the special
// transformation routines also verify correctness of the field masks. This
// property of correctness includes components of the field mask being
// camelCase, which disagrees with the map key functionality described in
// user-defined keys, we can't guarantee this property.
//
// Reference:
// * https://github.com/golang/protobuf/issues/1683
// * https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/field_mask.proto#L43
// * https://github.com/protocolbuffers/protobuf/issues/12524
//
// This type should be removed once the common Protobuf libraries support the
// AIP-recommended version of field masks.
type FieldMask struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The set of field mask paths.
	Paths         []string `protobuf:"bytes,1,rep,name=paths" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMask) Reset() {
	*x = FieldMask{}
	mi := &file_api_common_field_mask_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMask) ProtoMessage() {}

func (x *FieldMask) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_field_mask_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMask.ProtoReflect.Descriptor instead.
func (*FieldMask) Descriptor() ([]byte, []int) {
	return file_api_common_field_mask_proto_rawDescGZIP(), []int{0}
}

func (x *FieldMask) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_api_common_field_mask_proto protoreflect.FileDescriptor

const file_api_common_field_mask_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/common/field_mask.proto\x12\x1caalyria.spacetime.api.common\"!\n" +
	"\tFieldMask\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05pathsBD\n" +
	" com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common"

var (
	file_api_common_field_mask_proto_rawDescOnce sync.Once
	file_api_common_field_mask_proto_rawDescData []byte
)

func file_api_common_field_mask_proto_rawDescGZIP() []byte {
	file_api_common_field_mask_proto_rawDescOnce.Do(func() {
		file_api_common_field_mask_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_field_mask_proto_rawDesc), len(file_api_common_field_mask_proto_rawDesc)))
	})
	return file_api_common_field_mask_proto_rawDescData
}

var file_api_common_field_mask_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_common_field_mask_proto_goTypes = []any{
	(*FieldMask)(nil), // 0: aalyria.spacetime.api.common.FieldMask
}
var file_api_common_field_mask_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_common_field_mask_proto_init() }
func file_api_common_field_mask_proto_init() {
	if File_api_common_field_mask_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_field_mask_proto_rawDesc), len(file_api_common_field_mask_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_field_mask_proto_goTypes,
		DependencyIndexes: file_api_common_field_mask_proto_depIdxs,
		MessageInfos:      file_api_common_field_mask_proto_msgTypes,
	}.Build()
	File_api_common_field_mask_proto = out.File
	file_api_common_field_mask_proto_goTypes = nil
	file_api_common_field_mask_proto_depIdxs = nil
}
