// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/common/time.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TODO: Migrate to Timestamp.
type DateTime struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 'Smeared' microseconds since the Unix epoch. See
	// https://developers.google.com/time/smear.
	UnixTimeUsec  *int64   `protobuf:"varint,1,opt,name=unix_time_usec,json=unixTimeUsec" json:"unix_time_usec,omitempty"`
	GpsTime       *GpsTime `protobuf:"bytes,2,opt,name=gps_time,json=gpsTime" json:"gps_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DateTime) Reset() {
	*x = DateTime{}
	mi := &file_api_common_time_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DateTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DateTime) ProtoMessage() {}

func (x *DateTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_time_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DateTime.ProtoReflect.Descriptor instead.
func (*DateTime) Descriptor() ([]byte, []int) {
	return file_api_common_time_proto_rawDescGZIP(), []int{0}
}

func (x *DateTime) GetUnixTimeUsec() int64 {
	if x != nil && x.UnixTimeUsec != nil {
		return *x.UnixTimeUsec
	}
	return 0
}

func (x *DateTime) GetGpsTime() *GpsTime {
	if x != nil {
		return x.GpsTime
	}
	return nil
}

// TODO: Migrate to Timestamp.
type GpsTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    *int32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber" json:"week_number,omitempty"`
	SecondOfWeek  *int32                 `protobuf:"varint,2,opt,name=second_of_week,json=secondOfWeek" json:"second_of_week,omitempty"`
	Usec          *int32                 `protobuf:"varint,3,opt,name=usec" json:"usec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpsTime) Reset() {
	*x = GpsTime{}
	mi := &file_api_common_time_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpsTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpsTime) ProtoMessage() {}

func (x *GpsTime) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_time_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpsTime.ProtoReflect.Descriptor instead.
func (*GpsTime) Descriptor() ([]byte, []int) {
	return file_api_common_time_proto_rawDescGZIP(), []int{1}
}

func (x *GpsTime) GetWeekNumber() int32 {
	if x != nil && x.WeekNumber != nil {
		return *x.WeekNumber
	}
	return 0
}

func (x *GpsTime) GetSecondOfWeek() int32 {
	if x != nil && x.SecondOfWeek != nil {
		return *x.SecondOfWeek
	}
	return 0
}

func (x *GpsTime) GetUsec() int32 {
	if x != nil && x.Usec != nil {
		return *x.Usec
	}
	return 0
}

// TODO: Migrate to Duration.
type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Microseconds  *int64                 `protobuf:"varint,1,req,name=microseconds" json:"microseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_api_common_time_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_time_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_api_common_time_proto_rawDescGZIP(), []int{2}
}

func (x *Duration) GetMicroseconds() int64 {
	if x != nil && x.Microseconds != nil {
		return *x.Microseconds
	}
	return 0
}

// Time intervals are half-closed, [start_time, end_time)
// If the start and/or end time are not included, the time interval should
// be interpreted as extending to infinity in that timeline direction.
type TimeInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     *DateTime              `protobuf:"bytes,1,opt,name=start_time,json=startTime" json:"start_time,omitempty"` // closed
	EndTime       *DateTime              `protobuf:"bytes,2,opt,name=end_time,json=endTime" json:"end_time,omitempty"`       // open
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeInterval) Reset() {
	*x = TimeInterval{}
	mi := &file_api_common_time_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeInterval) ProtoMessage() {}

func (x *TimeInterval) ProtoReflect() protoreflect.Message {
	mi := &file_api_common_time_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeInterval.ProtoReflect.Descriptor instead.
func (*TimeInterval) Descriptor() ([]byte, []int) {
	return file_api_common_time_proto_rawDescGZIP(), []int{3}
}

func (x *TimeInterval) GetStartTime() *DateTime {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TimeInterval) GetEndTime() *DateTime {
	if x != nil {
		return x.EndTime
	}
	return nil
}

var File_api_common_time_proto protoreflect.FileDescriptor

const file_api_common_time_proto_rawDesc = "" +
	"\n" +
	"\x15api/common/time.proto\x12\x1caalyria.spacetime.api.common\"r\n" +
	"\bDateTime\x12$\n" +
	"\x0eunix_time_usec\x18\x01 \x01(\x03R\funixTimeUsec\x12@\n" +
	"\bgps_time\x18\x02 \x01(\v2%.aalyria.spacetime.api.common.GpsTimeR\agpsTime\"d\n" +
	"\aGpsTime\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\x05R\n" +
	"weekNumber\x12$\n" +
	"\x0esecond_of_week\x18\x02 \x01(\x05R\fsecondOfWeek\x12\x12\n" +
	"\x04usec\x18\x03 \x01(\x05R\x04usec\".\n" +
	"\bDuration\x12\"\n" +
	"\fmicroseconds\x18\x01 \x02(\x03R\fmicroseconds\"\x98\x01\n" +
	"\fTimeInterval\x12E\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2&.aalyria.spacetime.api.common.DateTimeR\tstartTime\x12A\n" +
	"\bend_time\x18\x02 \x01(\v2&.aalyria.spacetime.api.common.DateTimeR\aendTimeBD\n" +
	" com.aalyria.spacetime.api.commonZ aalyria.com/spacetime/api/common"

var (
	file_api_common_time_proto_rawDescOnce sync.Once
	file_api_common_time_proto_rawDescData []byte
)

func file_api_common_time_proto_rawDescGZIP() []byte {
	file_api_common_time_proto_rawDescOnce.Do(func() {
		file_api_common_time_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_common_time_proto_rawDesc), len(file_api_common_time_proto_rawDesc)))
	})
	return file_api_common_time_proto_rawDescData
}

var file_api_common_time_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_common_time_proto_goTypes = []any{
	(*DateTime)(nil),     // 0: aalyria.spacetime.api.common.DateTime
	(*GpsTime)(nil),      // 1: aalyria.spacetime.api.common.GpsTime
	(*Duration)(nil),     // 2: aalyria.spacetime.api.common.Duration
	(*TimeInterval)(nil), // 3: aalyria.spacetime.api.common.TimeInterval
}
var file_api_common_time_proto_depIdxs = []int32{
	1, // 0: aalyria.spacetime.api.common.DateTime.gps_time:type_name -> aalyria.spacetime.api.common.GpsTime
	0, // 1: aalyria.spacetime.api.common.TimeInterval.start_time:type_name -> aalyria.spacetime.api.common.DateTime
	0, // 2: aalyria.spacetime.api.common.TimeInterval.end_time:type_name -> aalyria.spacetime.api.common.DateTime
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_common_time_proto_init() }
func file_api_common_time_proto_init() {
	if File_api_common_time_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_common_time_proto_rawDesc), len(file_api_common_time_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_common_time_proto_goTypes,
		DependencyIndexes: file_api_common_time_proto_depIdxs,
		MessageInfos:      file_api_common_time_proto_msgTypes,
	}.Build()
	File_api_common_time_proto = out.File
	file_api_common_time_proto_goTypes = nil
	file_api_common_time_proto_depIdxs = nil
}
