// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/nbi/v1alpha/network_node_service.proto

package v1alpha

import (
	resources "aalyria.com/spacetime/api/nbi/v1alpha/resources"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkNodeService_CreateNode_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.NetworkNodeService/CreateNode"
	NetworkNodeService_GetNode_FullMethodName    = "/aalyria.spacetime.api.nbi.v1alpha.NetworkNodeService/GetNode"
	NetworkNodeService_ListNodes_FullMethodName  = "/aalyria.spacetime.api.nbi.v1alpha.NetworkNodeService/ListNodes"
	NetworkNodeService_UpdateNode_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.NetworkNodeService/UpdateNode"
	NetworkNodeService_DeleteNode_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.NetworkNodeService/DeleteNode"
)

// NetworkNodeServiceClient is the client API for NetworkNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service to manage NetworkNode resources.
type NetworkNodeServiceClient interface {
	CreateNode(ctx context.Context, in *resources.NetworkNode, opts ...grpc.CallOption) (*resources.NetworkNode, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*resources.NetworkNode, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*resources.NetworkNode, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type networkNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkNodeServiceClient(cc grpc.ClientConnInterface) NetworkNodeServiceClient {
	return &networkNodeServiceClient{cc}
}

func (c *networkNodeServiceClient) CreateNode(ctx context.Context, in *resources.NetworkNode, opts ...grpc.CallOption) (*resources.NetworkNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.NetworkNode)
	err := c.cc.Invoke(ctx, NetworkNodeService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkNodeServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*resources.NetworkNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.NetworkNode)
	err := c.cc.Invoke(ctx, NetworkNodeService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkNodeServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, NetworkNodeService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkNodeServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*resources.NetworkNode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.NetworkNode)
	err := c.cc.Invoke(ctx, NetworkNodeService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkNodeServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetworkNodeService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkNodeServiceServer is the server API for NetworkNodeService service.
// All implementations must embed UnimplementedNetworkNodeServiceServer
// for forward compatibility.
//
// Service to manage NetworkNode resources.
type NetworkNodeServiceServer interface {
	CreateNode(context.Context, *resources.NetworkNode) (*resources.NetworkNode, error)
	GetNode(context.Context, *GetNodeRequest) (*resources.NetworkNode, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*resources.NetworkNode, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNetworkNodeServiceServer()
}

// UnimplementedNetworkNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkNodeServiceServer struct{}

func (UnimplementedNetworkNodeServiceServer) CreateNode(context.Context, *resources.NetworkNode) (*resources.NetworkNode, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedNetworkNodeServiceServer) GetNode(context.Context, *GetNodeRequest) (*resources.NetworkNode, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNetworkNodeServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedNetworkNodeServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*resources.NetworkNode, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedNetworkNodeServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedNetworkNodeServiceServer) mustEmbedUnimplementedNetworkNodeServiceServer() {}
func (UnimplementedNetworkNodeServiceServer) testEmbeddedByValue()                            {}

// UnsafeNetworkNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkNodeServiceServer will
// result in compilation errors.
type UnsafeNetworkNodeServiceServer interface {
	mustEmbedUnimplementedNetworkNodeServiceServer()
}

func RegisterNetworkNodeServiceServer(s grpc.ServiceRegistrar, srv NetworkNodeServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkNodeService_ServiceDesc, srv)
}

func _NetworkNodeService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.NetworkNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkNodeServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkNodeService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkNodeServiceServer).CreateNode(ctx, req.(*resources.NetworkNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkNodeService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkNodeServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkNodeService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkNodeServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkNodeService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkNodeServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkNodeService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkNodeServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkNodeService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkNodeServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkNodeService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkNodeServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkNodeService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkNodeServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkNodeService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkNodeServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkNodeService_ServiceDesc is the grpc.ServiceDesc for NetworkNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aalyria.spacetime.api.nbi.v1alpha.NetworkNodeService",
	HandlerType: (*NetworkNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _NetworkNodeService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _NetworkNodeService_GetNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _NetworkNodeService_ListNodes_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _NetworkNodeService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _NetworkNodeService_DeleteNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nbi/v1alpha/network_node_service.proto",
}
