// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/nbi/v1alpha/network_link_service.proto

package v1alpha

import (
	resources "aalyria.com/spacetime/api/nbi/v1alpha/resources"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkLinkService_CreateLink_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.NetworkLinkService/CreateLink"
	NetworkLinkService_GetLink_FullMethodName    = "/aalyria.spacetime.api.nbi.v1alpha.NetworkLinkService/GetLink"
	NetworkLinkService_ListLinks_FullMethodName  = "/aalyria.spacetime.api.nbi.v1alpha.NetworkLinkService/ListLinks"
	NetworkLinkService_DeleteLink_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.NetworkLinkService/DeleteLink"
)

// NetworkLinkServiceClient is the client API for NetworkLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service to manage NetworkLink resources.
type NetworkLinkServiceClient interface {
	CreateLink(ctx context.Context, in *resources.BidirectionalLink, opts ...grpc.CallOption) (*resources.BidirectionalLink, error)
	GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*resources.BidirectionalLink, error)
	ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error)
	DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type networkLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkLinkServiceClient(cc grpc.ClientConnInterface) NetworkLinkServiceClient {
	return &networkLinkServiceClient{cc}
}

func (c *networkLinkServiceClient) CreateLink(ctx context.Context, in *resources.BidirectionalLink, opts ...grpc.CallOption) (*resources.BidirectionalLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.BidirectionalLink)
	err := c.cc.Invoke(ctx, NetworkLinkService_CreateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkLinkServiceClient) GetLink(ctx context.Context, in *GetLinkRequest, opts ...grpc.CallOption) (*resources.BidirectionalLink, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(resources.BidirectionalLink)
	err := c.cc.Invoke(ctx, NetworkLinkService_GetLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkLinkServiceClient) ListLinks(ctx context.Context, in *ListLinksRequest, opts ...grpc.CallOption) (*ListLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinksResponse)
	err := c.cc.Invoke(ctx, NetworkLinkService_ListLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkLinkServiceClient) DeleteLink(ctx context.Context, in *DeleteLinkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NetworkLinkService_DeleteLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkLinkServiceServer is the server API for NetworkLinkService service.
// All implementations must embed UnimplementedNetworkLinkServiceServer
// for forward compatibility.
//
// Service to manage NetworkLink resources.
type NetworkLinkServiceServer interface {
	CreateLink(context.Context, *resources.BidirectionalLink) (*resources.BidirectionalLink, error)
	GetLink(context.Context, *GetLinkRequest) (*resources.BidirectionalLink, error)
	ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error)
	DeleteLink(context.Context, *DeleteLinkRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedNetworkLinkServiceServer()
}

// UnimplementedNetworkLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkLinkServiceServer struct{}

func (UnimplementedNetworkLinkServiceServer) CreateLink(context.Context, *resources.BidirectionalLink) (*resources.BidirectionalLink, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedNetworkLinkServiceServer) GetLink(context.Context, *GetLinkRequest) (*resources.BidirectionalLink, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedNetworkLinkServiceServer) ListLinks(context.Context, *ListLinksRequest) (*ListLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLinks not implemented")
}
func (UnimplementedNetworkLinkServiceServer) DeleteLink(context.Context, *DeleteLinkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedNetworkLinkServiceServer) mustEmbedUnimplementedNetworkLinkServiceServer() {}
func (UnimplementedNetworkLinkServiceServer) testEmbeddedByValue()                            {}

// UnsafeNetworkLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkLinkServiceServer will
// result in compilation errors.
type UnsafeNetworkLinkServiceServer interface {
	mustEmbedUnimplementedNetworkLinkServiceServer()
}

func RegisterNetworkLinkServiceServer(s grpc.ServiceRegistrar, srv NetworkLinkServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkLinkService_ServiceDesc, srv)
}

func _NetworkLinkService_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(resources.BidirectionalLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkLinkServiceServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkLinkService_CreateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkLinkServiceServer).CreateLink(ctx, req.(*resources.BidirectionalLink))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkLinkService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkLinkServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkLinkService_GetLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkLinkServiceServer).GetLink(ctx, req.(*GetLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkLinkService_ListLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkLinkServiceServer).ListLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkLinkService_ListLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkLinkServiceServer).ListLinks(ctx, req.(*ListLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkLinkService_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkLinkServiceServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkLinkService_DeleteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkLinkServiceServer).DeleteLink(ctx, req.(*DeleteLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkLinkService_ServiceDesc is the grpc.ServiceDesc for NetworkLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aalyria.spacetime.api.nbi.v1alpha.NetworkLinkService",
	HandlerType: (*NetworkLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLink",
			Handler:    _NetworkLinkService_CreateLink_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _NetworkLinkService_GetLink_Handler,
		},
		{
			MethodName: "ListLinks",
			Handler:    _NetworkLinkService_ListLinks_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _NetworkLinkService_DeleteLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nbi/v1alpha/network_link_service.proto",
}
