// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/nbi/v1alpha/platform_service.proto

package v1alpha

import (
	common "aalyria.com/spacetime/api/common"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlatformService_CreatePlatform_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.PlatformService/CreatePlatform"
	PlatformService_GetPlatform_FullMethodName    = "/aalyria.spacetime.api.nbi.v1alpha.PlatformService/GetPlatform"
	PlatformService_ListPlatforms_FullMethodName  = "/aalyria.spacetime.api.nbi.v1alpha.PlatformService/ListPlatforms"
	PlatformService_UpdatePlatform_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.PlatformService/UpdatePlatform"
	PlatformService_DeletePlatform_FullMethodName = "/aalyria.spacetime.api.nbi.v1alpha.PlatformService/DeletePlatform"
)

// PlatformServiceClient is the client API for PlatformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service to manage PlatformDefinition resources.
type PlatformServiceClient interface {
	CreatePlatform(ctx context.Context, in *common.PlatformDefinition, opts ...grpc.CallOption) (*common.PlatformDefinition, error)
	GetPlatform(ctx context.Context, in *GetPlatformRequest, opts ...grpc.CallOption) (*common.PlatformDefinition, error)
	ListPlatforms(ctx context.Context, in *ListPlatformsRequest, opts ...grpc.CallOption) (*ListPlatformsResponse, error)
	UpdatePlatform(ctx context.Context, in *UpdatePlatformRequest, opts ...grpc.CallOption) (*common.PlatformDefinition, error)
	DeletePlatform(ctx context.Context, in *DeletePlatformRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type platformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformServiceClient(cc grpc.ClientConnInterface) PlatformServiceClient {
	return &platformServiceClient{cc}
}

func (c *platformServiceClient) CreatePlatform(ctx context.Context, in *common.PlatformDefinition, opts ...grpc.CallOption) (*common.PlatformDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.PlatformDefinition)
	err := c.cc.Invoke(ctx, PlatformService_CreatePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) GetPlatform(ctx context.Context, in *GetPlatformRequest, opts ...grpc.CallOption) (*common.PlatformDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.PlatformDefinition)
	err := c.cc.Invoke(ctx, PlatformService_GetPlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) ListPlatforms(ctx context.Context, in *ListPlatformsRequest, opts ...grpc.CallOption) (*ListPlatformsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlatformsResponse)
	err := c.cc.Invoke(ctx, PlatformService_ListPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) UpdatePlatform(ctx context.Context, in *UpdatePlatformRequest, opts ...grpc.CallOption) (*common.PlatformDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.PlatformDefinition)
	err := c.cc.Invoke(ctx, PlatformService_UpdatePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformServiceClient) DeletePlatform(ctx context.Context, in *DeletePlatformRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PlatformService_DeletePlatform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformServiceServer is the server API for PlatformService service.
// All implementations must embed UnimplementedPlatformServiceServer
// for forward compatibility.
//
// Service to manage PlatformDefinition resources.
type PlatformServiceServer interface {
	CreatePlatform(context.Context, *common.PlatformDefinition) (*common.PlatformDefinition, error)
	GetPlatform(context.Context, *GetPlatformRequest) (*common.PlatformDefinition, error)
	ListPlatforms(context.Context, *ListPlatformsRequest) (*ListPlatformsResponse, error)
	UpdatePlatform(context.Context, *UpdatePlatformRequest) (*common.PlatformDefinition, error)
	DeletePlatform(context.Context, *DeletePlatformRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPlatformServiceServer()
}

// UnimplementedPlatformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformServiceServer struct{}

func (UnimplementedPlatformServiceServer) CreatePlatform(context.Context, *common.PlatformDefinition) (*common.PlatformDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlatform not implemented")
}
func (UnimplementedPlatformServiceServer) GetPlatform(context.Context, *GetPlatformRequest) (*common.PlatformDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatform not implemented")
}
func (UnimplementedPlatformServiceServer) ListPlatforms(context.Context, *ListPlatformsRequest) (*ListPlatformsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlatforms not implemented")
}
func (UnimplementedPlatformServiceServer) UpdatePlatform(context.Context, *UpdatePlatformRequest) (*common.PlatformDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlatform not implemented")
}
func (UnimplementedPlatformServiceServer) DeletePlatform(context.Context, *DeletePlatformRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePlatform not implemented")
}
func (UnimplementedPlatformServiceServer) mustEmbedUnimplementedPlatformServiceServer() {}
func (UnimplementedPlatformServiceServer) testEmbeddedByValue()                         {}

// UnsafePlatformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformServiceServer will
// result in compilation errors.
type UnsafePlatformServiceServer interface {
	mustEmbedUnimplementedPlatformServiceServer()
}

func RegisterPlatformServiceServer(s grpc.ServiceRegistrar, srv PlatformServiceServer) {
	// If the following call panics, it indicates UnimplementedPlatformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformService_ServiceDesc, srv)
}

func _PlatformService_CreatePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PlatformDefinition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).CreatePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_CreatePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).CreatePlatform(ctx, req.(*common.PlatformDefinition))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_GetPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).GetPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_GetPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).GetPlatform(ctx, req.(*GetPlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_ListPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).ListPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_ListPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).ListPlatforms(ctx, req.(*ListPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_UpdatePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).UpdatePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_UpdatePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).UpdatePlatform(ctx, req.(*UpdatePlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformService_DeletePlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlatformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformServiceServer).DeletePlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformService_DeletePlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformServiceServer).DeletePlatform(ctx, req.(*DeletePlatformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformService_ServiceDesc is the grpc.ServiceDesc for PlatformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aalyria.spacetime.api.nbi.v1alpha.PlatformService",
	HandlerType: (*PlatformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlatform",
			Handler:    _PlatformService_CreatePlatform_Handler,
		},
		{
			MethodName: "GetPlatform",
			Handler:    _PlatformService_GetPlatform_Handler,
		},
		{
			MethodName: "ListPlatforms",
			Handler:    _PlatformService_ListPlatforms_Handler,
		},
		{
			MethodName: "UpdatePlatform",
			Handler:    _PlatformService_UpdatePlatform_Handler,
		},
		{
			MethodName: "DeletePlatform",
			Handler:    _PlatformService_DeletePlatform_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/nbi/v1alpha/platform_service.proto",
}
