// Copyright 2023 Aalyria Technologies, Inc., and its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/nbi/v1alpha/signal_propagation.proto

package v1alpha

import (
	resources "aalyria.com/spacetime/api/nbi/v1alpha/resources"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalPropagationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the transmitting transceiver model.
	TransmitterModel *resources.TransceiverProvider `protobuf:"bytes,1,opt,name=transmitter_model,json=transmitterModel" json:"transmitter_model,omitempty"`
	// This string should correspond to the `id` field of an
	// Entity message that contains a aalyria.spacetime.api.common.BandProfile
	// message.
	BandProfileId *string `protobuf:"bytes,2,opt,name=band_profile_id,json=bandProfileId" json:"band_profile_id,omitempty"`
	// Identifies the time-dynamic target of a steerable beam.
	// This field may only be omitted if the beam is fixed / non-steerable.
	// If this field is omitted, the `accessibility` field in each
	// `access_interval` within the SignalPropagationResponse will be
	// omitted, and the access interval will match the request interval.
	// Only coverage calculations will be completed. The link budget from
	// the transmitter to target will not be computed.
	Target *resources.TransceiverProvider `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	// This field is useful for interference analysis.
	// Omitting this field causes 'coverage' to be omitted from the response.
	Coverage *resources.CoordinateArray `protobuf:"bytes,4,opt,name=coverage" json:"coverage,omitempty"`
	// Types that are valid to be assigned to AnalysisTime:
	//
	//	*SignalPropagationRequest_AnalysisInterval
	//	*SignalPropagationRequest_AnalysisInstant
	AnalysisTime isSignalPropagationRequest_AnalysisTime `protobuf_oneof:"analysis_time"`
	// Sets the analysis step size and the temporal resolution of the response.
	// This step size determines the rate at which constraints of link
	// accessibility (such as the link being obstructed by terrain) are
	// sampled with respect to time.
	StepSize *durationpb.Duration `protobuf:"bytes,7,opt,name=step_size,json=stepSize" json:"step_size,omitempty"`
	// Sets the analysis step size for spatial propagation metrics.
	// This step size determines the rate at which propagation loss
	// metrics are sampled in order to compute the access intervals in
	// the response. If the step is set to 0, then spatial propagation
	// will not be calculated.
	SpatialPropagationStepSize *durationpb.Duration `protobuf:"bytes,9,opt,name=spatial_propagation_step_size,json=spatialPropagationStepSize" json:"spatial_propagation_step_size,omitempty"`
	// If explain_inaccessibility is true, the server will spend additional
	// computational time determining the specific set of access constraints
	// that were not satisfied and including these reasons in the response.
	// Set this to false to optimize performance.
	ExplainInaccessibility *bool `protobuf:"varint,8,opt,name=explain_inaccessibility,json=explainInaccessibility" json:"explain_inaccessibility,omitempty"`
	// If past/historic reference data should be used (e.g. platform motion,
	// weather, etc) rather than current / most-recent data, this
	// field indicates the time for retrieving that reference data.
	ReferenceDataTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=reference_data_time,json=referenceDataTime" json:"reference_data_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignalPropagationRequest) Reset() {
	*x = SignalPropagationRequest{}
	mi := &file_api_nbi_v1alpha_signal_propagation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalPropagationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalPropagationRequest) ProtoMessage() {}

func (x *SignalPropagationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_signal_propagation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalPropagationRequest.ProtoReflect.Descriptor instead.
func (*SignalPropagationRequest) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_signal_propagation_proto_rawDescGZIP(), []int{0}
}

func (x *SignalPropagationRequest) GetTransmitterModel() *resources.TransceiverProvider {
	if x != nil {
		return x.TransmitterModel
	}
	return nil
}

func (x *SignalPropagationRequest) GetBandProfileId() string {
	if x != nil && x.BandProfileId != nil {
		return *x.BandProfileId
	}
	return ""
}

func (x *SignalPropagationRequest) GetTarget() *resources.TransceiverProvider {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SignalPropagationRequest) GetCoverage() *resources.CoordinateArray {
	if x != nil {
		return x.Coverage
	}
	return nil
}

func (x *SignalPropagationRequest) GetAnalysisTime() isSignalPropagationRequest_AnalysisTime {
	if x != nil {
		return x.AnalysisTime
	}
	return nil
}

func (x *SignalPropagationRequest) GetAnalysisInterval() *interval.Interval {
	if x != nil {
		if x, ok := x.AnalysisTime.(*SignalPropagationRequest_AnalysisInterval); ok {
			return x.AnalysisInterval
		}
	}
	return nil
}

func (x *SignalPropagationRequest) GetAnalysisInstant() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.AnalysisTime.(*SignalPropagationRequest_AnalysisInstant); ok {
			return x.AnalysisInstant
		}
	}
	return nil
}

func (x *SignalPropagationRequest) GetStepSize() *durationpb.Duration {
	if x != nil {
		return x.StepSize
	}
	return nil
}

func (x *SignalPropagationRequest) GetSpatialPropagationStepSize() *durationpb.Duration {
	if x != nil {
		return x.SpatialPropagationStepSize
	}
	return nil
}

func (x *SignalPropagationRequest) GetExplainInaccessibility() bool {
	if x != nil && x.ExplainInaccessibility != nil {
		return *x.ExplainInaccessibility
	}
	return false
}

func (x *SignalPropagationRequest) GetReferenceDataTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReferenceDataTime
	}
	return nil
}

type isSignalPropagationRequest_AnalysisTime interface {
	isSignalPropagationRequest_AnalysisTime()
}

type SignalPropagationRequest_AnalysisInterval struct {
	// The interval of time to evaluate signal propagation. This must be a
	// closed interval with both a start and end time.
	AnalysisInterval *interval.Interval `protobuf:"bytes,6,opt,name=analysis_interval,json=analysisInterval,oneof"`
}

type SignalPropagationRequest_AnalysisInstant struct {
	// The instant in time to evaluate signal propagation.
	AnalysisInstant *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=analysis_instant,json=analysisInstant,oneof"`
}

func (*SignalPropagationRequest_AnalysisInterval) isSignalPropagationRequest_AnalysisTime() {}

func (*SignalPropagationRequest_AnalysisInstant) isSignalPropagationRequest_AnalysisTime() {}

type SignalPropagationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A timeline of target accessibility (subject to geometric constraints).
	// Accessible intervals contain the modeled temporospatial signal propagation.
	// Access intervals are non-overlapping.
	AccessInterval []*resources.AccessInterval `protobuf:"bytes,1,rep,name=access_interval,json=accessInterval" json:"access_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SignalPropagationResponse) Reset() {
	*x = SignalPropagationResponse{}
	mi := &file_api_nbi_v1alpha_signal_propagation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalPropagationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalPropagationResponse) ProtoMessage() {}

func (x *SignalPropagationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nbi_v1alpha_signal_propagation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalPropagationResponse.ProtoReflect.Descriptor instead.
func (*SignalPropagationResponse) Descriptor() ([]byte, []int) {
	return file_api_nbi_v1alpha_signal_propagation_proto_rawDescGZIP(), []int{1}
}

func (x *SignalPropagationResponse) GetAccessInterval() []*resources.AccessInterval {
	if x != nil {
		return x.AccessInterval
	}
	return nil
}

var File_api_nbi_v1alpha_signal_propagation_proto protoreflect.FileDescriptor

const file_api_nbi_v1alpha_signal_propagation_proto_rawDesc = "" +
	"\n" +
	"(api/nbi/v1alpha/signal_propagation.proto\x12!aalyria.spacetime.api.nbi.v1alpha\x1a(api/nbi/v1alpha/resources/coverage.proto\x1a3api/nbi/v1alpha/resources/wireless_evaluation.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1agoogle/type/interval.proto\"\xa0\x06\n" +
	"\x18SignalPropagationRequest\x12m\n" +
	"\x11transmitter_model\x18\x01 \x01(\v2@.aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProviderR\x10transmitterModel\x12&\n" +
	"\x0fband_profile_id\x18\x02 \x01(\tR\rbandProfileId\x12X\n" +
	"\x06target\x18\x03 \x01(\v2@.aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProviderR\x06target\x12X\n" +
	"\bcoverage\x18\x04 \x01(\v2<.aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArrayR\bcoverage\x12D\n" +
	"\x11analysis_interval\x18\x06 \x01(\v2\x15.google.type.IntervalH\x00R\x10analysisInterval\x12G\n" +
	"\x10analysis_instant\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0fanalysisInstant\x126\n" +
	"\tstep_size\x18\a \x01(\v2\x19.google.protobuf.DurationR\bstepSize\x12\\\n" +
	"\x1dspatial_propagation_step_size\x18\t \x01(\v2\x19.google.protobuf.DurationR\x1aspatialPropagationStepSize\x127\n" +
	"\x17explain_inaccessibility\x18\b \x01(\bR\x16explainInaccessibility\x12J\n" +
	"\x13reference_data_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11referenceDataTimeB\x0f\n" +
	"\ranalysis_time\"\x81\x01\n" +
	"\x19SignalPropagationResponse\x12d\n" +
	"\x0faccess_interval\x18\x01 \x03(\v2;.aalyria.spacetime.api.nbi.v1alpha.resources.AccessIntervalR\x0eaccessInterval2\x9d\x01\n" +
	"\x11SignalPropagation\x12\x87\x01\n" +
	"\bEvaluate\x12;.aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest\x1a<.aalyria.spacetime.api.nbi.v1alpha.SignalPropagationResponse\"\x00BN\n" +
	"%com.aalyria.spacetime.api.nbi.v1alphaZ%aalyria.com/spacetime/api/nbi/v1alpha"

var (
	file_api_nbi_v1alpha_signal_propagation_proto_rawDescOnce sync.Once
	file_api_nbi_v1alpha_signal_propagation_proto_rawDescData []byte
)

func file_api_nbi_v1alpha_signal_propagation_proto_rawDescGZIP() []byte {
	file_api_nbi_v1alpha_signal_propagation_proto_rawDescOnce.Do(func() {
		file_api_nbi_v1alpha_signal_propagation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_signal_propagation_proto_rawDesc), len(file_api_nbi_v1alpha_signal_propagation_proto_rawDesc)))
	})
	return file_api_nbi_v1alpha_signal_propagation_proto_rawDescData
}

var file_api_nbi_v1alpha_signal_propagation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_nbi_v1alpha_signal_propagation_proto_goTypes = []any{
	(*SignalPropagationRequest)(nil),      // 0: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest
	(*SignalPropagationResponse)(nil),     // 1: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationResponse
	(*resources.TransceiverProvider)(nil), // 2: aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProvider
	(*resources.CoordinateArray)(nil),     // 3: aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArray
	(*interval.Interval)(nil),             // 4: google.type.Interval
	(*timestamppb.Timestamp)(nil),         // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),           // 6: google.protobuf.Duration
	(*resources.AccessInterval)(nil),      // 7: aalyria.spacetime.api.nbi.v1alpha.resources.AccessInterval
}
var file_api_nbi_v1alpha_signal_propagation_proto_depIdxs = []int32{
	2,  // 0: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.transmitter_model:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProvider
	2,  // 1: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.target:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.TransceiverProvider
	3,  // 2: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.coverage:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.CoordinateArray
	4,  // 3: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.analysis_interval:type_name -> google.type.Interval
	5,  // 4: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.analysis_instant:type_name -> google.protobuf.Timestamp
	6,  // 5: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.step_size:type_name -> google.protobuf.Duration
	6,  // 6: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.spatial_propagation_step_size:type_name -> google.protobuf.Duration
	5,  // 7: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest.reference_data_time:type_name -> google.protobuf.Timestamp
	7,  // 8: aalyria.spacetime.api.nbi.v1alpha.SignalPropagationResponse.access_interval:type_name -> aalyria.spacetime.api.nbi.v1alpha.resources.AccessInterval
	0,  // 9: aalyria.spacetime.api.nbi.v1alpha.SignalPropagation.Evaluate:input_type -> aalyria.spacetime.api.nbi.v1alpha.SignalPropagationRequest
	1,  // 10: aalyria.spacetime.api.nbi.v1alpha.SignalPropagation.Evaluate:output_type -> aalyria.spacetime.api.nbi.v1alpha.SignalPropagationResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_nbi_v1alpha_signal_propagation_proto_init() }
func file_api_nbi_v1alpha_signal_propagation_proto_init() {
	if File_api_nbi_v1alpha_signal_propagation_proto != nil {
		return
	}
	file_api_nbi_v1alpha_signal_propagation_proto_msgTypes[0].OneofWrappers = []any{
		(*SignalPropagationRequest_AnalysisInterval)(nil),
		(*SignalPropagationRequest_AnalysisInstant)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_nbi_v1alpha_signal_propagation_proto_rawDesc), len(file_api_nbi_v1alpha_signal_propagation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_nbi_v1alpha_signal_propagation_proto_goTypes,
		DependencyIndexes: file_api_nbi_v1alpha_signal_propagation_proto_depIdxs,
		MessageInfos:      file_api_nbi_v1alpha_signal_propagation_proto_msgTypes,
	}.Build()
	File_api_nbi_v1alpha_signal_propagation_proto = out.File
	file_api_nbi_v1alpha_signal_propagation_proto_goTypes = nil
	file_api_nbi_v1alpha_signal_propagation_proto_depIdxs = nil
}
